-- Superseded by 0031_invoice_workspace.sql, which independently added every
-- column and the invoice_line_items table this migration would have created.
--
-- Left as a no-op instead of deleted so wrangler's migration ledger keeps
-- a slot at 0030 and the two hosts (dev / prod) stay in agreement about
-- which migrations have been recorded. Dropping this file would either
-- cause wrangler to reapply everything above 0030 on any db that already
-- has this row, or leave the prod ledger permanently out of step with
-- the tree. A single-statement SELECT is D1's cheapest way to say
-- "already handled" here.
SELECT 1;
