export {
  PUBLIC_SITE_URL,
  PUBLIC_SITE_BASE,
  SECURE_ORIGIN,
  LEGACY_HQ_ORIGIN,
  LEGACY_PORTAL_ORIGIN,
  HQ_APP_ORIGIN,
  PORTAL_APP_ORIGIN,
  PORTAL_WWW_BASE,
  HQ_WWW_LOGIN,
  PORTAL_WWW_LOGIN,
  portalUrl,
  hqUrl,
  portalLoginUrl,
  hqLoginUrl,
  portalSetupUrl,
  hqSetupUrl,
  accountSetupUrl,
  wwwPortalUrl,
  vendorSignupUrl,
} from '../../shared/appUrls'
