export {
  PUBLIC_SITE_URL,
  SECURE_ORIGIN,
  LEGACY_HQ_ORIGIN,
  LEGACY_PORTAL_ORIGIN,
  HQ_APP_ORIGIN,
  PORTAL_APP_ORIGIN,
  PORTAL_WWW_BASE,
  HQ_WWW_LOGIN,
  PORTAL_WWW_LOGIN,
  portalUrl,
  hqUrl,
  wwwPortalUrl,
  portalLoginUrl,
  hqLoginUrl,
  setupPasswordUrl,
} from '../../shared/appUrls'
