import { PDFDocument, StandardFonts, rgb, type PDFFont, type PDFPage } from 'pdf-lib'
import type { ReportColumn, ReportResult } from './reportRegistry'

const W = 612, H = 792, M = 42, CONTENT = W - M * 2
const NAVY = rgb(0.035, 0.075, 0.14)
const GOLD = rgb(0.78, 0.61, 0.23)
const SLATE = rgb(0.34, 0.38, 0.45)
const PALE = rgb(0.94, 0.95, 0.97)

function value(v: unknown, type?: ReportColumn['type']) {
  if (v == null) return '—'
  if (type === 'money') return `$${(Number(v) / 100).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`
  if (type === 'percent') return `${v}%`
  if (typeof v === 'number') return v.toLocaleString()
  return String(v)
}

function wrap(text: string, font: PDFFont, size: number, width: number) {
  const words = String(text || '').replace(/\s+/g, ' ').trim().split(' ').filter(Boolean)
  const lines: string[] = []; let line = ''
  for (const word of words) {
    const next = line ? `${line} ${word}` : word
    if (font.widthOfTextAtSize(next, size) <= width) line = next
    else { if (line) lines.push(line); line = word }
  }
  if (line) lines.push(line)
  return lines.length ? lines : ['']
}

export async function renderReportPdf(input: { key: string; label: string; description?: string; from: string; to: string; result: ReportResult; generatedBy: string; logoBytes?: ArrayBuffer | Uint8Array | null }) {
  const pdf = await PDFDocument.create()
  pdf.setTitle(`${input.label} — Pinnacle Management Ventures`)
  pdf.setAuthor('Pinnacle Management Ventures')
  pdf.setSubject('Pinnacle Management Ventures report export')
  const regular = await pdf.embedFont(StandardFonts.Helvetica)
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold)
  let logo: Awaited<ReturnType<PDFDocument['embedPng']>> | null = null
  if (input.logoBytes) { try { logo = await pdf.embedPng(input.logoBytes) } catch { try { logo = await pdf.embedJpg(input.logoBytes) } catch { logo = null } } }
  let page!: PDFPage, y = 0
  const newPage = () => {
    page = pdf.addPage([W, H]); y = H - M
    page.drawRectangle({ x: 0, y: H - 7, width: W, height: 7, color: GOLD })
    page.drawText('Pinnacle Management Ventures', { x: M, y: 18, size: 7, font: regular, color: SLATE })
    page.drawText('Confidential business report', { x: W - M - 115, y: 18, size: 7, font: regular, color: SLATE })
  }
  const ensure = (h: number) => { if (y - h < 42) newPage() }
  const line = (text: string, size = 9, font = regular, color = NAVY, gap = 3) => {
    const lines = wrap(text, font, size, CONTENT); ensure(lines.length * (size + 3) + gap)
    for (const l of lines) { page.drawText(l, { x: M, y, size, font, color }); y -= size + 3 }
    y -= gap
  }

  newPage()
  if (logo) { const scaled = logo.scaleToFit(38, 38); page.drawImage(logo, { x: M, y: y - 33, width: scaled.width, height: scaled.height }) }
  const hx = logo ? M + 50 : M
  page.drawText('PINNACLE', { x: hx, y: y - 4, size: 17, font: bold, color: NAVY })
  page.drawText('MANAGEMENT VENTURES', { x: hx, y: y - 17, size: 7, font: bold, color: GOLD })
  y -= 56
  line(input.label, 22, bold, NAVY, 6)
  if (input.description) line(input.description, 9, regular, SLATE, 10)
  page.drawRectangle({ x: M, y: y - 24, width: CONTENT, height: 24, color: PALE })
  page.drawText(`Range: ${input.from.slice(0,10)} to ${input.to.slice(0,10)}`, { x: M + 9, y: y - 16, size: 8, font: bold, color: NAVY })
  page.drawText(`Generated by ${input.generatedBy}`, { x: M + 260, y: y - 16, size: 8, font: regular, color: SLATE })
  y -= 38

  const cols = input.result.columns.slice(0, 7)
  const colWidth = CONTENT / Math.max(1, cols.length)
  ensure(34)
  page.drawRectangle({ x: M, y: y - 22, width: CONTENT, height: 22, color: NAVY })
  cols.forEach((c, i) => page.drawText(c.label.slice(0, 24), { x: M + i * colWidth + 4, y: y - 14, size: 7, font: bold, color: rgb(1,1,1) }))
  y -= 26
  for (const row of input.result.rows.slice(0, 150)) {
    ensure(24)
    const rendered = cols.map((c) => value(row[c.key], c.type))
    const lines = rendered.map((v) => wrap(v, regular, 7.5, colWidth - 8).slice(0, 2))
    const rowHeight = Math.max(1, ...lines.map((l) => l.length)) * 10 + 7
    ensure(rowHeight)
    page.drawRectangle({ x: M, y: y - rowHeight + 3, width: CONTENT, height: rowHeight, borderColor: rgb(.86,.88,.91), borderWidth: .5 })
    lines.forEach((ls, i) => ls.forEach((l, n) => page.drawText(l, { x: M + i * colWidth + 4, y: y - 8 - n * 9, size: 7.5, font: regular, color: NAVY })))
    y -= rowHeight
  }
  if (input.result.rows.length > 150) line(`Showing first 150 of ${input.result.rows.length.toLocaleString()} rows. Use CSV export for the complete dataset.`, 8, regular, SLATE, 0)
  return pdf.save()
}
