import { useEffect, useMemo, useRef, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { api, ApiError } from '../../lib/api'
import { Card, PageHeader, StatusBadge } from '../../components/ui'
import { inputCls } from '../auth/AuthLayout'
import { useAppPath } from '../../lib/basePath'
import { InlineLoading } from '../../components/LoadingScreen'
import { DateSelect } from '../../components/kit/DateSelect'
import { Icon } from '../../components/kit/Icon'
import { DocumentUpload } from '../../components/forms/DocumentUpload'
import { displayValue, hasAnswer, parseOptions, questionVisible, type AnswerMap, type IntakeQuestion, type IntakeValue } from '../../lib/intake'

interface ServiceRow { key:string; name:string; description:string|null; category:string|null; intake_intro:string|null; estimated_minutes:number }
interface ApplicationRow { id:string; service_key:string; status:string; current_step:number; submission_source?:string; assigned_by_user_id?:string|null; assigned_at?:string|null; client_signature_name?:string|null; client_signed_at?:string|null; created_at:string; updated_at:string }
interface Attachment { id:string; document_id:string; question_key:string|null; file_name:string|null; content_type:string|null; size_bytes:number|null; visibility:string; created_at:string }
interface StartResponse { application:ApplicationRow; service:ServiceRow; questions:IntakeQuestion[]; answers:AnswerMap; prefill:AnswerMap; attachments:Attachment[]; client:{name:string;email:string;phone:string|null;business_name:string|null}; banking_supported:boolean }
interface CopyResponse { service_application_disclaimer:string; eviction_scope_disclaimer:string; service_application_contact_line:string }

type Step = { type:'intro'; label:string } | { type:'questions'; label:string; order:number; part:number; questions:IntakeQuestion[] } | { type:'banking'; label:string } | { type:'review'; label:string }
const TIME_WINDOWS=['Morning (8am–12pm)','Afternoon (12pm–5pm)','Evening (5pm–8pm)','Flexible']
const QUESTIONS_PER_PAGE = 3

function splitWindow(value:IntakeValue|undefined):[string,string]{ const raw=typeof value==='string'?value:''; const [date='',window='']=raw.split('|'); return [date,window] }
function fileSize(value:number|null){ if(!value)return undefined; return value<1024*1024?`${Math.max(1,Math.round(value/1024))} KB`:`${(value/(1024*1024)).toFixed(1)} MB` }

function ChoiceButtons({options,value,onChange,multiple=false}:{options:{value:string;label:string}[];value:string|string[];onChange:(value:string|string[])=>void;multiple?:boolean}){
  const selected=Array.isArray(value)?value:[value]
  return <div className="mt-2 divide-y divide-white/10 overflow-hidden rounded-lg border border-white/10">{options.map((option)=>{
    const active=selected.includes(option.value)
    return <button type="button" key={option.value} onClick={()=>multiple?onChange(active?selected.filter((item)=>item!==option.value):[...selected,option.value]):onChange(option.value)} className={`flex w-full items-center gap-3 px-4 py-3 text-left text-sm transition ${active?'bg-gold/[.07] text-white':'text-slate-300 hover:bg-white/[.025]'}`}><span className={`grid h-5 w-5 shrink-0 place-items-center border ${multiple?'rounded':'rounded-full'} ${active?'border-gold bg-gold text-navy-950':'border-white/20'}`}>{active?'✓':''}</span><span>{option.label}</span></button>
  })}</div>
}

function Question({q,value,answers,files,onChange,onUpload,onRemove,uploading}:{q:IntakeQuestion;value:IntakeValue|undefined;answers:AnswerMap;files:Attachment[];onChange:(v:IntakeValue)=>void;onUpload:(files:File[])=>Promise<void>;onRemove:(id:string)=>Promise<void>;uploading:boolean}){
  if(!questionVisible(q,answers))return null
  const options=parseOptions(q.options)
  const label=<><label htmlFor={q.id} className="block text-sm font-semibold text-white">{q.label}{q.required?<span className="text-gold"> *</span>:null}</label>{q.help_text&&<p className="mt-1 text-xs leading-5 text-slate-500">{q.help_text}</p>}</>
  if(q.input_type==='single_select') return <div>{label}{options.length<=7?<ChoiceButtons options={options} value={typeof value==='string'?value:''} onChange={(next)=>onChange(next as string)}/>:<select id={q.id} className={`${inputCls} mt-2`} value={typeof value==='string'?value:''} onChange={(e)=>onChange(e.target.value)}><option value="">Choose an option…</option>{options.map((o)=><option key={o.value} value={o.value}>{o.label}</option>)}</select>}</div>
  if(q.input_type==='toggle') return <div>{label}<ChoiceButtons options={[{value:'yes',label:'Yes'},{value:'no',label:'No'}]} value={typeof value==='boolean'?(value?'yes':'no'):''} onChange={(next)=>onChange(next==='yes')}/></div>
  if(q.input_type==='multi_select'){const selected=Array.isArray(value)?value:[];return <div>{label}<ChoiceButtons multiple options={options} value={selected} onChange={(next)=>onChange(next as string[])}/></div>}
  if(q.input_type==='date') return <div>{label}<div className="mt-2"><DateSelect value={typeof value==='string'?value:''} onChange={onChange} ariaLabel={q.label}/></div></div>
  if(q.input_type==='datetime_window'){const [date,window]=splitWindow(value);return <div>{label}<div className="mt-2 grid gap-2 sm:grid-cols-[1.3fr_1fr]"><DateSelect value={date} onChange={(d)=>onChange(`${d}|${window}`)} ariaLabel={q.label}/><select className={inputCls} value={window} onChange={(e)=>onChange(`${date}|${e.target.value}`)}><option value="">Time window…</option>{TIME_WINDOWS.map((w)=><option key={w}>{w}</option>)}</select></div></div>}
  if(q.input_type==='textarea') return <div>{label}<textarea id={q.id} className={`${inputCls} mt-2 min-h-24`} value={typeof value==='string'?value:''} onChange={(e)=>onChange(e.target.value)} placeholder="A short answer is fine. Add only what helps us understand the situation."/></div>
  if(q.input_type==='file'){
    const attached=files.filter((file)=>file.question_key===q.question_key)
    return <DocumentUpload label={q.label} help={q.help_text||'Take a photo from your phone or choose a file. Your upload is saved securely with this application.'} required={!!q.required} multiple={!!q.allow_multiple} files={attached.map((file)=>({id:file.document_id,name:file.file_name||'Uploaded document',detail:fileSize(file.size_bytes)}))} uploading={uploading} onFiles={onUpload} onRemove={onRemove}/>
  }
  const numeric=q.input_type==='number'||q.input_type==='currency'
  return <div>{label}<div className={`relative mt-2 ${q.input_type==='currency'?'pl-0':''}`}>{q.input_type==='currency'&&<span className="pointer-events-none absolute left-3 top-1/2 -translate-y-1/2 text-slate-500">$</span>}<input id={q.id} className={`${inputCls} ${q.input_type==='currency'?'!pl-7':''}`} type={numeric?'number':'text'} step={q.input_type==='currency'?'.01':numeric?'1':undefined} inputMode={numeric?'decimal':undefined} value={typeof value==='string'||typeof value==='number'?value:''} onChange={(e)=>onChange(e.target.value)} autoComplete={q.input_type==='address'?'street-address':undefined}/></div></div>
}

export default function ServiceApplication(){
  const {key}=useParams<{key:string}>(); const p=useAppPath(); const saveTimer=useRef<number|null>(null); const hydrated=useRef(false)
  const [loading,setLoading]=useState(true); const [application,setApplication]=useState<ApplicationRow|null>(null); const [service,setService]=useState<ServiceRow|null>(null); const [questions,setQuestions]=useState<IntakeQuestion[]>([]); const [answers,setAnswers]=useState<AnswerMap>({}); const [attachments,setAttachments]=useState<Attachment[]>([]); const [client,setClient]=useState<StartResponse['client']|null>(null); const [bankingSupported,setBankingSupported]=useState(false); const [copy,setCopy]=useState<CopyResponse|null>(null); const [step,setStep]=useState(0); const [saveState,setSaveState]=useState<'idle'|'saving'|'saved'|'error'>('idle'); const [error,setError]=useState<string|null>(null); const [busy,setBusy]=useState(false); const [done,setDone]=useState(false); const [uploading,setUploading]=useState<string|null>(null); const [signatureName,setSignatureName]=useState(''); const [signatureIntent,setSignatureIntent]=useState(false); const [skipBanking,setSkipBanking]=useState(true); const [banking,setBanking]=useState({account_holder_name:'',bank_name:'',account_type:'checking',routing_number:'',account_number:''})

  useEffect(()=>{if(!key)return;hydrated.current=false;(async()=>{try{const [started,copyResult]=await Promise.all([api.post<StartResponse>(`/portal/service-applications/${key}/start`),api.get<CopyResponse>('/portal/application-copy')]);setApplication(started.application);setService(started.service);setQuestions(started.questions);setAnswers({...started.prefill,...started.answers});setAttachments(started.attachments);setClient(started.client);setBankingSupported(started.banking_supported);setCopy(copyResult);setStep(Math.max(0,started.application.current_step||0));setSignatureName(started.application.client_signature_name||started.client.name||'');hydrated.current=true}catch(err){setError(err instanceof ApiError?err.message:'Could not open this application.')}finally{setLoading(false)}})();return()=>{if(saveTimer.current)window.clearTimeout(saveTimer.current)}},[key])

  const visibleQuestions=useMemo(()=>questions.filter((q)=>questionVisible(q,answers)),[questions,answers])
  const steps=useMemo<Step[]>(()=>{
    const groups=new Map<number,{label:string;questions:IntakeQuestion[]}>()
    for(const q of visibleQuestions){if(!groups.has(q.step_order))groups.set(q.step_order,{label:q.step_label||'Details',questions:[]});groups.get(q.step_order)!.questions.push(q)}
    const questionSteps:Step[]=[]
    for(const [order,group] of Array.from(groups.entries()).sort((a,b)=>a[0]-b[0])){
      const chunks=[] as IntakeQuestion[][]
      for(let index=0;index<group.questions.length;index+=QUESTIONS_PER_PAGE)chunks.push(group.questions.slice(index,index+QUESTIONS_PER_PAGE))
      chunks.forEach((chunk,part)=>questionSteps.push({type:'questions',label:chunks.length>1?`${group.label} · ${part+1} of ${chunks.length}`:group.label,order,part,questions:chunk}))
    }
    return [{type:'intro',label:'Overview'},...questionSteps,...(bankingSupported?[{type:'banking' as const,label:'Banking'}]:[]),{type:'review',label:'Review & sign'}]
  },[visibleQuestions,bankingSupported])
  useEffect(()=>{if(step>steps.length-1)setStep(Math.max(0,steps.length-1))},[step,steps.length])
  const current=steps[Math.min(step,steps.length-1)]

  useEffect(()=>{if(!hydrated.current||!application||done)return;if(saveTimer.current)window.clearTimeout(saveTimer.current);setSaveState('saving');saveTimer.current=window.setTimeout(()=>{api.patch(`/portal/service-applications/${application.id}`,{answers,current_step:step}).then(()=>setSaveState('saved')).catch(()=>setSaveState('error'))},700);return()=>{if(saveTimer.current)window.clearTimeout(saveTimer.current)}},[answers,step,application,done])

  function complete(q:IntakeQuestion){if(q.input_type==='file')return attachments.some((a)=>a.question_key===q.question_key);if(q.input_type==='datetime_window'){const[d,w]=splitWindow(answers[q.question_key]);return!!d&&!!w}if(q.question_key.endsWith('_ack'))return answers[q.question_key]===true;return hasAnswer(answers[q.question_key])}
  function validateCurrent(){if(current?.type==='questions'){for(const q of current.questions)if(q.required&&!complete(q))return `Please complete “${q.label}” before continuing.`}if(current?.type==='banking'&&!skipBanking){const started=Object.values(banking).some(Boolean);if(started&&(!banking.account_holder_name||!/^[0-9]{9}$/.test(banking.routing_number)||!banking.account_number))return 'Complete the account holder, 9-digit routing number, and account number, or choose Provide later.'}return null}
  async function saveNow(next=step){if(!application)return;if(saveTimer.current)window.clearTimeout(saveTimer.current);setSaveState('saving');try{await api.patch(`/portal/service-applications/${application.id}`,{answers,current_step:next});setSaveState('saved')}catch{setSaveState('error')}}
  async function go(next:number){const message=next>step?validateCurrent():null;if(message){setError(message);return}setError(null);await saveNow(next);setStep(Math.max(0,Math.min(next,steps.length-1)));window.scrollTo({top:0,behavior:'smooth'})}

  async function upload(q:IntakeQuestion,files:File[]){if(!application)return;setUploading(q.question_key);setError(null);try{for(const file of (q.allow_multiple?files:files.slice(0,1))){const res=await api.upload<{document?:Attachment}>(`/portal/service-applications/${application.id}/files/${q.question_key}`,file);if(res.document)setAttachments((cur)=>[...cur,res.document!])}}catch(err){setError(err instanceof ApiError?err.message:'Could not upload that file.')}finally{setUploading(null)}}
  async function removeFile(id:string){if(!application)return;try{await api.del(`/portal/service-applications/${application.id}/files/${id}`);setAttachments((cur)=>cur.filter((a)=>a.document_id!==id))}catch(err){setError(err instanceof ApiError?err.message:'Could not remove that file.')}}

  async function submit(){if(!application)return;const missing=visibleQuestions.filter((q)=>q.required&&!complete(q));if(missing.length){const first=missing[0];const idx=steps.findIndex((s)=>s.type==='questions'&&s.questions.some((q)=>q.id===first.id));setError(`Please finish “${first.label}” before submitting.`);if(idx>=0)setStep(idx);return}if(!signatureIntent||signatureName.trim().length<2){setError('Type your full name and confirm the electronic signature checkbox.');return}setBusy(true);setError(null);try{await saveNow(step);await api.post(`/portal/service-applications/${application.id}/sign`,{signature_name:signatureName.trim(),intent:true});const payload:Record<string,unknown>={current_step:step};if(bankingSupported&&!skipBanking&&banking.account_holder_name&&banking.routing_number&&banking.account_number)payload.banking=banking;await api.post(`/portal/service-applications/${application.id}/submit`,payload);setDone(true);setSaveState('saved')}catch(err){setError(err instanceof ApiError?err.message:'Could not submit the application.')}finally{setBusy(false)}}

  if(loading)return <InlineLoading/>
  if(!service||!application)return <div><PageHeader eyebrow="Service application" title="We couldn't open this application"/><Card className="max-w-2xl"><p className="text-sm text-slate-300">{error||'This service is unavailable right now.'}</p><Link to={p('services')} className="btn-outline mt-5 inline-block">Back to My Services</Link></Card></div>
  if(done)return <div><PageHeader eyebrow="Application received" title={service.name}/><Card className="mx-auto max-w-2xl text-center"><div className="mx-auto grid h-14 w-14 place-items-center rounded-full border border-emerald-400/30 bg-emerald-400/10 text-emerald-300"><Icon name="check" size={26}/></div><h2 className="mt-5 text-2xl font-semibold text-white">You're all set.</h2><p className="mx-auto mt-2 max-w-lg text-sm leading-6 text-slate-300">We received your signed application and your Pinnacle team has been notified.</p><div className="mt-4"><StatusBadge tone="blue">Application received / in review</StatusBadge></div><p className="mt-5 text-xs text-slate-600">Application ID: {application.id}</p><Link to={p('services')} className="btn-gold mt-5 inline-block">Back to My Services</Link></Card></div>

  const progress=Math.round(((step+1)/steps.length)*100)
  const stepsLeft=Math.max(0,steps.length-step-1)
  return <div><PageHeader eyebrow={application.submission_source==='staff_assigned'?'Requested by your Pinnacle team':'Service application'} title={service.name} subtitle={service.description||undefined}/><div className="mx-auto max-w-3xl">
    {application.submission_source==='staff_assigned'&&<div className="mb-4 rounded-lg border border-gold/20 bg-gold/[.06] p-4 text-sm leading-6 text-slate-300"><strong className="text-gold">Your Pinnacle team started this for you.</strong> We prefilled information already on file. Please review it, finish anything missing, and sign when you're ready.</div>}
    <div className="mb-4 rounded-lg border border-white/10 bg-white/[.025] p-4"><div className="flex items-center justify-between gap-3 text-xs"><span className="font-semibold text-slate-300">Step {step+1} of {steps.length} · {current?.label}</span><span className="text-gold">{progress}% complete</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-gold transition-all" style={{width:`${progress}%`}}/></div><div className="mt-2 flex items-center justify-between text-[11px]"><span className={saveState==='error'?'text-rose-300':saveState==='saving'?'text-slate-500':'text-emerald-300'}>{saveState==='saving'?'Saving…':saveState==='saved'?'Progress saved':'Autosave on'}</span><span className={progress>=75?'font-medium text-emerald-300':'text-slate-500'}>{progress>=75?'Almost done':stepsLeft===1?'1 short step left':`${stepsLeft} short steps left`}</span></div></div>
    {error&&<div className="mb-4 rounded-lg border border-rose-400/20 bg-rose-400/[.06] p-3 text-sm text-rose-200">{error}</div>}

    <Card className="!p-0"><div className="border-b border-white/10 px-5 py-4"><p className="text-[10px] font-semibold uppercase tracking-[.16em] text-gold">{current?.label}</p></div><div className="p-5 sm:p-6">
      {current?.type==='intro'&&<div><h2 className="font-display text-3xl text-white">A few short steps. That's it.</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-300">We'll show only a few questions at a time and only request documents that make sense for {service.name}. Tap choices where possible, and leave whenever you need to — your progress saves automatically.</p>{client&&<div className="mt-5 grid gap-2 border-y border-white/10 py-4 text-sm sm:grid-cols-2"><div><span className="text-slate-500">Client</span><p className="text-white">{client.name}</p></div><div><span className="text-slate-500">Email</span><p className="text-white">{client.email}</p></div>{client.business_name&&<div><span className="text-slate-500">Business</span><p className="text-white">{client.business_name}</p></div>}{service.estimated_minutes>0&&<div><span className="text-slate-500">Typical time</span><p className="text-white">About {service.estimated_minutes} minutes</p></div>}</div>}</div>}
      {current?.type==='questions'&&<div className="space-y-6">{current.questions.map((q)=><Question key={q.id} q={q} value={answers[q.question_key]} answers={answers} files={attachments} onChange={(v)=>setAnswers((a)=>({...a,[q.question_key]:v}))} onUpload={(files)=>upload(q,files)} onRemove={removeFile} uploading={uploading===q.question_key}/>)}</div>}
      {current?.type==='banking'&&<div><h2 className="text-xl font-semibold text-white">Banking details</h2><p className="mt-2 text-sm leading-6 text-slate-400">Only provide banking if it is needed for this service and you're comfortable doing so now. You can leave this for your Pinnacle team to coordinate later.</p><ChoiceButtons options={[{value:'later',label:'Provide banking later'},{value:'now',label:'Provide banking now'}]} value={skipBanking?'later':'now'} onChange={(value)=>setSkipBanking(value==='later')}/>{!skipBanking&&<div className="mt-5 grid gap-4 sm:grid-cols-2"><label><span className="mb-1 block text-xs text-slate-400">Account holder</span><input className={inputCls} value={banking.account_holder_name} onChange={(e)=>setBanking((b)=>({...b,account_holder_name:e.target.value}))}/></label><label><span className="mb-1 block text-xs text-slate-400">Bank name</span><input className={inputCls} value={banking.bank_name} onChange={(e)=>setBanking((b)=>({...b,bank_name:e.target.value}))}/></label><label><span className="mb-1 block text-xs text-slate-400">Account type</span><select className={inputCls} value={banking.account_type} onChange={(e)=>setBanking((b)=>({...b,account_type:e.target.value}))}><option value="checking">Checking</option><option value="savings">Savings</option></select></label><label><span className="mb-1 block text-xs text-slate-400">Routing number</span><input inputMode="numeric" className={inputCls} value={banking.routing_number} onChange={(e)=>setBanking((b)=>({...b,routing_number:e.target.value.replace(/\D/g,'').slice(0,9)}))}/></label><label className="sm:col-span-2"><span className="mb-1 block text-xs text-slate-400">Account number</span><input inputMode="numeric" className={inputCls} value={banking.account_number} onChange={(e)=>setBanking((b)=>({...b,account_number:e.target.value.replace(/\s/g,'')}))}/></label></div>}</div>}
      {current?.type==='review'&&<div><div className="flex items-start justify-between gap-3"><div><h2 className="text-xl font-semibold text-white">Review & sign</h2><p className="mt-2 text-sm leading-6 text-slate-400">You're at the finish line. Scan the summary, go back if something needs changing, then sign.</p></div><Icon name="shield" size={24} className="text-gold"/></div><div className="mt-5 divide-y divide-white/5 border-y border-white/10">{visibleQuestions.filter((q)=>hasAnswer(answers[q.question_key])||q.input_type==='file').map((q)=><div key={q.id} className="grid gap-1 py-3 sm:grid-cols-[minmax(0,1fr)_minmax(0,1.2fr)] sm:gap-5"><dt className="text-xs text-slate-500">{q.label}</dt><dd className="text-sm text-slate-200">{q.input_type==='file'?attachments.filter((a)=>a.question_key===q.question_key).map((a)=>a.file_name).filter(Boolean).join(', ')||'—':displayValue(answers[q.question_key])}</dd></div>)}</div><div className="mt-6 rounded-lg border border-gold/20 bg-gold/[.05] p-4"><p className="text-sm font-semibold text-white">Electronic signature</p><p className="mt-1 text-xs leading-5 text-slate-400">By typing your name and checking the box, you agree that your typed name is your electronic signature for this application.</p><label className="mt-4 block"><span className="mb-1 block text-xs text-slate-400">Full legal name</span><input className={inputCls} value={signatureName} onChange={(e)=>setSignatureName(e.target.value)} autoComplete="name"/></label><label className="mt-3 flex items-start gap-2 text-sm leading-5 text-slate-300"><input className="mt-1" type="checkbox" checked={signatureIntent} onChange={(e)=>setSignatureIntent(e.target.checked)}/><span>I have reviewed this application and intend my typed name above to serve as my electronic signature.</span></label></div>{copy?.service_application_disclaimer&&<p className="mt-4 text-xs leading-5 text-slate-500">{copy.service_application_disclaimer}</p>}</div>}
    </div><div className="flex flex-wrap items-center justify-between gap-3 border-t border-white/10 px-5 py-4"><button type="button" disabled={step===0||busy} onClick={()=>void go(step-1)} className="btn-outline">Back</button>{current?.type==='review'?<button type="button" disabled={busy} onClick={()=>void submit()} className="btn-gold inline-flex items-center gap-2"><Icon name="send" size={15}/>{busy?'Submitting…':'Sign & submit'}</button>:<button type="button" disabled={busy} onClick={()=>void go(step+1)} className="btn-gold inline-flex items-center gap-2">Continue<Icon name="arrowRight" size={15}/></button>}</div></Card>
    <p className="mt-4 text-center text-xs text-slate-600">You can leave and come back later. Your saved draft stays in My Services.</p>
  </div></div>
}
