import { Link } from 'react-router-dom'
import { Header } from '../components/public/Header'
import { Footer } from '../components/public/Footer'
import { btnOutline, btnPrimary, CtaBand } from '../components/public/ui'
import { AmbientGlow, Reveal, StaggerGroup, staggerItem } from '../components/public/motion'
import { usePageMeta } from '../lib/usePageMeta'
import { WhiteGoldBrandMark } from '../components/ui'
import { Icon, type IconName } from '../components/kit/Icon'
import { motion } from 'motion/react'

const CLIENT_SIGNUP='/portal/signup?source=home'

const audiences:{icon:IconName;eyebrow:string;title:string;body:string;examples:string[]}[]=[
  {icon:'briefcase',eyebrow:'For business owners',title:'More capacity without another department.',body:'When operations, clients, systems, paperwork, vendors, or a transition need an experienced point person, Pinnacle steps in, gets oriented quickly, and keeps the work moving.',examples:['Operational support','Admin & project ownership','POS, payments & systems','Client escalations']},
  {icon:'building',eyebrow:'For property owners',title:'One relationship for the work around the property.',body:'From a single inspection or deep clean to turnover, eviction support, REO coordination, vendor access, and documented field work, you have one place to call and one record to follow.',examples:['Cleaning & readiness','Inspections & field visits','Turnover & REO support','Vendor coordination']},
  {icon:'file',eyebrow:'For professionals',title:'Reliable support behind the work you already do.',body:'Pinnacle helps professionals extend their reach with document preparation, filing, signing coordination, mobile notary, RON, field assistance, and dependable follow-through.',examples:['Documents & filing','Mobile notary & RON','Signing coordination','Local field support']},
]

const strengths=[
  ['Get oriented','Understand the people, systems, history, urgency, and real outcome before creating more motion.'],
  ['Own the follow-through','Keep clients informed, chase the handoffs, resolve blockers, and make sure the work does not disappear between teams.'],
  ['Handle the exceptions','Step into the unusual request, failed process, sensitive escalation, or incomplete file and work it toward a practical answer.'],
  ['Leave a clear record','Keep communication, documents, decisions, activity, and completion connected so everyone knows what happened next.'],
]

const requests=[
  ['A client or operational issue keeps bouncing between people','/services/business-operations'],
  ['I need admin or project capacity without hiring a full team','/services/business-operations'],
  ['A property needs to be inspected, cleaned, secured, or made ready','/services/property-field'],
  ['I need documents prepared, filed, delivered, signed, or notarized','/services/mobile-documents'],
  ['I need someone dependable on site in South Florida','/projects/local-support-south-florida'],
]

export default function Home(){
  usePageMeta('Pinnacle Management Ventures - Practical Support That Stays With the Work','A dependable support partner for business owners, property owners, and professionals. Operations, administration, documents, notary, RON, field services, and provider coordination through one accountable relationship.')
  return <div className="min-h-screen bg-navy-950"><Header/><main>
    <section className="pmv-hero-story relative min-h-[calc(100vh-68px)] overflow-hidden border-b border-white/[.07]"><AmbientGlow/><div className="pmv-home-grid" aria-hidden="true"/><div className="container-pmv relative z-10 grid min-h-[calc(100vh-68px)] gap-8 py-14 lg:grid-cols-[1.08fr_.92fr] lg:items-center lg:py-20">
      <Reveal><p className="text-xs font-bold uppercase tracking-[.18em] text-gold">Pinnacle Management Ventures</p><h1 className="mt-5 max-w-4xl font-display text-5xl font-semibold leading-[.98] tracking-[-.045em] text-white sm:text-6xl lg:text-7xl xl:text-[5.5rem]">The person you call when it <span className="pmv-gold-text">needs to get handled.</span></h1><p className="mt-7 max-w-2xl text-lg leading-8 text-slate-300 sm:text-xl">Practical, experienced support for business owners, property owners, and professionals who need someone to understand the situation, coordinate the right people, and stay with the work through completion.</p><p className="mt-4 max-w-xl text-sm leading-7 text-slate-500">One defined task, a sensitive client issue, a property project, or ongoing operating support. Start with what is happening. We will help make the next step clear.</p><div className="mt-9 flex flex-wrap gap-3"><a href={CLIENT_SIGNUP} className={btnPrimary}>Tell Us What’s Going On</a><Link to="/contact" className={btnOutline}>Talk With Pinnacle</Link></div><div className="mt-8 flex flex-wrap gap-x-7 gap-y-2 text-xs font-semibold uppercase tracking-[.12em] text-slate-500"><span>Nationwide remote support</span><span>South Florida field coverage</span><span>Secure client workspace</span></div></Reveal>
      <Reveal className="relative flex min-h-[360px] items-center justify-center lg:min-h-[520px] lg:justify-end"><motion.div className="pmv-free-floating-mark" animate={{y:[0,-18,4,0],x:[0,10,-6,0],rotate:[-1.5,1.5,-.75,-1.5]}} transition={{duration:10,repeat:Infinity,ease:'easeInOut'}}><WhiteGoldBrandMark size={360} decorative/></motion.div><motion.p className="absolute bottom-6 right-0 max-w-[250px] border-l border-gold/40 pl-4 text-sm leading-6 text-slate-400 lg:bottom-16" animate={{y:[0,-6,0]}} transition={{duration:7,repeat:Infinity,ease:'easeInOut'}}>Clear communication. Calm ownership. No disappearing between handoffs.</motion.p></Reveal>
    </div></section>

    <section className="container-pmv py-16 sm:py-20"><Reveal className="max-w-4xl"><p className="eyebrow">Support built around the person asking</p><h2 className="mt-3 font-display text-3xl font-semibold leading-tight text-white sm:text-5xl">You should not have to know which department, vendor, or service label comes first.</h2><p className="mt-5 max-w-3xl text-base leading-8 text-slate-400">Pinnacle is the capable point of contact between the issue and the outcome. We help define what needs to happen, bring the right resources together, communicate with the people involved, and keep ownership visible until the work is closed out.</p></Reveal><StaggerGroup className="mt-10 grid gap-4 lg:grid-cols-3">{audiences.map(item=><motion.article variants={staggerItem} key={item.title} className="group rounded-2xl border border-white/[.08] bg-white/[.018] p-6 transition hover:-translate-y-1 hover:border-gold/25 hover:bg-gold/[.025] sm:p-7"><div className="flex items-center gap-3 text-gold"><Icon name={item.icon} size={22}/><p className="text-xs font-bold uppercase tracking-[.14em]">{item.eyebrow}</p></div><h3 className="mt-5 font-display text-2xl font-semibold leading-tight text-white">{item.title}</h3><p className="mt-4 text-sm leading-7 text-slate-400">{item.body}</p><div className="mt-6 flex flex-wrap gap-2">{item.examples.map(x=><span key={x} className="rounded-full border border-white/10 px-3 py-1 text-xs text-slate-500">{x}</span>)}</div></motion.article>)}</StaggerGroup></section>

    <section className="border-y border-gold/15 bg-gradient-to-br from-gold/[.055] via-white/[.012] to-transparent"><div className="container-pmv grid gap-10 py-16 lg:grid-cols-[.72fr_1.28fr] lg:items-start"><Reveal><p className="eyebrow">What you are really hiring</p><h2 className="mt-3 font-display text-3xl font-semibold text-white sm:text-4xl">Judgment, ownership, and follow-through.</h2><p className="mt-5 text-sm leading-7 text-slate-400">The service matters. How it is handled matters more. Pinnacle brings the relationship management, process control, escalation experience, and steady communication that keep real-world work from becoming another loose end.</p><Link to="/about" className="mt-6 inline-flex items-center gap-2 text-sm font-bold text-gold">How Pinnacle works <span>→</span></Link></Reveal><div className="divide-y divide-white/10 border-y border-white/10">{strengths.map(([title,body],i)=><Reveal key={title} delay={i*.05} className="grid gap-3 py-5 sm:grid-cols-[42px_180px_1fr] sm:items-start"><span className="font-display text-xs text-gold/60">0{i+1}</span><h3 className="text-sm font-bold text-white">{title}</h3><p className="text-sm leading-6 text-slate-400">{body}</p></Reveal>)}</div></div></section>

    <section className="container-pmv py-16 sm:py-20"><Reveal className="grid gap-10 lg:grid-cols-[.72fr_1.28fr]"><div><p className="eyebrow">A good place to start</p><h2 className="mt-3 font-display text-3xl font-semibold text-white sm:text-4xl">Tell us the situation in plain English.</h2><p className="mt-5 max-w-md text-sm leading-7 text-slate-400">You do not need a polished scope of work. Give us the issue, the people involved, the location, and the timing. We will help separate what Pinnacle can handle directly from what should be coordinated through a qualified provider.</p></div><div className="divide-y divide-white/10 border-y border-white/10">{requests.map(([label,to],i)=><Link key={label} to={to} className="group flex items-center justify-between gap-5 py-5"><div className="flex items-center gap-4"><span className="font-display text-xs text-gold/60">0{i+1}</span><span className="text-sm font-semibold text-slate-200 transition group-hover:text-gold sm:text-base">{label}</span></div><span className="text-gold transition-transform group-hover:translate-x-1">→</span></Link>)}</div></Reveal></section>

    <section className="pmv-trust-strip border-y border-gold/15"><div className="container-pmv grid gap-7 py-9 sm:grid-cols-2 lg:grid-cols-4">{[['Responsive','A real point person who communicates and keeps the next step visible.'],['Connected','Business, property, documents, field work, and providers stay in one relationship.'],['Documented','Secure records, updates, files, photos, signatures, and completion history.'],['Flexible','One-time request, defined project, transition support, or ongoing capacity.']].map(([a,b])=><Reveal key={a}><strong className="font-display text-2xl font-semibold text-white">{a}</strong><p className="mt-2 text-sm leading-6 text-slate-400">{b}</p></Reveal>)}</div></section>

    <CtaBand title="What needs your attention right now?" body="Bring us the request that is sitting unfinished, crossing too many people, or taking more of your time than it should." primary={{to:CLIENT_SIGNUP,label:'Start the Conversation'}} secondary={{to:'/services',label:'Explore Capabilities'}}/>
  </main><Footer/></div>
}
