import { Link } from 'react-router-dom'
import { Header } from '../components/public/Header'
import { Footer } from '../components/public/Footer'
import { btnOutline, btnPrimary, CtaBand } from '../components/public/ui'
import { AmbientGlow, Marquee, Reveal } from '../components/public/motion'
import { usePageMeta } from '../lib/usePageMeta'
import { BrandMark3D } from '../components/ui'
import { Icon, type IconName } from '../components/kit/Icon'

const CLIENT_SIGNUP='/portal/signup?source=home'
const pathways:{n:string;icon:IconName;title:string;body:string;to:string;note:string}[]=[
  {n:'01',icon:'briefcase',title:'Business Consulting & Transitions',body:'Operational changes, POS and payment transitions, systems, vendors, data, and implementation support.',to:'/services/business-operations',note:'Consulting + implementation'},
  {n:'02',icon:'building',title:'Property & Field Support',body:'Dependable local follow-through for inspections, field verification, access, vendors, and property needs.',to:'/services/property-field',note:'South Florida field coverage'},
  {n:'03',icon:'file',title:'Documents & Mobile Services',body:'Mobile notary, signing support, courier work, document delivery, and other defined local assignments.',to:'/services/mobile-documents',note:'Local mobile support'},
]
const startingPoints=[
  ['Switching POS or payment providers','/projects/switching-pos-payment-providers'],
  ['Moving data between systems','/projects/moving-data-between-systems'],
  ['Managing a business transition','/projects/managing-business-transition'],
  ['Need someone local in South Florida','/projects/local-support-south-florida'],
  ['Ongoing administrative support','/projects/ongoing-administrative-support'],
]

export default function Home(){
  usePageMeta('Business Consulting & Professional Services','Pinnacle Management Ventures helps businesses move operational changes from strategy through implementation, including POS and payment transitions, project coordination, property and field support, and mobile professional services.')
  return <div className="min-h-screen bg-navy-950"><Header/><main>
    <section className="pmv-hero-story relative overflow-hidden border-b border-white/[.08]"><AmbientGlow/><div className="pmv-hero-gold" aria-hidden="true"/><div className="container-pmv relative z-10 grid gap-10 py-16 sm:py-20 lg:grid-cols-[1.04fr_.96fr] lg:items-center lg:py-24 xl:py-28">
      <Reveal><p className="text-xs font-bold uppercase tracking-[.16em] text-gold">Consulting + Implementation Support · South Florida + Remote</p><h1 className="mt-5 max-w-5xl font-display text-5xl font-semibold leading-[1.01] tracking-[-.04em] text-white sm:text-6xl lg:text-7xl xl:text-[5.35rem]">Turn a complicated business change into <span className="pmv-gold-text">a clear plan and a finished project.</span></h1><p className="mt-7 max-w-2xl text-lg leading-8 text-slate-300 sm:text-xl">Pinnacle helps when a transition, migration, vendor change, property need, or cross-functional project needs one accountable point of coordination.</p><div className="mt-9 flex flex-wrap gap-3"><a href={CLIENT_SIGNUP} className={btnPrimary}>Start Your Journey</a><Link to="/services" className={btnOutline}>Explore Capabilities</Link></div></Reveal>
      <Reveal className="relative flex min-h-[390px] items-center justify-center lg:justify-end"><div className="pmv-hero-logo-shell"><div className="pmv-story-orbit pmv-story-orbit-animated" aria-hidden="true"/><div className="pmv-story-orbit pmv-story-orbit-animated-secondary" aria-hidden="true"/><BrandMark3D size={285} decorative className="pmv-hero-brand relative z-20"/><div className="pmv-story-note pmv-story-note-a"><span>Define</span><strong>Know what needs to change</strong></div><div className="pmv-story-note pmv-story-note-b"><span>Coordinate</span><strong>Keep the moving pieces connected</strong></div><div className="pmv-story-note pmv-story-note-c"><span>Deliver</span><strong>Stay with it through closeout</strong></div></div></Reveal>
    </div><Marquee items={['POS & payment transitions','Operational consulting','Data & vendor coordination','Project implementation','Property & field support','Mobile professional services']}/></section>

    <section className="container-pmv py-14 sm:py-18"><Reveal className="max-w-3xl"><p className="eyebrow">Where Pinnacle Fits</p><h2 className="mt-3 font-display text-3xl font-semibold text-white sm:text-4xl">Bring us the work that keeps crossing teams, vendors, systems, or locations.</h2></Reveal><div className="mt-8 border-y border-white/10">{pathways.map(item=><Reveal key={item.title}><Link to={item.to} className="group grid gap-4 border-b border-white/10 py-6 last:border-b-0 sm:grid-cols-[54px_48px_minmax(190px,.72fr)_1.28fr_auto] sm:items-center"><span className="font-display text-xs text-gold/70">{item.n}</span><span className="text-gold"><Icon name={item.icon} size={21}/></span><div><h3 className="text-lg font-bold text-white transition group-hover:text-gold">{item.title}</h3><p className="mt-1 text-xs font-semibold uppercase tracking-[.1em] text-slate-500">{item.note}</p></div><p className="max-w-2xl text-sm leading-6 text-slate-400">{item.body}</p><span className="text-gold transition-transform group-hover:translate-x-1">→</span></Link></Reveal>)}</div></section>

    <section className="pmv-gold-band border-y border-gold/15"><div className="container-pmv py-12 sm:py-14"><Reveal className="grid gap-8 lg:grid-cols-[.8fr_1.2fr] lg:items-center"><div><p className="eyebrow">How We Help</p><h2 className="mt-3 font-display text-3xl font-semibold text-white sm:text-4xl">Advice is useful. Follow-through is what gets the work finished.</h2></div><div><p className="max-w-2xl text-base leading-7 text-slate-300">We stay close to execution, keep the right people connected, surface blockers, and make the next step clear. When specialized expertise is needed, we work alongside the appropriate professional without losing sight of the larger project.</p><div className="mt-5 flex flex-wrap gap-x-7 gap-y-2 text-sm text-slate-400"><span>One accountable relationship</span><span>Flexible project scopes</span><span>Secure client workspace</span></div></div></Reveal></div></section>

    <section className="container-pmv py-14 sm:py-18"><Reveal className="grid gap-8 lg:grid-cols-[.72fr_1.28fr]"><div><p className="eyebrow">Common Starting Points</p><h2 className="mt-3 font-display text-3xl font-semibold text-white sm:text-4xl">You do not need to know the service name before you reach out.</h2><p className="mt-4 max-w-md text-sm leading-6 text-slate-400">Start with the situation. These are a few of the projects clients commonly need help moving forward.</p></div><div className="divide-y divide-white/10 border-y border-white/10">{startingPoints.map(([label,to],i)=><Link key={to} to={to} className="group flex items-center justify-between gap-5 py-4"><div className="flex items-center gap-4"><span className="font-display text-xs text-gold/60">0{i+1}</span><span className="text-sm font-semibold text-slate-200 transition group-hover:text-gold">{label}</span></div><span className="text-gold transition-transform group-hover:translate-x-1">→</span></Link>)}</div></Reveal></section>

    <section className="container-pmv pb-14 sm:pb-18"><Reveal className="grid gap-8 border-t border-white/10 pt-10 lg:grid-cols-[.72fr_1.28fr]"><div><p className="eyebrow">How We Work</p><h2 className="mt-3 font-display text-3xl font-semibold text-white">A practical path from open issue to handled.</h2><Link to="/about" className="mt-5 inline-block text-sm font-bold text-gold">How Pinnacle Works →</Link></div><div className="pmv-process-line">{[['01','Define','Get clear on the outcome and what cannot break.'],['02','Map','Identify the people, systems, vendors, and dependencies.'],['03','Coordinate','Keep communication, handoffs, and blockers visible.'],['04','Close','Verify completion and make the next operating step clear.']].map(([n,t,b])=><div key={n} className="pmv-process-step"><span>{n}</span><div><h3>{t}</h3><p>{b}</p></div></div>)}</div></Reveal></section>

    <section className="pmv-trust-strip border-y border-gold/15"><div className="container-pmv grid gap-7 py-8 sm:grid-cols-2 lg:grid-cols-4">{[['South Florida','Local field and mobile coverage'],['Remote-Ready','Consulting and transition support beyond South Florida'],['Secure','Centralized documents and communication'],['Flexible','Project, transition, task, or ongoing support']].map(([a,b])=><div key={a}><strong className="font-display text-2xl font-semibold text-white">{a}</strong><p className="mt-1 text-sm leading-6 text-slate-400">{b}</p></div>)}</div></section>

    <CtaBand title="What needs an owner right now?" body="Start with the situation. We will help determine the right scope and next move." primary={{to:CLIENT_SIGNUP,label:'Start Your Journey'}} secondary={{to:'/contact',label:'Talk With Pinnacle'}}/>
  </main><Footer/></div>
}
