import { Link } from 'react-router-dom'
import { Header } from '../components/public/Header'
import { Footer } from '../components/public/Footer'
import { btnOutline, btnPrimary, CtaBand } from '../components/public/ui'
import { AmbientGlow, Marquee, Reveal } from '../components/public/motion'
import { usePageMeta } from '../lib/usePageMeta'
import { BrandMark3D } from '../components/ui'
import { Icon, type IconName } from '../components/kit/Icon'

const CLIENT_SIGNUP='https://secure.pinnaclemanagementventures.com/signup?source=home'
const pathways:{n:string;icon:IconName;title:string;body:string;to:string;note:string}[]=[
  {n:'01',icon:'briefcase',title:'Business Consulting & Transitions',body:'Move operational changes from decision to implementation: POS and payment migrations, process improvement, vendor changes, administrative projects, data coordination, and follow-through.',to:'/services/business-operations',note:'Strategy + implementation'},
  {n:'02',icon:'building',title:'Property & Field Support',body:'Put dependable local execution behind remote ownership and operations with inspections, vendor coordination, field verification, access support, and documented follow-up.',to:'/services/property-field',note:'South Florida field coverage'},
  {n:'03',icon:'file',title:'Documents & Mobile Services',body:'Handle defined document and mobile assignments with a clear chain of responsibility, including mobile notary, courier, signing support, and document delivery.',to:'/services/mobile-documents',note:'Local mobile support'},
]

export default function Home(){
  usePageMeta('Business Consulting & Professional Services','Pinnacle Management Ventures helps businesses move operational changes from strategy through implementation, including POS and payment transitions, project coordination, property and field support, and mobile professional services.')
  return <div className="min-h-screen bg-navy-950"><Header/><main>
    <section className="pmv-hero-story relative overflow-hidden border-b border-white/[.08]"><AmbientGlow/><div className="pmv-hero-gold" aria-hidden="true"/><div className="container-pmv relative z-10 grid gap-12 py-16 sm:py-20 lg:grid-cols-[1.03fr_.97fr] lg:items-center lg:py-24 xl:py-28">
      <Reveal><p className="text-xs font-semibold uppercase tracking-[.16em] text-gold">Consulting + Implementation Support · South Florida + Remote</p><h1 className="mt-5 max-w-5xl font-display text-5xl font-medium leading-[1.01] tracking-[-.04em] text-white sm:text-6xl lg:text-7xl xl:text-[5.35rem]">Turn a complicated business change into <span className="pmv-gold-text">a clear plan and a finished project.</span></h1><p className="mt-7 max-w-2xl text-lg leading-8 text-slate-300 sm:text-xl">Pinnacle Management Ventures helps businesses move operational work from decision to execution. We step in when a transition, migration, vendor change, process problem, or cross-functional project needs one accountable point of coordination.</p><p className="mt-4 max-w-2xl text-base leading-7 text-slate-400">That includes hands-on support for POS and payment transitions, data and vendor coordination, administrative projects, process improvement, property needs, and implementation work that cannot afford to stall between teams.</p><div className="mt-9 flex flex-wrap gap-3"><a href={CLIENT_SIGNUP} className={btnPrimary}>Discuss Your Project</a><Link to="/services" className={btnOutline}>Explore Capabilities</Link></div><div className="mt-9 grid max-w-2xl gap-3 border-t border-white/10 pt-5 text-sm text-slate-400 sm:grid-cols-3"><span><strong className="block text-slate-200">Define</strong>Clarify the scope, risks, and next move</span><span><strong className="block text-slate-200">Coordinate</strong>Keep people, systems, data, and vendors aligned</span><span><strong className="block text-slate-200">Deliver</strong>Stay involved through implementation and follow-up</span></div></Reveal>
      <Reveal className="relative flex min-h-[430px] items-center justify-center lg:justify-end"><div className="pmv-hero-logo-shell"><div className="pmv-story-orbit pmv-story-orbit-animated" aria-hidden="true"/><div className="pmv-story-orbit pmv-story-orbit-animated-secondary" aria-hidden="true"/><BrandMark3D size={285} decorative className="pmv-hero-brand relative z-20"/><div className="pmv-story-note pmv-story-note-a"><span>Define</span><strong>Scope the outcome, dependencies, and risks</strong></div><div className="pmv-story-note pmv-story-note-b"><span>Coordinate</span><strong>Connect vendors, systems, data, and stakeholders</strong></div><div className="pmv-story-note pmv-story-note-c"><span>Deliver</span><strong>Keep ownership through implementation and closeout</strong></div></div></Reveal>
    </div><Marquee items={['POS & payment transitions','Operational consulting','Data & vendor coordination','Project implementation','Property & field support','Mobile professional services']}/></section>

    <section className="container-pmv py-14 sm:py-18"><Reveal className="grid gap-8 lg:grid-cols-[.7fr_1.3fr] lg:items-end"><div><p className="eyebrow">Where Pinnacle fits</p><h2 className="mt-3 font-display text-3xl font-medium text-white sm:text-4xl">When the work crosses teams, vendors, systems, or locations, someone still has to own the whole picture.</h2></div><div><p className="max-w-2xl text-base leading-7 text-slate-300">Pinnacle is built for that gap. Some engagements begin with a strategic question. Others begin with a software migration, merchant-services change, administrative backlog, vendor issue, or field assignment.</p><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-400">We can support one defined project, a transition period, or an ongoing operating relationship — with the scope matched to the work instead of forcing every client into the same package.</p></div></Reveal><div className="mt-9 border-y border-white/10">{pathways.map(item=><Reveal key={item.title}><Link to={item.to} className="group grid gap-4 border-b border-white/10 py-6 last:border-b-0 sm:grid-cols-[54px_48px_minmax(180px,.7fr)_1.3fr_auto] sm:items-center"><span className="font-display text-xs text-gold/70">{item.n}</span><span className="text-gold"><Icon name={item.icon} size={21}/></span><div><h3 className="text-lg font-semibold text-white transition group-hover:text-gold">{item.title}</h3><p className="mt-1 text-xs uppercase tracking-[.1em] text-slate-500">{item.note}</p></div><p className="max-w-2xl text-sm leading-6 text-slate-400">{item.body}</p><span className="text-gold transition-transform group-hover:translate-x-1">→</span></Link></Reveal>)}</div></section>

    <section className="pmv-gold-band border-y border-gold/15"><div className="container-pmv py-14 sm:py-18"><Reveal className="grid gap-10 lg:grid-cols-[.82fr_1.18fr] lg:items-center"><div><p className="eyebrow">A different kind of support</p><h2 className="mt-3 font-display text-3xl font-medium text-white sm:text-5xl">Advice matters. So does what happens after the recommendation.</h2></div><div><p className="text-lg leading-8 text-slate-300">Many business problems are not difficult because nobody knows the answer. They are difficult because the answer has to survive vendor handoffs, data movement, internal approvals, timelines, documents, and the realities of day-to-day operations.</p><p className="mt-4 text-base leading-7 text-slate-400">Pinnacle stays close to execution. We help define the work, organize the moving pieces, surface blockers, coordinate the right parties, document progress, and keep a clear owner on the next step. When licensed or specialized expertise is required, we work alongside the appropriate professional while keeping the broader engagement connected.</p><div className="mt-7 flex flex-wrap gap-x-8 gap-y-3 text-sm"><span className="border-l border-gold/40 pl-3 text-slate-300">One accountable relationship</span><span className="border-l border-gold/40 pl-3 text-slate-300">Implementation-minded consulting</span><span className="border-l border-gold/40 pl-3 text-slate-300">Flexible project scopes</span><span className="border-l border-gold/40 pl-3 text-slate-300">Secure client workspace</span></div></div></Reveal></div></section>

    <section className="container-pmv py-14 sm:py-18"><Reveal className="grid gap-10 lg:grid-cols-[.8fr_1.2fr]"><div><p className="eyebrow">How we work</p><h2 className="mt-3 font-display text-3xl font-medium text-white sm:text-4xl">A practical path from “we need to change this” to “it is handled.”</h2><Link to="/about" className="mt-5 inline-block text-sm font-semibold text-gold">How Pinnacle works →</Link></div><div className="pmv-process-line">{[['01','Define the outcome','Understand what is changing, why it matters, what cannot break, and what a successful result looks like.'],['02','Map the work','Identify the people, systems, data, vendors, decisions, deadlines, and dependencies involved.'],['03','Coordinate execution','Keep communication, handoffs, documentation, implementation steps, and blockers visible.'],['04','Close the loop','Verify completion, document the result, and make the next operating step clear.']].map(([n,t,b])=><div key={n} className="pmv-process-step"><span>{n}</span><div><h3>{t}</h3><p>{b}</p></div></div>)}</div></Reveal></section>

    <section className="pmv-trust-strip border-y border-gold/15"><div className="container-pmv grid gap-8 py-9 sm:grid-cols-2 lg:grid-cols-4">{[['South Florida','Local field and mobile coverage'],['Remote-ready','Consulting and transition support beyond South Florida'],['Secure','Centralized client documents and communication'],['Flexible','Project, transition, defined task, or ongoing support']].map(([a,b])=><div key={a}><strong className="font-display text-2xl text-white">{a}</strong><p className="mt-1 text-sm leading-6 text-slate-400">{b}</p></div>)}</div></section>

    <CtaBand title="What change, migration, or operational problem needs an owner?" body="Start with the situation. We can help determine the scope, organize the moving pieces, and stay involved through implementation." primary={{to:CLIENT_SIGNUP,label:'Start a Project'}} secondary={{to:'/contact',label:'Talk With Pinnacle'}}/>
  </main><Footer/></div>
}