export interface ManagedAgreementSection {
  id: string
  title: string
  body: string
}

export const DEFAULT_PROVIDER_AGREEMENT_SECTIONS: ManagedAgreementSection[] = [
  {
    "id": "agreement",
    "title": "The Agreement and Who It Covers",
    "body": "This Independent Provider Network Agreement is between Pinnacle Management Ventures, referred to as Pinnacle, we, us, or our, and the individual or business accepting it, referred to as the Provider, you, or your.\n\nThis is the master agreement for your participation in the Pinnacle Professional Network. It becomes effective when you accept it electronically and continues until terminated. Your provider application, each written assignment or work order, applicable service standards, and any signed addendum are part of the agreement for the work they cover. A specific work order controls if it conflicts with this master agreement about that assignment's scope, location, timing, rate, expenses, or deliverables.\n\nIf you accept for a company, practice, or other legal entity, you represent that you have authority to bind that entity. The entity and the person performing the work are both responsible for obligations that apply to them."
  },
  {
    "id": "network",
    "title": "Professional Network, Not Guaranteed Work",
    "body": "Approval means Pinnacle may consider you for work that fits your services, credentials, service area, availability, capacity, and performance history. Approval does not guarantee assignments, minimum earnings, recurring work, territory exclusivity, client access, or continued network status.\n\nYou may update your availability and may accept or decline an opportunity before it becomes a work order. Declining an opportunity does not breach this agreement. Once you accept a work order, you are responsible for the commitment unless Pinnacle releases you in writing."
  },
  {
    "id": "services",
    "title": "Services the Network May Coordinate",
    "body": "Pinnacle coordinates a broad professional network. You may accept only work that fits your approved profile, actual qualifications, lawful authority, and current credentials. Potential assignments include:\n\n- Property and field services: property-condition and occupancy checks, photographs and video, cleaning and deep cleaning, janitorial work, turns, inspections within the provider's lawful scope, REO and vacant-property support, eviction and move-out support, preservation, lock or lockbox services, key and access coordination, minor maintenance or repair when qualified, vendor access, courier work, and documented site visits.\n- Documents, signing, and mobile support: client-directed document preparation or data entry, printing, copying, scanning, pickup, delivery, filing, courthouse or government runs, process service where lawfully authorized, mobile notary work, Remote Online Notarization, signing-agent appointments, witnesses, and document execution support.\n- Business, administrative, and operational support: administrative capacity, project or transaction coordination, bookkeeping support, vendor coordination, consulting, implementation, research, technology, POS and payment-system work, training, data migration, and funding-readiness or referral support.\n- Licensed or specialized professional work: legal, accounting, tax, inspection, contracting, brokerage, engineering, financial, or other regulated services only when the work order identifies the qualified provider and the provider may lawfully perform the work.\n\nA category in your profile is not permission to perform regulated work. A work order does not expand a license, commission, certification, permit, or legal scope."
  },
  {
    "id": "work-orders",
    "title": "Opportunities, Work Orders, and Changes",
    "body": "An opportunity is a request for your review, not a promise of work. It should identify the available scope, location or remote status, expected timing, compensation, material access conditions, and required deliverables. Ask questions before accepting if the information is not sufficient to price, schedule, or lawfully perform the work.\n\nAn opportunity becomes a Work Order when you accept it and Pinnacle confirms the assignment through the platform, email, text, or another written channel. You must promptly report a conflict, unsafe condition, access problem, material change, or fact that makes the original scope impractical. Do not perform or charge for additional work without written approval. An approved change may update the deadline, rate, expenses, or deliverables.\n\nPinnacle may cancel or reassign unaccepted opportunities. If Pinnacle cancels an accepted Work Order without Provider fault, the Work Order will govern any trip, cancellation, or completed-work fee. If it is silent, Pinnacle will pay for conforming work completed and preapproved noncancelable expenses through the cancellation time."
  },
  {
    "id": "performance",
    "title": "Performance and Communication Standards",
    "body": "You agree to perform accepted work professionally, safely, lawfully, and by the deadline in the Work Order. You control the lawful means and methods used to produce the required result, subject to site rules, client-authorized scope, security requirements, objective specifications, and professional standards.\n\n- Review the full Work Order before accepting and confirm that you have the time, tools, credentials, transportation, and capacity to complete it.\n- Use accurate status updates. Do not mark work started, on site, complete, or delivered when it is not.\n- Follow stated photo, video, report, document, checklist, file-format, and completion-proof requirements.\n- Protect the client experience. Be respectful, appropriately dressed for the assignment, and clear about your role as an independent Pinnacle provider.\n- Do not make promises, admissions, price changes, legal conclusions, or commitments on behalf of Pinnacle or a client.\n- Report a likely delay as soon as you know about it. Silence after accepting a time-sensitive assignment is a performance failure.\n\nIf a deliverable is incomplete or does not reasonably match the Work Order, Pinnacle may request a prompt cure when practical. Pinnacle may reassign urgent, unsafe, abandoned, materially late, or uncured work. Payment may be reduced only for rejected, incomplete, duplicative, unauthorized, or nonconforming portions and will not be withheld arbitrarily."
  },
  {
    "id": "site",
    "title": "Property Access, Safety, and Sensitive Assignments",
    "body": "Enter a property, open a lockbox, change access, post a notice, photograph an interior, contact an occupant, handle belongings, or remove material only when the Work Order provides documented authority and clear instructions. Never force entry, misrepresent your identity or authority, threaten an occupant, provide legal advice, or participate in a physical eviction.\n\nEviction, foreclosure, REO, preservation, and vacant-property assignments may be sensitive. Your role is limited to the lawful field, documentation, cleaning, delivery, coordination, or other support stated in the Work Order. Service of process, legal document selection, contracting, mold or hazardous-material work, and other regulated activity may be performed only by a person authorized to do it.\n\nStop and move to a safe location if you encounter a threatening person, unsafe structure, active criminal activity, uncontrolled animal, suspected hazardous material, exposed utility, or another condition outside your training or scope. Contact emergency services when reasonably necessary, then notify Pinnacle. Do not create or conceal damage."
  },
  {
    "id": "credentials",
    "title": "Licenses, Insurance, Verification, and Equipment",
    "body": "You must maintain every license, commission, registration, permit, bond, certification, background clearance, and insurance policy required by law or the Work Order. You must promptly tell Pinnacle about an expiration, suspension, restriction, claim, investigation, lapse, or other change that may affect your eligibility.\n\nYou are responsible for your ordinary business expenses, transportation, devices, tools, supplies, protective equipment, software, connectivity, and other resources unless a Work Order states otherwise. Do not accept an assignment that requires equipment, training, insurance, or credentials you do not have.\n\nPinnacle may verify identity, business registration, tax information, insurance, licenses, references, work history, and submitted documents. When a background or consumer report requires a separate disclosure or authorization, Pinnacle will request it separately. Approval or verification by Pinnacle does not transfer the Provider's professional responsibility to Pinnacle."
  },
  {
    "id": "notary",
    "title": "Notaries, RON, and Other Independent Professional Duties",
    "body": "A notary, Remote Online Notary, signing agent, attorney, accountant, inspector, contractor, or other regulated professional must exercise the independent judgment and duties required by applicable law and professional standards. Nothing in a Work Order requires a provider to perform an improper act, ignore a conflict, alter a certificate, select a legal instrument, backdate a record, conceal a fee, or act outside an authorized scope.\n\nA notary may refuse or stop a notarial act when identity, willingness, awareness, document readiness, technology, location, journal, recording, witness, or other legal requirements are not satisfied. The provider must document the reason through the appropriate secure channel without disclosing more personal information than necessary."
  },
  {
    "id": "independent",
    "title": "Independent Business Relationship",
    "body": "The parties intend an independent business relationship. You are not a Pinnacle employee, partner, joint venturer, franchisee, or general agent. The actual facts and applicable law control classification, not this heading alone.\n\n- You decide whether to accept each opportunity and may provide services to other clients or companies.\n- You control your business organization and the lawful means and methods of performing accepted work, while remaining responsible for the promised result.\n- You bear your ordinary business expenses and may realize a profit or loss from the way you operate.\n- You receive no employee wages, overtime, paid leave, retirement, unemployment, workers' compensation, health insurance, or other employee benefit from Pinnacle unless applicable law requires otherwise.\n- You have no authority to hire, bind, contract for, incur debt for, or make representations on behalf of Pinnacle or a client.\n\nYou may not transfer a Work Order or give another person client information, credentials, property access, or performance responsibility without Pinnacle's advance written approval. Approved personnel remain under your direction and responsibility, must be lawfully engaged by you, and must satisfy the same applicable security, credential, confidentiality, and service requirements."
  },
  {
    "id": "payment",
    "title": "Compensation, Expenses, Invoices, and Taxes",
    "body": "The Work Order states the compensation for an assignment and any conditions for a rush, trip, cancellation, milestone, or completion payment. Compensation includes your ordinary overhead unless the Work Order says otherwise. Travel, tolls, parking, filing fees, materials, third-party charges, and other expenses require advance written approval to be reimbursable.\n\nSubmit complete deliverables, required completion evidence, and any invoice or payment information requested. Unless a Work Order provides a different schedule, Pinnacle will pay undisputed, verified amounts within 30 calendar days after receiving the completed work, a complete invoice when required, and all tax and payment records needed to issue payment. Pinnacle will give a reasonable description of a disputed or rejected amount and an opportunity to provide missing information or cure when practical.\n\nYou are responsible for federal, state, and local taxes, registrations, business filings, insurance, payroll, and reporting obligations arising from your business and personnel. You must provide a current Form W-9 or other required tax documentation. Pinnacle may report compensation, apply backup withholding, or make other deductions when required by law."
  },
  {
    "id": "confidentiality",
    "title": "Confidential Information, Client Data, and Security",
    "body": "Client identities, contact details, property and occupancy information, access codes, alarm information, documents, signatures, financial information, credentials, photographs, pricing, Work Orders, internal methods, and nonpublic business information are confidential. Use them only to perform the accepted work and disclose them only to an approved person who needs them for that work.\n\n- Use Pinnacle's secure platform or approved channel for sensitive records. Do not place confidential material in personal cloud folders, public links, social media, or unapproved AI or file-sharing services.\n- Keep account credentials, keys, gate codes, lockbox combinations, and one-time links private. Do not reuse or retain access after the assignment.\n- Collect only the information and images the Work Order requires. Avoid unrelated people, documents, screens, license plates, or personal belongings when they are not needed.\n- Notify Pinnacle immediately, and no later than 24 hours after discovery, of suspected loss, unauthorized access, mistaken disclosure, device compromise, or security incident affecting Pinnacle or client information.\n- Return or securely delete confidential material when instructed, subject to a legal or professional record-retention duty you disclose to Pinnacle.\n\nThese duties continue after an assignment and after this agreement ends."
  },
  {
    "id": "client",
    "title": "Client Communication and No Side Arrangements",
    "body": "Communicate with a client, occupant, signer, property contact, or other third party only as the Work Order permits. Route scope, pricing, complaints, changes, and payment questions through Pinnacle unless the Work Order authorizes another process. Do not collect money from a client or occupant, advertise unrelated services during an assignment, or move Pinnacle work to a direct side arrangement.\n\nYou remain free to advertise generally and serve your existing or independently developed relationships. During an active Work Order and for six months after its completion, you will not use Pinnacle's confidential information or introduction to knowingly route the same client need, or materially related follow-on work arising from that assignment, around Pinnacle to avoid the agreed coordination or fee structure. This restriction does not apply to a preexisting relationship disclosed before accepting the Work Order, general advertising not directed using Pinnacle information, or work Pinnacle approves in writing."
  },
  {
    "id": "work-product",
    "title": "Work Product, Records, and Publicity",
    "body": "Reports, photographs, video, forms, data, notes, diagrams, recordings, files, and other assignment-specific material created for a Work Order are Work Product. To the extent permitted by law, Work Product is specially commissioned for Pinnacle or its client and will be treated as work made for hire. To the extent it is not work made for hire, you assign to Pinnacle all right, title, and interest needed for Pinnacle and the client to own, use, reproduce, modify, distribute, verify, and retain it for the assignment and related business, legal, insurance, compliance, and recordkeeping purposes.\n\nYou retain ownership of tools, methods, templates, know-how, and material developed independently of the assignment. If your background material is embedded in a deliverable, you grant Pinnacle and the client a perpetual, worldwide, paid-up license to use it as part of that deliverable.\n\nDo not publish, sell, reuse, train a model on, or use client or assignment material for a portfolio, marketing, social media, or another purpose without prior written approval. Maintain accurate assignment and payment records for the period required by law and any longer period stated in the Work Order."
  },
  {
    "id": "representations",
    "title": "Provider Promises",
    "body": "You represent that application and payment information is accurate and current; you may lawfully operate the business and perform accepted services; your work will be original or properly licensed; you are not bound by another obligation that prevents performance; and you will comply with applicable law, professional duties, the Work Order, and this agreement.\n\nYou will not engage in discrimination, harassment, retaliation, bribery, kickbacks, fraud, theft, falsification, trespass, unauthorized surveillance, substance impairment while performing work, or other conduct that threatens a person, property, record, or client relationship."
  },
  {
    "id": "risk",
    "title": "Responsibility, Indemnification, and Liability",
    "body": "Each party is responsible for its own acts and omissions. You will defend and indemnify Pinnacle, its clients, and their personnel from third-party claims, damages, penalties, and reasonable legal costs to the extent caused by your breach of this agreement, negligence, willful misconduct, unlawful act, infringement, data-security failure, or the acts of personnel you use. Pinnacle will defend and indemnify you from third-party claims to the extent caused by Pinnacle's negligence, willful misconduct, or material breach.\n\nTo the fullest extent permitted by law, neither party is liable to the other for indirect, special, exemplary, punitive, or consequential damages, or lost profits unrelated to payment for completed Work Orders. Except for payment obligations and liability that cannot lawfully be limited, each party's aggregate liability under this agreement will not exceed the greater of amounts paid or payable under Work Orders during the 12 months before the event or available insurance proceeds covering the claim.\n\nThe liability limit does not apply to fraud, willful misconduct, bodily injury, physical property damage, confidentiality or data-security obligations, intellectual-property infringement, indemnification obligations, or a provider's unauthorized collection of client funds."
  },
  {
    "id": "term",
    "title": "Suspension and Termination",
    "body": "Either party may end this agreement or pause future opportunities by written notice. Ending the agreement does not cancel an accepted Work Order unless the parties agree or Pinnacle reassigns it. Pinnacle may immediately suspend opportunities, access, or an assignment for a safety or security risk, suspected fraud, expired credential, client request, material performance failure, unlawful conduct, breach, or conduct that may harm a client or the network.\n\nOn termination, return access items and confidential material, submit completed Work Product, and cooperate in a reasonable handoff for accepted work. Accrued payment obligations and provisions concerning confidentiality, data security, taxes, records, Work Product, client protection, liability, disputes, and other terms that by nature should continue will survive."
  },
  {
    "id": "electronic",
    "title": "Electronic Records and Communications",
    "body": "You agree that the relationship may be administered electronically. Click acceptance, a typed signature, platform activity, email or text acceptance, timestamps, IP and device information, audit records, and other electronic evidence may document your intent and assignment activity. You may save or print this agreement and should keep copies of accepted Work Orders and payment records.\n\nService messages about applications, opportunities, Work Orders, safety, access, security, credentials, performance, and payment are transactional communications. Marketing consent is separate and is not required to participate in the network. The Electronic Communications Disclosure provides additional details."
  },
  {
    "id": "disputes",
    "title": "Disputes, Arbitration, and Class Waiver",
    "body": "Please read this section carefully because it affects legal rights. Before filing a formal claim, the complaining party must send written notice describing the dispute and requested resolution and allow at least 30 days for good-faith informal resolution. Notice to Pinnacle may be emailed to support@pinnaclemanagementventures.com with the subject \"Provider Legal Dispute Notice.\"\n\nIf the dispute is not resolved, either party may elect individual binding arbitration administered by the American Arbitration Association under the rules applicable to the dispute. The Federal Arbitration Act governs this arbitration provision. Hearings may be remote when allowed. Unless the parties agree otherwise, the arbitration seat will be Broward County, Florida. Either party may bring an eligible individual claim in small claims court or seek temporary injunctive relief to protect safety, property access, confidential information, intellectual property, or account security.\n\nClaims must be brought only on an individual basis and not as a class, collective, coordinated, consolidated, or representative action to the fullest extent permitted by law. You may opt out of arbitration by emailing support@pinnaclemanagementventures.com within 30 days after first accepting this agreement. Use the subject \"Provider Arbitration Opt Out\" and include your name, account email, and a clear statement that you are opting out. Opting out does not affect network eligibility."
  },
  {
    "id": "law",
    "title": "Governing Law and General Terms",
    "body": "Florida law and applicable federal law govern this agreement, without regard to conflict-of-law principles. If a dispute is not subject to arbitration, the parties consent to exclusive venue in state or federal court in Broward County, Florida, unless applicable law requires another venue.\n\nYou may not assign this agreement or a Work Order without Pinnacle's written consent. Pinnacle may assign the agreement in connection with a merger, financing, reorganization, sale, or transfer of the relevant business. Neither party is liable for delay caused by events beyond reasonable control, except payment for work already accepted and completed.\n\nIf a provision is unenforceable, it will be limited to the minimum extent necessary and the remainder will continue. A waiver must be in writing and applies only to the stated instance. This agreement, accepted Work Orders, applicable addenda, and incorporated disclosures are the entire agreement about the provider relationship and replace prior inconsistent discussions about that subject."
  },
  {
    "id": "changes",
    "title": "Future Versions",
    "body": "Pinnacle may revise this agreement as services, the platform, or law changes. A revised version will not retroactively change an accepted Work Order. If a revision materially changes provider rights or obligations, Pinnacle will provide reasonable notice and require affirmative acceptance before the revised version governs new assignments."
  }
]

