import { Hono } from 'hono'
import type { AppEnv } from '../types'
import { requireUser } from '../mid'
import { uuid } from '../crypto'
import { sha256Hex } from '../documentSealing'
import { snapshotBrandingProfile, snapshotCommunicationTemplate } from '../communicationBranding'

export const communicationBrandingAdminRoutes = new Hono<AppEnv>()
export const communicationBrandingPublicRoutes = new Hono<AppEnv>()

async function requireStaff(c:any,next:any){return requireUser(c,async()=>{const u=c.get('user');if(u.role!=='staff'&&u.role!=='admin')return c.json({error:'forbidden'},403);return next()})}
communicationBrandingAdminRoutes.use('/branding/*',requireStaff)

const profileFields=['name','description','organization_key','status','logo_file_id','primary_color','secondary_color','accent_color','background_color','text_color','heading_font_family','body_font_family','font_assets_json','email_header_html','email_footer_html','legal_disclaimer','social_links_json','pdf_header_text','pdf_footer_text','pdf_page_size','pdf_orientation','pdf_margin_top','pdf_margin_right','pdf_margin_bottom','pdf_margin_left','signature_block_style_json','audit_table_style_json','custom_css','email_settings_json','pdf_settings_json'] as const
const templateFields=['name','template_key','template_type','status','description','branding_profile_id','subject_template','preheader_template','body_html','body_text','custom_css','editor_json','variable_schema_json','conditional_rules_json','attach_audit_certificate'] as const

function pick(body:any,fields:readonly string[]){const out:Record<string,unknown>={};for(const k of fields)if(Object.prototype.hasOwnProperty.call(body,k))out[k]=body[k];return out}
function validHex(v:unknown){return typeof v==='string'&&/^#[0-9a-fA-F]{6}$/.test(v)}
function sanitizeProfile(body:any){const out=pick(body,profileFields);for(const k of ['primary_color','secondary_color','accent_color','background_color','text_color'])if(k in out&&out[k]&&!validHex(out[k]))delete out[k];for(const k of ['pdf_margin_top','pdf_margin_right','pdf_margin_bottom','pdf_margin_left'])if(k in out)out[k]=Math.max(0,Math.min(180,Number(out[k])||0));return out}
function sanitizeTemplate(body:any){const out=pick(body,templateFields);if('attach_audit_certificate'in out)out.attach_audit_certificate=out.attach_audit_certificate?1:0;return out}
async function changeEvent(c:any,type:string,id:string,action:string,versionId?:string|null,metadata:any={}){await c.env.DB.prepare('INSERT INTO template_change_events(id,entity_type,entity_id,action,version_id,actor_user_id,metadata_json) VALUES(?,?,?,?,?,?,?)').bind(uuid(),type,id,action,versionId||null,c.get('user').id,JSON.stringify(metadata)).run().catch(()=>undefined)}

communicationBrandingAdminRoutes.get('/branding/profiles',async c=>{const rows=await c.env.DB.prepare("SELECT * FROM branding_profiles WHERE status!='archived' ORDER BY is_default DESC,name").all();return c.json({profiles:rows.results})})
communicationBrandingAdminRoutes.post('/branding/profiles',async c=>{const b=sanitizeProfile(await c.req.json<any>().catch(()=>({})));if(!String(b.name||'').trim())return c.json({error:'profile name is required'},400);const id=uuid();const columns=Object.keys(b),values=Object.values(b);await c.env.DB.prepare(`INSERT INTO branding_profiles(id,${columns.join(',')},created_by_user_id,updated_by_user_id) VALUES(?,${columns.map(()=>'?').join(',')},?,?)`).bind(id,...values,c.get('user').id,c.get('user').id).run();const version=await snapshotBrandingProfile(c.env,id,c.get('user').id,'Initial version');await changeEvent(c,'branding_profile',id,'created',version?.id);const profile=await c.env.DB.prepare('SELECT * FROM branding_profiles WHERE id=?').bind(id).first();return c.json({profile},201)})
communicationBrandingAdminRoutes.patch('/branding/profiles/:id',async c=>{const id=c.req.param('id'),b=sanitizeProfile(await c.req.json<any>().catch(()=>({}))),columns=Object.keys(b);if(!columns.length)return c.json({error:'no changes supplied'},400);await c.env.DB.prepare(`UPDATE branding_profiles SET ${columns.map(k=>`${k}=?`).join(',')},updated_by_user_id=?,updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(...Object.values(b),c.get('user').id,id).run();const version=await snapshotBrandingProfile(c.env,id,c.get('user').id,'Brand Studio update');await changeEvent(c,'branding_profile',id,'versioned',version?.id);const profile=await c.env.DB.prepare('SELECT * FROM branding_profiles WHERE id=?').bind(id).first();return c.json({profile})})
communicationBrandingAdminRoutes.post('/branding/profiles/:id/default',async c=>{const id=c.req.param('id');await c.env.DB.batch([c.env.DB.prepare('UPDATE branding_profiles SET is_default=0 WHERE is_default=1'),c.env.DB.prepare("UPDATE branding_profiles SET is_default=1,status='active',updated_by_user_id=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(c.get('user').id,id)]);const version=await snapshotBrandingProfile(c.env,id,c.get('user').id,'Set as default');await changeEvent(c,'branding_profile',id,'activated',version?.id);return c.json({ok:true})})
communicationBrandingAdminRoutes.get('/branding/profiles/:id/versions',async c=>{const rows=await c.env.DB.prepare('SELECT * FROM branding_profile_versions WHERE branding_profile_id=? ORDER BY version_number DESC').bind(c.req.param('id')).all();return c.json({versions:rows.results})})

communicationBrandingAdminRoutes.get('/branding/templates',async c=>{const rows=await c.env.DB.prepare("SELECT * FROM communication_templates WHERE status!='archived' ORDER BY status='active' DESC,updated_at DESC,name").all();return c.json({templates:rows.results})})
communicationBrandingAdminRoutes.post('/branding/templates',async c=>{const b=sanitizeTemplate(await c.req.json<any>().catch(()=>({})));if(!String(b.name||'').trim()||!String(b.template_key||'').trim()||!String(b.subject_template||'').trim())return c.json({error:'name, template key, and subject are required'},400);if(!String(b.body_html||'').trim())b.body_html='<p></p>';const id=uuid(),columns=Object.keys(b),values=Object.values(b);await c.env.DB.prepare(`INSERT INTO communication_templates(id,${columns.join(',')},created_by_user_id,updated_by_user_id) VALUES(?,${columns.map(()=>'?').join(',')},?,?)`).bind(id,...values,c.get('user').id,c.get('user').id).run();const version=await snapshotCommunicationTemplate(c.env,id,c.get('user').id,'Initial version');await changeEvent(c,'communication_template',id,'created',version?.id);const template=await c.env.DB.prepare('SELECT * FROM communication_templates WHERE id=?').bind(id).first();return c.json({template},201)})
communicationBrandingAdminRoutes.patch('/branding/templates/:id',async c=>{const id=c.req.param('id'),b=sanitizeTemplate(await c.req.json<any>().catch(()=>({}))),columns=Object.keys(b);if(!columns.length)return c.json({error:'no changes supplied'},400);await c.env.DB.prepare(`UPDATE communication_templates SET ${columns.map(k=>`${k}=?`).join(',')},updated_by_user_id=?,updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(...Object.values(b),c.get('user').id,id).run();const version=await snapshotCommunicationTemplate(c.env,id,c.get('user').id,'Brand Studio update');await changeEvent(c,'communication_template',id,'versioned',version?.id);const template=await c.env.DB.prepare('SELECT * FROM communication_templates WHERE id=?').bind(id).first();return c.json({template})})
communicationBrandingAdminRoutes.post('/branding/templates/:id/activate',async c=>{const id=c.req.param('id'),t=await c.env.DB.prepare('SELECT template_type FROM communication_templates WHERE id=?').bind(id).first<any>();if(!t)return c.json({error:'template not found'},404);await c.env.DB.prepare("UPDATE communication_templates SET status='active',updated_by_user_id=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(c.get('user').id,id).run();const existing=await c.env.DB.prepare("SELECT id FROM template_assignments WHERE event_type=? AND assignment_scope='global' ORDER BY priority LIMIT 1").bind(t.template_type).first<any>();if(existing)await c.env.DB.prepare('UPDATE template_assignments SET communication_template_id=?,enabled=1,updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(id,existing.id).run();else if(t.template_type!=='custom')await c.env.DB.prepare("INSERT INTO template_assignments(id,assignment_scope,scope_key,event_type,communication_template_id,priority,enabled,created_by_user_id) VALUES(?,'global',NULL,?,?,100,1,?)").bind(uuid(),t.template_type,id,c.get('user').id).run();const version=await snapshotCommunicationTemplate(c.env,id,c.get('user').id,'Activated');await changeEvent(c,'communication_template',id,'activated',version?.id);return c.json({ok:true})})
communicationBrandingAdminRoutes.get('/branding/templates/:id/versions',async c=>{const rows=await c.env.DB.prepare('SELECT * FROM communication_template_versions WHERE communication_template_id=? ORDER BY version_number DESC').bind(c.req.param('id')).all();return c.json({versions:rows.results})})

communicationBrandingAdminRoutes.get('/branding/fonts',async c=>{const rows=await c.env.DB.prepare('SELECT id,display_name,family_name,font_weight,font_style,mime_type,usage_scope,active,created_at FROM custom_font_assets WHERE active=1 ORDER BY family_name,font_weight').all();return c.json({fonts:rows.results})})
communicationBrandingAdminRoutes.post('/branding/fonts',async c=>{if(!c.env.UPLOADS)return c.json({error:'Font storage is not configured.'},503);const name=c.req.header('X-File-Name')||'font.ttf',mime=c.req.header('content-type')||'application/octet-stream',ext=name.toLowerCase().split('.').pop()||'';if(!['ttf','otf','woff','woff2'].includes(ext))return c.json({error:'TTF, OTF, WOFF, or WOFF2 font files are required.'},400);const bytes=await c.req.arrayBuffer();if(!bytes.byteLength||bytes.byteLength>5*1024*1024)return c.json({error:'Font file must be between 1 byte and 5 MB.'},400);const q=c.req.query(),displayName=String(q.display_name||name).trim().slice(0,120),family=String(q.family_name||displayName).trim().slice(0,120),weight=Math.max(100,Math.min(900,Number(q.font_weight||400))),style=q.font_style==='italic'?'italic':'normal',scope=['email','pdf','both'].includes(String(q.usage_scope))?String(q.usage_scope):'both';const fileId=uuid(),fontId=uuid(),safe=name.replace(/[^a-zA-Z0-9._-]/g,'_'),key=`branding/fonts/${fontId}/${safe}`,hash=await sha256Hex(bytes);await c.env.UPLOADS.put(key,bytes,{httpMetadata:{contentType:mime},customMetadata:{sha256:hash,kind:'brand_font'}});await c.env.DB.batch([c.env.DB.prepare('INSERT INTO document_files(id,kind,original_name,mime_type,storage_key,size_bytes,sha256,created_by_user_id) VALUES(?,?,?,?,?,?,?,?)').bind(fileId,'brand_font',name,mime,key,bytes.byteLength,hash,c.get('user').id),c.env.DB.prepare('INSERT INTO custom_font_assets(id,display_name,family_name,font_weight,font_style,file_id,mime_type,usage_scope,created_by_user_id) VALUES(?,?,?,?,?,?,?,?,?)').bind(fontId,displayName,family,weight,style,fileId,mime,scope,c.get('user').id)]);return c.json({font:{id:fontId,display_name:displayName,family_name:family,font_weight:weight,font_style:style,mime_type:mime,usage_scope:scope}},201)})
communicationBrandingAdminRoutes.delete('/branding/fonts/:id',async c=>{await c.env.DB.prepare('UPDATE custom_font_assets SET active=0 WHERE id=?').bind(c.req.param('id')).run();return c.json({ok:true})})

communicationBrandingAdminRoutes.patch('/branding/envelopes/:id',async c=>{const b=await c.req.json<any>().catch(()=>({}));const id=c.req.param('id');await c.env.DB.prepare('UPDATE envelopes SET branding_profile_id=?,invitation_template_id=?,completion_template_id=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(b.branding_profile_id||null,b.invitation_template_id||null,b.completion_template_id||null,id).run();return c.json({ok:true})})

communicationBrandingPublicRoutes.get('/brand-fonts/:id',async c=>{if(!c.env.UPLOADS)return c.json({error:'not found'},404);const row=await c.env.DB.prepare('SELECT f.storage_key,COALESCE(a.mime_type,f.mime_type) mime_type FROM custom_font_assets a JOIN document_files f ON f.id=a.file_id WHERE a.id=? AND a.active=1').bind(c.req.param('id')).first<any>();if(!row)return c.json({error:'not found'},404);const obj=await c.env.UPLOADS.get(row.storage_key);if(!obj)return c.json({error:'not found'},404);return new Response(obj.body,{headers:{'Content-Type':row.mime_type||'font/ttf','Cache-Control':'public, max-age=31536000, immutable','Access-Control-Allow-Origin':'*','X-Content-Type-Options':'nosniff'}})})
