import { Hono } from 'hono'
import type { AppEnv } from '../types'
import { uuid } from '../crypto'
import { sealEnvelope, sha256Hex } from '../documentSealing'

export const documentSignerSecurityRoutes = new Hono<AppEnv>()
const now=()=>new Date().toISOString()
async function signerSession(c:any){const raw=c.req.header('x-signing-session')||'';const v=await c.env.SESSIONS.get(`sign:${raw}`);return v?JSON.parse(v):null}
async function event(env:any,envelopeId:string,type:string,recipientId:string|null,metadata:any={}){const prev=await env.DB.prepare('SELECT event_hash FROM envelope_events WHERE envelope_id=? ORDER BY occurred_at_utc DESC,id DESC LIMIT 1').bind(envelopeId).first() as any;const id=uuid(),stamp=now(),requestId=uuid(),prevHash=prev?.event_hash||'GENESIS',canonical=JSON.stringify({id,envelopeId,type,recipientId,stamp,requestId,prevHash,metadata});const hash=await sha256Hex(canonical);await env.DB.prepare(`INSERT INTO envelope_events(id,envelope_id,recipient_id,actor_type,actor_id,event_type,occurred_at_utc,request_id,metadata_json,prev_event_hash,event_hash) VALUES (?,?,?,'signer',?,?,?,?,?,?,?,?)`).bind(id,envelopeId,recipientId,recipientId,type,stamp,requestId,JSON.stringify(metadata),prevHash,hash).run()}

documentSignerSecurityRoutes.post('/sign/:token/complete',async c=>{
  const ses=await signerSession(c);if(!ses)return c.json({error:'authentication required'},401)
  const recipient=await c.env.DB.prepare('SELECT * FROM envelope_recipients WHERE id=? AND envelope_id=?').bind(ses.recipient_id,ses.envelope_id).first() as any
  if(!recipient)return c.json({error:'recipient not found'},404);if(recipient.access_revoked_at||recipient.status==='expired')return c.json({error:'access revoked'},410);if(recipient.status==='completed')return c.json({ok:true,already_completed:true})
  const env=await c.env.DB.prepare('SELECT * FROM envelopes WHERE id=?').bind(ses.envelope_id).first() as any;if(!env)return c.json({error:'envelope not found'},404);if(['voided','expired','declined'].includes(env.status))return c.json({error:`envelope ${env.status}`},410);if(env.expires_at&&env.expires_at<now())return c.json({error:'envelope expired'},410)
  const fields=await c.env.DB.prepare('SELECT id,required,completed_at,condition_json FROM document_fields WHERE recipient_id=?').bind(ses.recipient_id).all() as any
  for(const f of fields.results||[]){let active=true;try{const condition=f.condition_json?JSON.parse(f.condition_json):null;if(condition?.field_id){const dep=await c.env.DB.prepare('SELECT value_text FROM document_fields WHERE id=? AND recipient_id=?').bind(String(condition.field_id),ses.recipient_id).first() as any;if(condition.equals!==undefined)active=String(dep?.value_text||'')===String(condition.equals)}}catch{}if(active&&Number(f.required)===1&&!f.completed_at)return c.json({error:'required fields remain'},400)}
  const stamp=now();await c.env.DB.prepare(`UPDATE envelope_recipients SET status='completed',completed_at=?,updated_at=? WHERE id=?`).bind(stamp,stamp,ses.recipient_id).run();await event(c.env,ses.envelope_id,'recipient.completed',ses.recipient_id,{secure_completion_gate:true})
  const remaining=await c.env.DB.prepare(`SELECT COUNT(*) n FROM envelope_recipients WHERE envelope_id=? AND role IN ('signer','approver','witness','notary') AND access_revoked_at IS NULL AND status NOT IN ('completed','declined','expired')`).bind(ses.envelope_id).first() as any
  if(Number(remaining?.n||0)===0){const completedAt=now();await c.env.DB.prepare(`UPDATE envelopes SET status='completed',completed_at=?,updated_at=? WHERE id=?`).bind(completedAt,completedAt,ses.envelope_id).run();await event(c.env,ses.envelope_id,'envelope.completed',null,{secure_completion_gate:true});try{const result=await sealEnvelope(c.env,ses.envelope_id);await event(c.env,ses.envelope_id,'envelope.sealed',null,{algorithm:result.algorithm,key_id:result.keyId,final_pdf_sha256:result.signedPdfHash,audit_pdf_sha256:result.auditPdfHash,manifest_sha256:result.manifestHash});const e=await c.env.DB.prepare('SELECT public_id,title,completed_at FROM envelopes WHERE id=?').bind(ses.envelope_id).first() as any,signers=await c.env.DB.prepare(`SELECT COUNT(*) n FROM envelope_recipients WHERE envelope_id=? AND role='signer' AND access_revoked_at IS NULL`).bind(ses.envelope_id).first() as any;await c.env.DB.prepare(`INSERT OR REPLACE INTO verification_records(id,envelope_id,public_id,verification_status,document_label,issuer_name,completed_date,signer_count,final_pdf_sha256_prefix,sealed_at,updated_at) VALUES (?,?,?,?,?,'Pinnacle Management Ventures',?,?,?,?,?)`).bind(uuid(),ses.envelope_id,e.public_id,'valid',e.title,e.completed_at,Number(signers?.n||0),result.signedPdfHash.slice(0,16),result.sealedAt,now()).run()}catch(err){await event(c.env,ses.envelope_id,'envelope.seal_failed',null,{error:err instanceof Error?err.message:'unknown sealing error'})}}
  return c.json({ok:true})
})

documentSignerSecurityRoutes.post('/sign/:token/decline',async c=>{const h=await sha256Hex(c.req.param('token')),r=await c.env.DB.prepare('SELECT * FROM envelope_recipients WHERE invitation_token_hash=?').bind(h).first() as any;if(!r)return c.json({error:'invalid or revoked link'},404);if(r.access_revoked_at)return c.json({error:'access revoked'},410);const b=await c.req.json<any>().catch(()=>({})),reason=String(b.reason||'').slice(0,500),stamp=now();await c.env.DB.batch([c.env.DB.prepare(`UPDATE envelope_recipients SET status='declined',declined_at=?,updated_at=? WHERE id=?`).bind(stamp,stamp,r.id),c.env.DB.prepare(`UPDATE envelopes SET status='declined',declined_at=?,updated_at=? WHERE id=?`).bind(stamp,stamp,r.envelope_id)]);await event(c.env,r.envelope_id,'recipient.declined',r.id,{reason});return c.json({ok:true})})
