import { LegalPage, P, Strong, UL, type LegalSection } from '../../components/public/LegalPage'
import { usePageMeta } from '../../lib/usePageMeta'

const UPDATED='August 10, 2026'
const sections:LegalSection[]=[
  {id:'commitment',title:'Our Commitment',content:<><P>Pinnacle Management Ventures is committed to providing digital experiences that are usable by people with disabilities. Accessibility is treated as part of product quality, not as a separate add-on.</P><P>We aim to design and maintain our public website and authenticated workspaces using recognized accessibility practices and use the Web Content Accessibility Guidelines, currently WCAG 2.2 Level AA, as a practical design and testing benchmark. This statement is not a representation that every page, third-party component, or document is perfectly conformant at all times.</P></>},
  {id:'practices',title:'Accessibility Practices',content:<><UL><li>Use semantic headings, labels, landmarks, and meaningful link text.</li><li>Support keyboard navigation and visible focus indicators for interactive controls.</li><li>Maintain readable typography, responsive layouts, zoom support, and appropriate color contrast.</li><li>Provide text alternatives for meaningful images where appropriate.</li><li>Avoid relying on color alone to communicate status or required action.</li><li>Use clear validation messages for forms and account workflows.</li><li>Consider reduced-motion preferences when using animation.</li><li>Review new shared components so accessibility improvements apply across the platform.</li></UL></>},
  {id:'documents',title:'Documents and Third-Party Content',content:<><P>Some client documents, uploaded files, maps, embedded tools, or third-party services may be created or controlled outside Pinnacle and can have different accessibility characteristics. When a third-party tool is necessary to an engagement, we try to choose practical solutions and reasonable alternatives when available.</P><P>If a document or feature is difficult for you to access, contact us and identify the item and the format or assistance that would be useful.</P></>},
  {id:'assistance',title:'Alternative Access and Assistance',content:<><P>If you encounter an accessibility barrier, Pinnacle will work in good faith to provide the information or service through a reasonable alternative method when feasible. Depending on the request, that may include a different document format, assisted completion, email, phone support, or another communication method.</P></>},
  {id:'feedback',title:'Report an Accessibility Issue',content:<><P>Send accessibility feedback to <a href="mailto:support@pinnaclemanagementventures.com" className="font-bold text-gold hover:text-gold-300">support@pinnaclemanagementventures.com</a>. Please include the page, feature, or document involved; the device or browser you were using if relevant; the difficulty you encountered; and the best way to contact you.</P><P>Accessibility reports are reviewed as product and service issues so we can address the immediate need and improve the underlying experience where possible.</P></>},
]

export default function Accessibility(){
  usePageMeta('Accessibility','Pinnacle Management Ventures accessibility commitment, digital accessibility practices, alternative access, and feedback process.')
  return <LegalPage eyebrow="Accessibility" title="Accessibility Statement" intro="Pinnacle is committed to clear, usable access to our website, secure workspaces, documents, and professional services. We continuously improve the experience as our platform and services evolve." updated={UPDATED} sections={sections}/>
}
