import { LegalPage, P, Strong, UL, type LegalSection } from '../../components/public/LegalPage'
import { usePageMeta } from '../../lib/usePageMeta'

const UPDATED='August 10, 2026'
const sections:LegalSection[]=[
  {id:'consent',title:'Consent to Electronic Transactions',content:<><P>When you create a Pinnacle account, accept this disclosure, sign electronically, or choose to continue a transaction electronically, you consent to conduct eligible transactions with Pinnacle using electronic records, electronic communications, and electronic signatures.</P><P>Your consent applies to account notices, service communications, disclosures, agreements, applications, acknowledgments, invoices, records, signatures, and other documents that Pinnacle is legally permitted to provide electronically.</P></>},
  {id:'intent',title:'Electronic Signature Intent',content:<><P>An electronic action can be evidence of your intent when the surrounding process identifies the record and asks you to approve, accept, sign, initial, check a box, enter a verification code, or take another action intended to authenticate or signify agreement. Pinnacle may retain associated timestamps, IP information, device/browser information, verification evidence, document hashes, audit events, and other records that help establish the integrity of the transaction.</P><P>Electronic signatures and records are not used to bypass legal requirements. If a transaction requires a different form, witness, notarization, paper record, or other formality, Pinnacle may require that additional process.</P></>},
  {id:'delivery',title:'Electronic Delivery',content:<><P>Electronic records may be delivered through the secure client workspace, email, a secure signing link, an in-app notice, or another electronic method identified during the engagement. You are responsible for keeping your email address and other account contact information current.</P><P>Some communications are considered delivered when made available through the agreed electronic method, subject to applicable law and any transaction-specific terms.</P></>},
  {id:'requirements',title:'Hardware and Software Requirements',content:<><P>To receive and retain electronic records, you should have:</P><UL><li>a current internet-connected computer, tablet, or smartphone;</li><li>a reasonably current web browser with cookies, JavaScript, and modern encryption enabled;</li><li>access to the email account associated with your Pinnacle account;</li><li>software or browser capability to view common formats such as PDF, image, and text documents;</li><li>sufficient storage or printing capability to keep records you need.</li></UL><P>If these requirements materially change in a way that creates a substantial risk that you cannot access required electronic records, Pinnacle will provide updated information or another method when required by law.</P></>},
  {id:'retain',title:'Keeping Copies',content:<><P>You may download, save, or print records made available through Pinnacle when the interface permits. You should retain copies of agreements, signed records, invoices, and other records important to your business or legal obligations. If you need a paper copy of a record that Pinnacle still retains, contact support. Reasonable reproduction or delivery charges may apply if disclosed in advance.</P></>},
  {id:'withdraw',title:'Withdrawing Electronic Consent',content:<><P>You may ask to withdraw consent to electronic records for future transactions by contacting support@pinnaclemanagementventures.com. Withdrawal does not invalidate electronic records or signatures completed before the withdrawal takes effect.</P><P>Because the Pinnacle platform is designed as an electronic service, withdrawing electronic consent may limit or prevent use of certain online features or engagements. We will explain material consequences before processing a withdrawal when applicable.</P></>},
  {id:'marketing',title:'Electronic Consent Is Not Marketing Consent',content:<><P>Consent to electronic records and service communications is not consent to automated promotional calls or texts. Where separate marketing consent is required by law, Pinnacle will request it separately and will not condition service eligibility on agreeing to that marketing consent.</P></>},
  {id:'security',title:'Security and Verification',content:<><P>Pinnacle may use password authentication, one-time links, verification codes, device/session controls, access logs, encryption, document hashes, signing evidence, and other security procedures appropriate to a transaction. You agree not to share verification links, codes, or credentials with an unauthorized person.</P><P>If you believe an electronic record, signature, account, or verification process was used without your permission, contact Pinnacle promptly so access can be reviewed and protected.</P></>},
  {id:'contact',title:'Contact and Paper Records',content:<><P>Questions about electronic records, requests for a paper copy, updates to contact information, or withdrawal of electronic consent can be directed to <a href="mailto:support@pinnaclemanagementventures.com" className="font-bold text-gold hover:text-gold-300">support@pinnaclemanagementventures.com</a>.</P></>},
]

export default function ElectronicCommunications(){
  usePageMeta('Electronic Communications Disclosure','Pinnacle Management Ventures disclosure for electronic records, electronic signatures, delivery, hardware requirements, and withdrawal of electronic consent.')
  return <LegalPage eyebrow="Electronic Records" title="Electronic Communications and Signature Disclosure" intro="This disclosure explains how Pinnacle conducts eligible transactions electronically, what an electronic signature means in our workflows, what you need to access records, and how to request paper records or withdraw future electronic consent." updated={UPDATED} sections={sections}/>
}
