import { Link } from 'react-router-dom'
import { Header } from '../../components/public/Header'
import { Footer } from '../../components/public/Footer'
import { btnPrimary, PageIntro } from '../../components/public/ui'
import { Reveal } from '../../components/public/motion'
import { BrandMark3D } from '../../components/ui'
import { services } from '../../data/services'
import { usePageMeta } from '../../lib/usePageMeta'
import { Icon, type IconName } from '../../components/kit/Icon'

const CLIENT_SIGNUP='/scope-request?source=services-overview'
// Category order matches Home: business + operations first, documents +
// signing second, property + field third. Reflects the nationwide-network
// framing rather than the property-management-first frame the site used
// to lead with.
const hubs:{n:string;icon:IconName;title:string;body:string;to:string;includes:string}[]=[
  {n:'01',icon:'briefcase',title:'Business & Operations',body:'Fractional operations partner, admin capacity, project coordination, POS + payment transitions, systems implementation, funding readiness, and vendor management for owners and teams anywhere in the U.S.',to:'/services/business-operations',includes:'Ops · Admin · Systems · POS &amp; payments · Vendors'},
  {n:'02',icon:'file',title:'Documents, Signing & Mobile',body:'Document preparation, organized packets, filing, delivery, mobile notarization, Remote Online Notarization sessions, courthouse runs, and certified audit trails - available nationwide, on-site or remote.',to:'/services/mobile-documents',includes:'Document prep · Filing · Courier · Mobile notary · RON'},
  {n:'03',icon:'building',title:'Property & Field Services',body:'Property care, cleaning, turnovers, inspections, REO and vacant-property support, eviction coordination, and documented on-site work across our field coverage areas.',to:'/services/property-field',includes:'Cleaning · Inspections · Evictions · REO · Preservation'},
]

export default function ServicesOverview(){
  usePageMeta('Nationwide Professional Services Network - Pinnacle','Business operations, admin capacity, documents and signing (RON included), mobile notary, and property field services from Pinnacle Management Ventures - one dependable network available across the U.S.')
  return <div className="min-h-screen bg-navy-950"><Header/><main>
    <section className="pmv-hero-story relative overflow-hidden border-b border-white/10"><div className="pmv-hero-gold" aria-hidden="true"/><div className="container-pmv grid gap-10 py-16 sm:py-20 lg:grid-cols-[1fr_.72fr] lg:items-center"><PageIntro kicker="Nationwide Professional Services Network" title="A broad network. One dependable place to start." subtitle="Pinnacle handles practical one-time requests, recurring support, and multi-step projects across the U.S. Tell us what needs handling and we will help define the right scope."/><Reveal className="relative flex min-h-[250px] items-center justify-center"><div className="pmv-story-orbit pmv-story-orbit-animated" aria-hidden="true"/><BrandMark3D size={180} decorative className="relative z-10"/></Reveal></div></section>
    <section className="container-pmv py-14 sm:py-18"><Reveal className="mb-8 grid gap-5 lg:grid-cols-[.72fr_1.28fr] lg:items-end"><div><p className="eyebrow">Ways We Can Help</p><h2 className="mt-3 font-display text-3xl font-medium text-white sm:text-4xl">Small task or bigger project, start here.</h2></div><p className="max-w-2xl text-sm leading-7 text-slate-400">Start with the property, paperwork, deadline, problem, or outcome. We will confirm the scope, availability, pricing, and any qualified provider that may be required.</p></Reveal><div className="border-y border-white/10">{hubs.map(hub=><Reveal key={hub.to}><Link to={hub.to} className="group grid gap-4 border-b border-white/10 py-7 last:border-b-0 sm:grid-cols-[54px_48px_minmax(190px,.72fr)_1.28fr_auto] sm:items-center"><span className="font-display text-xs text-gold/70">{hub.n}</span><span className="text-gold"><Icon name={hub.icon} size={21}/></span><div><h2 className="text-xl font-semibold text-white transition group-hover:text-gold">{hub.title}</h2><p className="mt-1 text-[11px] uppercase tracking-[.11em] text-slate-500">{hub.includes}</p></div><p className="max-w-2xl text-sm leading-7 text-slate-400">{hub.body}</p><span className="text-gold transition-transform group-hover:translate-x-1">→</span></Link></Reveal>)}</div></section>
    <section className="pmv-gold-band border-y border-gold/15"><div className="container-pmv py-14 sm:py-18"><Reveal className="grid gap-8 lg:grid-cols-[.72fr_1.28fr]"><div><p className="eyebrow">Flexible by Design</p><h2 className="mt-3 font-display text-3xl font-medium text-white sm:text-4xl">The scope should match the work, not the other way around.</h2></div><div className="grid gap-x-8 sm:grid-cols-3">{[['One-time service','A cleaning, inspection, document run, notary appointment, filing task, or other clearly defined request.'],['Multi-step project','Coordination across vendors, documents, locations, deadlines, or several related services.'],['Ongoing support','Recurring property, administrative, or operational support when the work needs steady follow-through.']].map(([title,body])=><div key={title} className="border-t border-gold/30 py-4"><h3 className="font-semibold text-white">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-400">{body}</p></div>)}</div></Reveal></div></section>
    <section className="container-pmv py-14 sm:py-18"><Reveal className="max-w-3xl"><p className="eyebrow">Detailed service index</p><h2 className="mt-3 font-display text-3xl font-medium text-white">Need a more specific scope?</h2><p className="mt-3 text-sm leading-7 text-slate-400">The service pages below describe common use cases and intake requirements. They are starting points, not rigid packages.</p></Reveal><div className="mt-7 grid border-y border-white/10 sm:grid-cols-2">{services.map((service,i)=><Link key={service.slug} to={`/services/${service.slug}`} className={`group flex items-center justify-between gap-5 border-b border-white/10 py-5 sm:px-5 ${i%2===0?'sm:border-r':''}`}><div><p className="text-xs text-gold/70">{service.tag}</p><h3 className="mt-1 font-semibold text-white group-hover:text-gold">{service.title}</h3></div><span className="text-gold transition group-hover:translate-x-1">→</span></Link>)}</div></section>
    <section className="container-pmv pb-16"><Reveal className="flex flex-col items-start justify-between gap-5 border-t border-gold/20 pt-9 sm:flex-row sm:items-center"><div className="max-w-xl"><h2 className="font-display text-2xl font-medium text-white">Have a project that does not fit neatly into one category?</h2><p className="mt-2 text-sm leading-7 text-slate-400">That is often exactly where coordination matters most. Tell us what is changing and what outcome you need.</p></div><a href={CLIENT_SIGNUP} className={btnPrimary}>Discuss Your Project</a></Reveal></section>
  </main><Footer/></div>
}
