import { Header } from '../../components/public/Header'
import { Footer } from '../../components/public/Footer'
import { btnPrimary, PageIntro } from '../../components/public/ui'
import { Reveal } from '../../components/public/motion'
import { Breadcrumbs, BreadcrumbSlot } from '../../components/public/Breadcrumbs'
import { ViewTransitionLink } from '../../components/public/ViewTransitionLink'
import { BrandMark3D } from '../../components/ui'
import { services } from '../../data/services'
import { usePageMeta } from '../../lib/usePageMeta'
import { usePublicVisitor } from '../../lib/publicContext'
import type { OperatingWorld } from '../../../shared/workspace'
import { Icon, type IconName } from '../../components/kit/Icon'

const CLIENT_SIGNUP='/scope-request?source=services-overview'
const HUBS_WORLD: Record<string, OperatingWorld> = { 'Business Support': 'business', 'Property & Project Support': 'property', 'Personal & Administrative': 'documents' }
const hubs:{n:string;icon:IconName;title:string;body:string;to:string;includes:string}[]=[
  {n:'01',icon:'briefcase',title:'Business Support',body:'Operations consulting, administrative capacity, project coordination, POS and payment transitions, and funding readiness for owners and teams anywhere in the U.S.',to:'/services/business-operations',includes:'Consulting · Admin · Systems · POS &amp; payments · Funding'},
  {n:'02',icon:'building',title:'Property & Project Support',body:'Cleaning and turnovers, inspections and condition reports, field photos and BPO support, eviction document and possession work, and REO preservation. Owned South Florida crews with documented, geo-verified completion. Licensed property managers or CAMs are named when that work requires them.',to:'/services/property-field',includes:'Property support · Inspections · Vendors · Field photos · Evictions · REO'},
  {n:'03',icon:'file',title:'Personal & Administrative',body:'Document preparation, filing packets, courier and courthouse runs, mobile notarization, loan signings, and Remote Online Notarization. On-site in South Florida, RON nationwide.',to:'/services/mobile-documents',includes:'Document prep · Filing · Courier · Mobile notary · Loan signings · RON'},
]

const TAG_ORDER=['Business Services','Property Services','Document Services']

export default function ServicesOverview(){
  const visitor = usePublicVisitor()
  usePageMeta('Nationwide Professional Services Network - Pinnacle','Business operations, admin capacity, documents and signing (RON included), mobile notary, and property field services from Pinnacle Management Ventures - one dependable network available across the U.S.')
  return <div className="min-h-screen bg-navy-950"><Header/><main>
    <BreadcrumbSlot><Breadcrumbs items={[{ label: 'Services' }]} /></BreadcrumbSlot>
    <section className="pmv-hero-story relative overflow-hidden border-b border-white/10"><div className="pmv-hero-gold" aria-hidden="true"/><div className="container-pmv grid gap-10 py-10 sm:py-14 lg:grid-cols-[1fr_.72fr] lg:items-center"><PageIntro kicker="Services" title="Tell us what you need help with." subtitle="You do not need the exact service name. Start with the situation, or open a hub if you already know the path."/><Reveal className="relative flex min-h-[250px] items-center justify-center"><BrandMark3D size={168} decorative variant="quiet" className="relative z-10"/></Reveal></div></section>
    <section className="container-pmv py-14 sm:py-18"><Reveal className="mb-8 grid gap-5 lg:grid-cols-[.72fr_1.28fr] lg:items-end"><div><p className="eyebrow">Ways We Can Help</p><h2 className="mt-3 font-display text-3xl font-medium text-white sm:text-4xl">Small task or bigger project, start here.</h2></div><p className="max-w-2xl text-sm leading-7 text-slate-400">Start with the property, paperwork, deadline, problem, or outcome. We will confirm the scope, availability, pricing, and any qualified provider that may be required.</p></Reveal><div className="border-y border-white/10">{hubs.map(hub=><Reveal key={hub.to}><ViewTransitionLink to={hub.to} onClick={() => { const w = HUBS_WORLD[hub.title]; if (w) visitor.setWorld(w) }} className="group grid gap-4 border-b border-white/10 py-7 last:border-b-0 sm:grid-cols-[54px_48px_minmax(190px,.72fr)_1.28fr_auto] sm:items-center"><span className="font-display text-xs text-gold/70">{hub.n}</span><span className="text-gold"><Icon name={hub.icon} size={21}/></span><div><h2 className="text-xl font-semibold text-white transition group-hover:text-gold">{hub.title}</h2><p className="mt-1 text-[11px] uppercase tracking-[.11em] text-slate-500">{hub.includes}</p></div><p className="max-w-2xl text-sm leading-7 text-slate-400">{hub.body}</p><span className="text-gold transition-transform group-hover:translate-x-1">→</span></ViewTransitionLink></Reveal>)}</div></section>
    <section className="pmv-gold-band border-y border-gold/15"><div className="container-pmv py-14 sm:py-18"><Reveal className="grid gap-8 lg:grid-cols-[.72fr_1.28fr]"><div><p className="eyebrow">Flexible by Design</p><h2 className="mt-3 font-display text-3xl font-medium text-white sm:text-4xl">The scope should match the work, not the other way around.</h2></div><div className="grid gap-x-8 sm:grid-cols-3">{[['One-time service','A cleaning, inspection, document run, notary appointment, filing task, or other clearly defined request.'],['Multi-step project','Coordination across vendors, documents, locations, deadlines, or several related services.'],['Ongoing support','Recurring property, administrative, or operational support when the work needs steady follow-through.']].map(([title,body])=><div key={title} className="border-t border-gold/30 py-4"><h3 className="font-semibold text-white">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-400">{body}</p></div>)}</div></Reveal></div></section>
    <section className="border-y border-gold/20 bg-gradient-to-br from-gold/[.06] via-transparent to-transparent"><div className="container-pmv grid gap-8 py-14 sm:py-16 lg:grid-cols-[1fr_auto] lg:items-center"><Reveal><p className="eyebrow">Monthly plans</p><h2 className="mt-3 font-display text-3xl font-bold tracking-[-.03em] text-white sm:text-4xl">Most of this work repeats. Put it on a plan.</h2><p className="mt-4 max-w-2xl text-sm leading-7 text-slate-400">Property Care from $89/mo, Ops-on-Call from $199/mo, and a Legal &amp; Notary Pass from $99/mo. Every plan includes priority scheduling, a saved profile, and 10-25% member pricing on everything past the included volume.</p></Reveal><Reveal><ViewTransitionLink to="/care-plans" className={btnPrimary}>See Monthly Plans</ViewTransitionLink></Reveal></div></section>

    <section className="container-pmv py-14 sm:py-18"><Reveal className="max-w-3xl"><p className="eyebrow">Full service index</p><h2 className="mt-3 font-display text-3xl font-medium text-white">Every service, with real starting prices.</h2><p className="mt-3 text-sm leading-7 text-slate-400">Each page lists the defined services in that area with South Florida market-based pricing, what is included, and what changes the final quote.</p></Reveal>
      {TAG_ORDER.map(tag=>{const group=services.filter(service=>service.tag===tag);if(!group.length)return null;return <div key={tag} className="mt-10"><p className="text-[10px] font-bold uppercase tracking-[.18em] text-gold">{tag}</p><div className="mt-3 grid border-y border-white/10 sm:grid-cols-2">{group.map((service,i)=><ViewTransitionLink key={service.slug} to={`/services/${service.slug}`} className={`group flex items-start justify-between gap-5 border-b border-white/10 py-5 sm:px-5 ${i%2===0?'sm:border-r':''}`}><div className="min-w-0"><h3 className="font-semibold text-white group-hover:text-gold">{service.title}{service.popular&&<span className="ml-2 rounded-full border border-gold/30 px-2 py-0.5 align-middle text-[9px] font-bold uppercase tracking-wide text-gold">Popular</span>}</h3><p className="mt-1 text-xs leading-5 text-slate-500">{service.shortDescription}</p></div><span className="mt-1 text-gold transition group-hover:translate-x-1">→</span></ViewTransitionLink>)}</div></div>})}
    </section>
    <section className="container-pmv pb-16"><Reveal className="flex flex-col items-start justify-between gap-5 border-t border-gold/20 pt-9 sm:flex-row sm:items-center"><div className="max-w-xl"><h2 className="font-display text-2xl font-medium text-white">Have a project that does not fit neatly into one category?</h2><p className="mt-2 text-sm leading-7 text-slate-400">That is often exactly where coordination matters most. Tell us what is changing and what outcome you need.</p></div><ViewTransitionLink to={CLIENT_SIGNUP} className={btnPrimary}>Discuss Your Project</ViewTransitionLink></Reveal></section>
  </main><Footer/></div>
}
