import { Link } from 'react-router-dom'
import { Header } from '../../components/public/Header'
import { Footer } from '../../components/public/Footer'
import { btnPrimary, PageIntro } from '../../components/public/ui'
import { Reveal } from '../../components/public/motion'
import { BrandMark3D } from '../../components/ui'
import { services } from '../../data/services'
import { usePageMeta } from '../../lib/usePageMeta'
import { Icon, type IconName } from '../../components/kit/Icon'

const CLIENT_SIGNUP='https://secure.pinnaclemanagementventures.com/signup?source=services-overview'
const hubs:{n:string;icon:IconName;title:string;body:string;to:string;includes:string}[]=[
  {n:'01',icon:'briefcase',title:'Business Consulting & Operations',body:'For operational changes that need both judgment and implementation support: system and vendor transitions, POS and payments, process improvement, administrative projects, data coordination, and recurring operating support.',to:'/services/business-operations',includes:'Consulting · POS & payments · Process · Implementation'},
  {n:'02',icon:'building',title:'Property & Field Support',body:'A dependable local operating layer for owners, managers, and remote teams that need inspections, field verification, access coordination, vendor follow-up, and documented completion.',to:'/services/property-field',includes:'Owner support · Inspections · Field work · Vendors'},
  {n:'03',icon:'file',title:'Documents & Mobile Services',body:'Defined local assignments where a document, signer, office, or destination needs reliable physical handling and a clear chain of responsibility.',to:'/services/mobile-documents',includes:'Mobile notary · Courier · Signing support'},
]

export default function ServicesOverview(){
  usePageMeta('Consulting & Professional Services','Explore Pinnacle Management Ventures consulting, POS and payment transition support, operational coordination, property and field services, mobile notary, and document services.')
  return <div className="min-h-screen bg-navy-950"><Header/><main>
    <section className="pmv-hero-story relative overflow-hidden border-b border-white/10"><div className="pmv-hero-gold" aria-hidden="true"/><div className="container-pmv grid gap-10 py-16 sm:py-20 lg:grid-cols-[1fr_.72fr] lg:items-center"><PageIntro kicker="Consulting & Professional Services" title="Choose the capability. Keep one view of the outcome." subtitle="Pinnacle combines consulting, coordination, and hands-on support across three practical service areas. If your situation crosses more than one, the engagement can too."/><Reveal className="relative flex min-h-[250px] items-center justify-center"><div className="pmv-story-orbit pmv-story-orbit-animated" aria-hidden="true"/><BrandMark3D size={180} decorative className="relative z-10"/></Reveal></div></section>
    <section className="container-pmv py-14 sm:py-18"><Reveal className="mb-8 grid gap-5 lg:grid-cols-[.72fr_1.28fr] lg:items-end"><div><p className="eyebrow">Core capabilities</p><h2 className="mt-3 font-display text-3xl font-medium text-white sm:text-4xl">Start where the work is stuck.</h2></div><p className="max-w-2xl text-sm leading-7 text-slate-400">You do not need to diagnose the service category before reaching out. Start with the change, problem, deadline, or result you need; the first job is defining the right scope.</p></Reveal><div className="border-y border-white/10">{hubs.map(hub=><Reveal key={hub.to}><Link to={hub.to} className="group grid gap-4 border-b border-white/10 py-7 last:border-b-0 sm:grid-cols-[54px_48px_minmax(190px,.72fr)_1.28fr_auto] sm:items-center"><span className="font-display text-xs text-gold/70">{hub.n}</span><span className="text-gold"><Icon name={hub.icon} size={21}/></span><div><h2 className="text-xl font-semibold text-white transition group-hover:text-gold">{hub.title}</h2><p className="mt-1 text-[11px] uppercase tracking-[.11em] text-slate-500">{hub.includes}</p></div><p className="max-w-2xl text-sm leading-7 text-slate-400">{hub.body}</p><span className="text-gold transition-transform group-hover:translate-x-1">→</span></Link></Reveal>)}</div></section>
    <section className="pmv-gold-band border-y border-gold/15"><div className="container-pmv py-14 sm:py-18"><Reveal className="grid gap-8 lg:grid-cols-[.72fr_1.28fr]"><div><p className="eyebrow">Engagement structure</p><h2 className="mt-3 font-display text-3xl font-medium text-white sm:text-4xl">The scope should match the work: not the other way around.</h2></div><div className="grid gap-x-8 sm:grid-cols-3">{[['Defined assignment','A focused task or short engagement with a clear deliverable and handoff.'],['Project / transition','Hands-on coordination through a migration, implementation, operational change, or multi-step initiative.'],['Ongoing support','Recurring consulting or operational support when consistent follow-through is needed without adding another full-time role.']].map(([title,body])=><div key={title} className="border-t border-gold/30 py-4"><h3 className="font-semibold text-white">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-400">{body}</p></div>)}</div></Reveal></div></section>
    <section className="container-pmv py-14 sm:py-18"><Reveal className="max-w-3xl"><p className="eyebrow">Detailed service index</p><h2 className="mt-3 font-display text-3xl font-medium text-white">Need a more specific scope?</h2><p className="mt-3 text-sm leading-7 text-slate-400">The service pages below describe common use cases and intake requirements. They are starting points, not rigid packages.</p></Reveal><div className="mt-7 grid border-y border-white/10 sm:grid-cols-2">{services.map((service,i)=><Link key={service.slug} to={`/services/${service.slug}`} className={`group flex items-center justify-between gap-5 border-b border-white/10 py-5 sm:px-5 ${i%2===0?'sm:border-r':''}`}><div><p className="text-xs text-gold/70">{service.tag}</p><h3 className="mt-1 font-semibold text-white group-hover:text-gold">{service.title}</h3></div><span className="text-gold transition group-hover:translate-x-1">→</span></Link>)}</div></section>
    <section className="container-pmv pb-16"><Reveal className="flex flex-col items-start justify-between gap-5 border-t border-gold/20 pt-9 sm:flex-row sm:items-center"><div className="max-w-xl"><h2 className="font-display text-2xl font-medium text-white">Have a project that does not fit neatly into one category?</h2><p className="mt-2 text-sm leading-7 text-slate-400">That is often exactly where coordination matters most. Tell us what is changing and what outcome you need.</p></div><a href={CLIENT_SIGNUP} className={btnPrimary}>Discuss Your Project</a></Reveal></section>
  </main><Footer/></div>
}