import { useEffect, useMemo, useRef, useState } from 'react'
import { useParams } from 'react-router-dom'
import { AlertCircle, Check, CheckCircle2, ChevronDown, ChevronRight, FileText, LockKeyhole, ShieldCheck } from 'lucide-react'
import { Logo } from '../../components/ui'
import { btnPrimary, btnOutline } from '../../components/public/ui'

type PacketDoc={id:string;title:string;sort_order:number;required:number;original_name?:string|null;mime_type?:string|null}
type FieldData={id:string;envelope_document_id?:string|null;page_number:number;field_type:string;required:number;label:string|null;value_text:string|null;completed_at:string|null;validation_json?:string|null;condition_json?:string|null;validation_error_message?:string|null}
type Data={recipient:{id:string;name:string;email:string;status:string};envelope:{id:string;title:string;message:string|null;public_id:string;status:string;expires_at:string|null;branding_profile_id?:string|null};documents?:PacketDoc[];fields:FieldData[]}

export default function SignerExperience(){
  const {token=''}=useParams();const [data,setData]=useState<Data|null>(null),[error,setError]=useState(''),[challenge,setChallenge]=useState(''),[code,setCode]=useState(''),[session,setSession]=useState(''),[busy,setBusy]=useState(false),[done,setDone]=useState(false),[consented,setConsented]=useState(false),[activeDoc,setActiveDoc]=useState(''),[mobilePreview,setMobilePreview]=useState(false)
  const fieldRefs=useRef<Record<string,HTMLDivElement|null>>({})
  const [adopted,setAdopted]=useState<{name:string;initials:string}>({name:'',initials:''})
  async function load(){try{const r=await fetch(`/api/sign/${encodeURIComponent(token)}`);const j:any=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||'Unable to open document');setData(j as Data);setError('');const docs=(j.documents||[]) as PacketDoc[];setActiveDoc(v=>v||docs[0]?.id||'source')}catch(e:any){setError(e.message)}}
  useEffect(()=>{void load()},[token])
  async function requestOtp(){setBusy(true);setError('');try{const r=await fetch(`/api/sign/${encodeURIComponent(token)}/otp`,{method:'POST'});const j:any=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||'Could not send code');setChallenge(String(j.challenge_id||''))}catch(e:any){setError(e.message)}finally{setBusy(false)}}
  async function verify(){setBusy(true);setError('');try{const r=await fetch(`/api/sign/${encodeURIComponent(token)}/otp/verify`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({challenge_id:challenge,code})});const j:any=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||'Could not verify code');setSession(String(j.session_token||''));await load()}catch(e:any){setError(e.message)}finally{setBusy(false)}}
  async function acceptConsent(){setBusy(true);setError('');try{const r=await fetch(`/api/sign/${encodeURIComponent(token)}/consent`,{method:'POST',headers:{'Content-Type':'application/json','x-signing-session':session},body:JSON.stringify({accepted:true})});const j:any=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||'Could not record consent');setConsented(true)}catch(e:any){setError(e.message)}finally{setBusy(false)}}
  async function saveField(id:string,payload:any){const r=await fetch(`/api/sign/${encodeURIComponent(token)}/fields/${id}`,{method:'POST',headers:{'Content-Type':'application/json','x-signing-session':session},body:JSON.stringify(payload)});const j:any=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||'Could not save field');await load()}
  async function complete(){setBusy(true);setError('');try{const r=await fetch(`/api/sign/${encodeURIComponent(token)}/complete`,{method:'POST',headers:{'x-signing-session':session}});const j:any=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||'Could not complete envelope');setDone(true)}catch(e:any){setError(e.message)}finally{setBusy(false)}}
  async function decline(){const reason=window.prompt('Optional reason for declining:')||'';const r=await fetch(`/api/sign/${encodeURIComponent(token)}/decline`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({reason})});const j:any=await r.json().catch(()=>({}));if(!r.ok){setError(j.error||'Could not decline envelope');return}setDone(true)}

  const docs=useMemo<PacketDoc[]>(()=>{if(!data)return[];return data.documents?.length?data.documents:[{id:'source',title:data.envelope.title,sort_order:1,required:1}]},[data])
  const activeFields=useMemo(()=>{if(!data)return[];const values=new Map(data.fields.map(f=>[f.id,String(f.value_text||'')]));return data.fields.filter(f=>{if(!f.condition_json)return true;try{const c=JSON.parse(f.condition_json);if(c.field_id&&c.equals!==undefined)return values.get(String(c.field_id))===String(c.equals);return true}catch{return true}})},[data])
  const required=activeFields.filter(f=>f.required===1),completed=required.filter(f=>!!f.completed_at),progress=required.length?Math.round(completed.length/required.length*100):100,nextRequired=required.find(f=>!f.completed_at)
  function jumpNext(){if(!nextRequired)return;const doc=nextRequired.envelope_document_id||'source';setActiveDoc(doc);setMobilePreview(false);setTimeout(()=>fieldRefs.current[nextRequired.id]?.scrollIntoView({behavior:'smooth',block:'center'}),80)}
  // Adopt-a-signature: the signer types their name once, then applies it to any
  // signature/initials field with a single tap instead of retyping every time.
  const signatureFields=useMemo(()=>activeFields.filter(f=>f.field_type==='signature'||f.field_type==='initial'),[activeFields])
  async function applyAdopted(f:FieldData){if(!adopted.name)return;await saveField(f.id,{value:f.field_type==='initial'?adopted.initials:adopted.name})}
  async function applyAllAdopted(){if(!adopted.name)return;for(const f of signatureFields){if(!f.completed_at)await saveField(f.id,{value:f.field_type==='initial'?adopted.initials:adopted.name})}}

  if(error&&!data)return <Shell><StateCard icon={<AlertCircle size={26}/>} title="This secure link is not available" body={error}/></Shell>
  if(done)return <Shell><StateCard icon={<CheckCircle2 size={30}/>} title="Your response has been recorded" body="You can close this window. Pinnacle has recorded the updated envelope status and supporting audit evidence." success/></Shell>
  if(!data)return <Shell><StateCard icon={<LockKeyhole size={24}/>} title="Opening secure envelope" body="Preparing your protected document workspace."/></Shell>
  const authed=!!session

  return <Shell>
    <div className="mx-auto max-w-[1500px]">
      <div className="mb-4 rounded-2xl border border-white/10 bg-white/[.025] p-4 sm:p-5">
        <div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between">
          <div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><span className="rounded-full border border-gold/25 bg-gold/[.07] px-2.5 py-1 text-[10px] font-bold uppercase tracking-[.14em] text-gold">Secure e-Signature</span><span className="text-xs text-slate-500">{data.envelope.public_id}</span></div><h1 className="mt-3 font-display text-2xl leading-tight text-white sm:text-3xl lg:text-4xl">{data.envelope.title}</h1>{data.envelope.message&&<p className="mt-2 max-w-3xl text-sm leading-6 text-slate-400">{data.envelope.message}</p>}<p className="mt-3 text-xs text-slate-500">Prepared for <span className="font-semibold text-slate-300">{data.recipient.name}</span> · {data.recipient.email}</p></div>
          <div className="w-full rounded-xl border border-white/10 bg-navy-950/50 p-3 lg:w-64"><div className="flex items-center justify-between text-xs"><span className="font-bold text-slate-300">Required fields</span><span className="text-gold">{completed.length}/{required.length}</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-gold transition-all" style={{width:`${progress}%`}}/></div><p className="mt-2 text-[11px] text-slate-500">{progress===100?'Ready to submit':'Your progress saves as you apply each field.'}</p></div>
        </div>
      </div>

      {!authed?<VerificationPanel challenge={challenge} code={code} setCode={setCode} busy={busy} requestOtp={requestOtp} verify={verify} error={error}/>:!consented?<ConsentPanel busy={busy} acceptConsent={acceptConsent} error={error}/>:<div className="grid gap-4 xl:grid-cols-[minmax(0,1.45fr)_minmax(360px,.55fr)]">
        <PanelCard className="overflow-hidden !p-0">
          <div className="border-b border-white/10 p-3 sm:p-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-bold text-white">Document packet</p><p className="mt-1 text-[11px] text-slate-500">{docs.length} document{docs.length===1?'':'s'} in this envelope</p></div><div className="flex gap-2 overflow-x-auto pb-1">{docs.map((d,i)=><button key={d.id} onClick={()=>{setActiveDoc(d.id);setMobilePreview(true)}} className={`shrink-0 rounded-lg border px-3 py-2 text-xs font-bold ${activeDoc===d.id?'border-gold/35 bg-gold/[.08] text-gold':'border-white/10 text-slate-400'}`}>{i+1}. {d.title}</button>)}</div></div></div>
          <div className={`${mobilePreview?'block':'hidden'} xl:block`}><iframe title="Secure document preview" src={`/api/sign/${encodeURIComponent(token)}/documents/${encodeURIComponent(activeDoc||'source')}/file`} className="h-[58vh] w-full bg-white sm:h-[66vh] xl:h-[72vh]"/></div>
          <button onClick={()=>setMobilePreview(v=>!v)} className="flex w-full items-center justify-between border-t border-white/10 px-4 py-3 text-xs font-bold text-slate-300 xl:hidden"><span>{mobilePreview?'Hide document preview':'Show document preview'}</span><ChevronDown size={14} className={mobilePreview?'rotate-180 transition':'transition'}/></button>
        </PanelCard>

        <div className="space-y-4">
          <PanelCard><div className="flex items-center gap-2"><ShieldCheck size={17} className="text-gold"/><div><p className="text-sm font-extrabold text-white">Guided signing</p><p className="text-[11px] text-slate-500">Complete the highlighted required fields, then submit once.</p></div></div>{nextRequired&&<button className={`${btnOutline} mt-4 w-full justify-between`} onClick={jumpNext}><span>Go to next required field</span><ChevronRight size={15}/></button>}</PanelCard>
          {signatureFields.length>0&&<AdoptCard suggestName={data.recipient.name} adopted={adopted} setAdopted={setAdopted} onApplyAll={applyAllAdopted} remaining={signatureFields.filter(f=>!f.completed_at).length}/>}
          <div className="space-y-3">{activeFields.map(f=><div key={f.id} ref={el=>{fieldRefs.current[f.id]=el}}><Field field={f} save={saveField} adopted={adopted} onApply={()=>applyAdopted(f)}/></div>)}</div>
          {error&&<div className="rounded-xl border border-rose-400/20 bg-rose-400/[.06] p-3 text-sm text-rose-200"><div className="flex items-start gap-2"><AlertCircle size={16} className="mt-0.5 shrink-0"/><span>{error}</span></div></div>}
          <div className="hidden rounded-2xl border border-white/10 bg-navy-950/95 p-4 shadow-2xl xl:block"><button className={`${btnPrimary} w-full justify-center`} onClick={complete} disabled={busy||progress<100}>{busy?'Submitting…':'Complete & Submit'}</button><button className={`${btnOutline} mt-2 w-full justify-center`} onClick={decline}>Decline</button><p className="mt-3 text-center text-[10px] leading-4 text-slate-600">Submitting records the completion event and finalizes the evidentiary audit chain.</p></div>
        </div>
      </div>}
    </div>
    {authed&&<div className="fixed inset-x-0 bottom-0 z-40 border-t border-white/10 bg-navy-950/95 p-3 backdrop-blur-xl xl:hidden"><div className="mx-auto flex max-w-3xl gap-2"><button className={`${btnOutline} flex-1 justify-center`} onClick={nextRequired?jumpNext:decline}>{nextRequired?'Next Field':'Decline'}</button><button className={`${btnPrimary} flex-[1.4] justify-center`} onClick={complete} disabled={busy||progress<100}>{busy?'Submitting…':progress<100?`${progress}% Complete`:'Complete & Submit'}</button></div></div>}
  </Shell>
}

function VerificationPanel({challenge,code,setCode,busy,requestOtp,verify,error}:{challenge:string;code:string;setCode:(v:string)=>void;busy:boolean;requestOtp:()=>void;verify:()=>void;error:string}){return <div className="mx-auto max-w-xl py-6 sm:py-10"><PanelCard className="border-gold/20 bg-gradient-to-br from-gold/[.055] to-transparent"><div className="grid h-11 w-11 place-items-center rounded-xl border border-gold/25 bg-gold/[.08] text-gold"><LockKeyhole size={20}/></div><h2 className="mt-4 font-display text-2xl text-white">Verify your identity to continue</h2><p className="mt-2 text-sm leading-6 text-slate-400">We will send a one-time code to the email address associated with this signing request. Authentication, timestamps, and technical evidence become part of the envelope audit record.</p>{!challenge?<button className={`${btnPrimary} mt-5 w-full justify-center sm:w-auto`} onClick={requestOtp} disabled={busy}>{busy?'Sending…':'Send Verification Code'}</button>:<div className="mt-5"><label className="text-xs font-bold text-slate-300">6-digit verification code</label><input className="mt-2 w-full rounded-xl border border-white/15 bg-white/[.03] px-4 py-3.5 text-lg tracking-[.28em] text-white outline-none focus:border-gold" value={code} maxLength={6} onChange={e=>setCode(e.target.value.replace(/\D/g,'').slice(0,6))} placeholder="000000" inputMode="numeric" autoComplete="one-time-code"/><button className={`${btnPrimary} mt-3 w-full justify-center`} onClick={verify} disabled={busy||code.length<6}>{busy?'Verifying…':'Verify & Open Documents'}</button></div>}{error&&<p className="mt-4 text-sm text-rose-300">{error}</p>}</PanelCard></div>}

function ConsentPanel({busy,acceptConsent,error}:{busy:boolean;acceptConsent:()=>void;error:string}){return <div className="mx-auto max-w-xl py-6 sm:py-10"><PanelCard className="border-gold/20 bg-gradient-to-br from-gold/[.055] to-transparent"><div className="grid h-11 w-11 place-items-center rounded-xl border border-gold/25 bg-gold/[.08] text-gold"><ShieldCheck size={20}/></div><h2 className="mt-4 font-display text-2xl text-white">Consent to sign electronically</h2><p className="mt-2 text-sm leading-6 text-slate-400">Before applying your signature, confirm that you agree to complete this transaction electronically. Your consent, device details, and location evidence are recorded in the finalized audit trail.</p><label className="mt-5 flex items-start gap-3 rounded-xl border border-white/10 bg-white/[.02] p-4 text-sm leading-6 text-slate-300"><input type="checkbox" className="mt-1 h-4 w-4 accent-[#d6b86e]" onChange={(e)=>{if(e.target.checked)void acceptConsent()}} disabled={busy}/><span>I agree to use electronic records and electronic signatures for this transaction.</span></label><button className={`${btnPrimary} mt-4 w-full justify-center`} onClick={acceptConsent} disabled={busy}>{busy?'Recording consent…':'Continue to signing'}</button>{error&&<p className="mt-4 text-sm text-rose-300">{error}</p>}</PanelCard></div>}

const SIG_FONT='"Segoe Script","Bradley Hand","Brush Script MT",cursive'
type Adopted={name:string;initials:string}

function AdoptCard({suggestName,adopted,setAdopted,onApplyAll,remaining}:{suggestName:string;adopted:Adopted;setAdopted:(v:Adopted)=>void;onApplyAll:()=>void;remaining:number}){
  const [name,setName]=useState(adopted.name||suggestName||'')
  const initials=(name.trim().split(/\s+/).map(p=>p[0]||'').join('')||'').slice(0,4).toUpperCase()
  const isAdopted=!!adopted.name
  return <PanelCard className="border-gold/25 bg-gradient-to-br from-gold/[.05] to-transparent">
    <p className="text-sm font-extrabold text-white">Adopt your signature</p>
    <p className="mt-1 text-[11px] leading-4 text-slate-500">Type your name once, then apply it to every signature and initials field with one tap.</p>
    <label className="mt-3 block"><span className="text-[11px] font-bold text-slate-400">Your full name</span><input className="mt-1 w-full rounded-xl border border-white/15 bg-white/[.03] px-4 py-2.5 text-white outline-none focus:border-gold" value={name} onChange={e=>setName(e.target.value)} placeholder="Full legal name" autoComplete="name"/></label>
    {name.trim()&&<div className="mt-3 grid grid-cols-[1fr_auto] gap-2">
      <div className="rounded-xl border border-white/12 bg-white/[.03] px-4 py-3"><span className="block text-[10px] uppercase tracking-wide text-slate-500">Signature</span><span className="block truncate text-2xl text-white" style={{fontFamily:SIG_FONT}}>{name.trim()}</span></div>
      <div className="rounded-xl border border-white/12 bg-white/[.03] px-4 py-3 text-center"><span className="block text-[10px] uppercase tracking-wide text-slate-500">Initials</span><span className="block text-2xl text-white" style={{fontFamily:SIG_FONT}}>{initials}</span></div>
    </div>}
    {!isAdopted
      ?<button type="button" className={`${btnPrimary} mt-3 w-full justify-center`} disabled={!name.trim()} onClick={()=>setAdopted({name:name.trim(),initials})}>Adopt signature</button>
      :<div className="mt-3 flex flex-col gap-2 sm:flex-row"><button type="button" className={`${btnOutline} flex-1 justify-center`} onClick={()=>setAdopted({name:'',initials:''})}>Change</button>{remaining>0&&<button type="button" className={`${btnPrimary} flex-1 justify-center`} onClick={onApplyAll}>Apply to all {remaining}</button>}</div>}
  </PanelCard>
}

function Field({field,save,adopted,onApply}:{field:FieldData;save:(id:string,p:any)=>Promise<void>;adopted?:Adopted;onApply?:()=>Promise<void>}){
  const [value,setValue]=useState(field.value_text||''),[saving,setSaving]=useState(false),[localError,setLocalError]=useState('')
  useEffect(()=>setValue(field.value_text||''),[field.value_text])
  const label=field.label||({signature:'Legal signature',initial:'Initials',date:'Date',text:'Text',checkbox:'Confirmation'} as any)[field.field_type]
  const complete=!!field.completed_at
  async function persist(payload:any){setSaving(true);setLocalError('');try{await save(field.id,payload)}catch(e:any){setLocalError(e.message||'Could not save field')}finally{setSaving(false)}}
  const header=<span className="mb-2 flex items-center gap-2 text-sm font-bold text-white">{label}{field.required===1&&<span className="text-gold">*</span>}{complete&&<Check size={14} className="text-emerald-300"/>}<span className="ml-auto text-[10px] font-normal text-slate-600">Page {field.page_number}</span></span>
  if(field.field_type==='checkbox')return <PanelCard className={complete?'border-emerald-400/20 bg-emerald-400/[.035]':''}><label className="flex cursor-pointer items-start gap-3"><input type="checkbox" className="mt-1 h-4 w-4 accent-[#d6b86e]" checked={value==='true'} onChange={async e=>{const v=e.target.checked?'true':'false';setValue(v);await persist({checked:e.target.checked})}}/><span className="min-w-0 flex-1"><span className="flex items-center gap-2 text-sm font-bold text-white">{label}{field.required===1&&<span className="text-gold">*</span>}{complete&&<Check size={14} className="text-emerald-300"/>}</span><span className="mt-1 block text-[11px] text-slate-500">Page {field.page_number}</span>{localError&&<span className="mt-2 block text-xs text-rose-300">{localError}</span>}</span></label></PanelCard>
  if(field.field_type==='signature'||field.field_type==='initial'){
    const sig=adopted?.name?(field.field_type==='initial'?adopted.initials:adopted.name):''
    return <PanelCard className={complete?'border-emerald-400/20 bg-emerald-400/[.035]':''}>{header}
      {complete
        ?<div className="rounded-xl border border-white/12 bg-white/[.03] px-4 py-3 text-3xl leading-none text-white" style={{fontFamily:SIG_FONT}}>{value||sig}</div>
        :sig
          ?<button type="button" className="flex w-full items-center justify-between rounded-xl border border-gold/40 bg-gold/[.06] px-4 py-3 text-left hover:bg-gold/[.12] disabled:opacity-50" disabled={saving} onClick={async()=>{if(!onApply)return;setSaving(true);setLocalError('');try{await onApply()}catch(e:any){setLocalError(e?.message||'Could not apply')}finally{setSaving(false)}}}><span className="truncate text-2xl text-white" style={{fontFamily:SIG_FONT}}>{sig}</span><span className="ml-3 shrink-0 text-xs font-bold text-gold">{saving?'Applying…':'Tap to sign here'}</span></button>
          :<div className="flex flex-col gap-2 sm:flex-row"><input className="min-w-0 flex-1 rounded-xl border border-white/15 bg-white/[.03] px-4 py-3 text-white outline-none focus:border-gold" value={value} autoComplete="name" placeholder={field.field_type==='signature'?'Type your full legal signature':'Your initials'} onChange={e=>setValue(e.target.value)}/><button type="button" className="rounded-xl border border-gold/30 px-4 py-3 text-sm font-bold text-gold hover:bg-gold/10 disabled:opacity-50" disabled={saving||!value.trim()} onClick={()=>persist({value})}>{saving?'Saving…':'Apply'}</button></div>}
      {!complete&&!sig&&<p className="mt-2 text-[11px] text-slate-500">Tip: adopt your signature above to sign every field with one tap.</p>}
      {localError&&<span className="mt-2 block text-xs text-rose-300">{localError}</span>}
    </PanelCard>
  }
  return <PanelCard className={complete?'border-emerald-400/20 bg-emerald-400/[.035]':''}><label className="block">{header}<div className="flex flex-col gap-2 sm:flex-row"><input className="min-w-0 flex-1 rounded-xl border border-white/15 bg-white/[.03] px-4 py-3 text-white outline-none focus:border-gold" type={field.field_type==='date'?'date':'text'} value={value} autoComplete="off" placeholder="Enter value" onChange={e=>setValue(e.target.value)}/><button type="button" className="rounded-xl border border-gold/30 px-4 py-3 text-sm font-bold text-gold hover:bg-gold/10 disabled:opacity-50" disabled={saving} onClick={()=>persist({value})}>{saving?'Saving…':complete?'Update':'Apply'}</button></div>{localError&&<span className="mt-2 block text-xs text-rose-300">{localError}</span>}</label></PanelCard>
}

function PanelCard({children,className=''}:{children:any;className?:string}){return <div className={`rounded-2xl border border-white/10 bg-white/[.022] p-4 sm:p-5 ${className}`}>{children}</div>}
function StateCard({icon,title,body,success=false}:{icon:any;title:string;body:string;success?:boolean}){return <div className="mx-auto max-w-lg py-16 text-center"><div className={`mx-auto grid h-14 w-14 place-items-center rounded-2xl border ${success?'border-emerald-400/25 bg-emerald-400/[.07] text-emerald-300':'border-gold/25 bg-gold/[.07] text-gold'}`}>{icon}</div><h1 className="mt-5 font-display text-3xl text-white">{title}</h1><p className="mt-3 text-sm leading-6 text-slate-400">{body}</p></div>}
function Shell({children}:{children:any}){return <div className="min-h-screen bg-navy-950 pb-24 text-slate-100 xl:pb-0"><header className="sticky top-0 z-30 border-b border-white/10 bg-navy-950/92 backdrop-blur-xl"><div className="container-pmv flex h-16 items-center justify-between"><Logo/><div className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-[.12em] text-slate-500"><ShieldCheck size={14} className="text-gold"/>Secure Signing</div></div></header><main className="container-pmv py-5 sm:py-8">{children}</main><footer className="container-pmv border-t border-white/10 py-6 text-xs leading-5 text-slate-500">Electronic signing records include authentication and technical evidence for integrity purposes. This signing workflow is not represented as remote online notarization unless a separate compliant RON session is expressly identified.</footer></div>}
