import { useEffect, useState } from 'react'
import { useParams } from 'react-router-dom'
import { Logo } from '../../components/ui'
import { btnPrimary, btnOutline } from '../../components/public/ui'

type Data={recipient:{id:string;name:string;email:string;status:string};envelope:{id:string;title:string;message:string|null;public_id:string;status:string;expires_at:string|null};fields:Array<{id:string;page_number:number;field_type:string;required:number;label:string|null;value_text:string|null;completed_at:string|null}>}

export default function SignerExperience(){
  const {token=''}=useParams(); const [data,setData]=useState<Data|null>(null),[error,setError]=useState(''),[challenge,setChallenge]=useState(''),[code,setCode]=useState(''),[session,setSession]=useState(''),[busy,setBusy]=useState(false),[done,setDone]=useState(false)
  async function load(){try{const r=await fetch(`/api/sign/${encodeURIComponent(token)}`);const j=await r.json();if(!r.ok)throw new Error(j.error||'Unable to open document');setData(j)}catch(e:any){setError(e.message)}}
  useEffect(()=>{void load()},[token])
  async function requestOtp(){setBusy(true);try{const r=await fetch(`/api/sign/${encodeURIComponent(token)}/otp`,{method:'POST'});const j=await r.json();if(!r.ok)throw new Error(j.error);setChallenge(j.challenge_id)}catch(e:any){setError(e.message)}finally{setBusy(false)}}
  async function verify(){setBusy(true);try{const r=await fetch(`/api/sign/${encodeURIComponent(token)}/otp/verify`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({challenge_id:challenge,code})});const j=await r.json();if(!r.ok)throw new Error(j.error);setSession(j.session_token);await load()}catch(e:any){setError(e.message)}finally{setBusy(false)}}
  async function saveField(id:string,payload:any){const r=await fetch(`/api/sign/${encodeURIComponent(token)}/fields/${id}`,{method:'POST',headers:{'Content-Type':'application/json','x-signing-session':session},body:JSON.stringify(payload)});const j=await r.json();if(!r.ok)throw new Error(j.error);await load()}
  async function complete(){setBusy(true);try{const r=await fetch(`/api/sign/${encodeURIComponent(token)}/complete`,{method:'POST',headers:{'x-signing-session':session}});const j=await r.json();if(!r.ok)throw new Error(j.error);setDone(true)}catch(e:any){setError(e.message)}finally{setBusy(false)}}
  async function decline(){const reason=window.prompt('Optional reason for declining:')||'';const r=await fetch(`/api/sign/${encodeURIComponent(token)}/decline`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({reason})});if(r.ok)setDone(true)}
  if(error&&!data)return <Shell><p className="text-center text-rose-300">{error}</p></Shell>
  if(done)return <Shell><div className="text-center"><p className="eyebrow">Pinnacle Documents</p><h1 className="mt-3 font-display text-3xl text-white">Your response has been recorded.</h1><p className="mt-3 text-slate-400">You may close this window. The envelope owner can see the updated status immediately.</p></div></Shell>
  if(!data)return <Shell><p className="text-center text-slate-400">Opening secure envelope…</p></Shell>
  const authed=!!session
  return <Shell><div className="mx-auto max-w-3xl"><div className="mb-8 border-b border-white/10 pb-6"><p className="eyebrow">Secure document · {data.envelope.public_id}</p><h1 className="mt-3 font-display text-4xl text-white">{data.envelope.title}</h1>{data.envelope.message&&<p className="mt-3 text-slate-400">{data.envelope.message}</p>}<p className="mt-4 text-sm text-slate-500">Signer: {data.recipient.name} · {data.recipient.email}</p></div>
  {!authed?<div className="rounded-2xl border border-gold/20 bg-gold/[.04] p-6"><h2 className="font-display text-2xl text-white">Verify your email before signing</h2><p className="mt-2 text-sm leading-6 text-slate-400">Pinnacle records authentication method, timestamp, network metadata, and device/browser evidence as part of the envelope audit trail.</p>{!challenge?<button className={`${btnPrimary} mt-5`} onClick={requestOtp} disabled={busy}>{busy?'Sending…':'Send verification code'}</button>:<div className="mt-5 flex flex-col gap-3 sm:flex-row"><input className="rounded-lg border border-white/15 bg-white/[.03] px-4 py-3 text-white outline-none focus:border-gold" value={code} onChange={e=>setCode(e.target.value)} placeholder="6-digit code" inputMode="numeric"/><button className={btnPrimary} onClick={verify} disabled={busy||code.length<6}>{busy?'Verifying…':'Verify'}</button></div>}</div>:<><div className="space-y-4">{data.fields.map(f=><Field key={f.id} field={f} save={saveField}/>)}</div><div className="mt-8 flex flex-wrap gap-3 border-t border-white/10 pt-6"><button className={btnPrimary} onClick={complete} disabled={busy}>{busy?'Completing…':'Complete & Submit'}</button><button className={btnOutline} onClick={decline}>Decline</button></div></>}{error&&<p className="mt-4 text-sm text-rose-300">{error}</p>}</div></Shell>
}

function Field({field,save}:{field:any;save:(id:string,p:any)=>Promise<void>}){const [value,setValue]=useState(field.value_text||'');const label=field.label||({signature:'Signature',initial:'Initials',date:'Date',text:'Text',checkbox:'Confirmation'} as any)[field.field_type];if(field.field_type==='checkbox')return <label className="flex items-start gap-3 rounded-xl border border-white/10 p-4"><input type="checkbox" checked={value==='true'} onChange={async e=>{setValue(e.target.checked?'true':'false');await save(field.id,{checked:e.target.checked})}}/><span><strong className="text-white">{label}</strong>{field.required===1&&<span className="ml-1 text-gold">*</span>}<span className="block text-xs text-slate-500">Page {field.page_number}</span></span></label>;return <label className="block rounded-xl border border-white/10 p-4"><span className="mb-2 block text-sm font-medium text-white">{label}{field.required===1&&<span className="ml-1 text-gold">*</span>} <span className="font-normal text-slate-500">· page {field.page_number}</span></span><div className="flex gap-2"><input className="min-w-0 flex-1 rounded-lg border border-white/15 bg-white/[.03] px-4 py-3 text-white outline-none focus:border-gold" type={field.field_type==='date'?'date':'text'} value={value} placeholder={field.field_type==='signature'?'Type your full legal signature':field.field_type==='initial'?'Initials':''} onChange={e=>setValue(e.target.value)}/><button className="rounded-lg border border-gold/30 px-4 text-sm font-semibold text-gold hover:bg-gold/10" onClick={()=>save(field.id,{value})}>Apply</button></div></label>}
function Shell({children}:{children:any}){return <div className="min-h-screen bg-navy-950 text-slate-100"><header className="border-b border-white/10"><div className="container-pmv flex h-16 items-center"><Logo/></div></header><main className="container-pmv py-12 sm:py-16">{children}</main><footer className="container-pmv border-t border-white/10 py-6 text-xs leading-5 text-slate-500">Electronic signing records include authentication and technical evidence for integrity purposes. This signing workflow is not represented as a remote online notarization unless a separate compliant RON session is expressly identified.</footer></div>}
