import { useEffect, useState } from 'react'
import { useParams } from 'react-router-dom'
import { CheckCircle2, LockKeyhole, ShieldCheck } from 'lucide-react'
import { Logo } from '../../components/ui'
import { btnPrimary, btnOutline } from '../../components/public/ui'

type Data={recipient:{id:string;name:string;email:string;status:string};envelope:{id:string;title:string;message:string|null;public_id:string;status:string;expires_at:string|null};fields:Array<{id:string;page_number:number;field_type:string;required:number;label:string|null;value_text:string|null;completed_at:string|null}>}

export default function SignerExperience(){
  const {token=''}=useParams(); const [data,setData]=useState<Data|null>(null),[error,setError]=useState(''),[challenge,setChallenge]=useState(''),[code,setCode]=useState(''),[session,setSession]=useState(''),[busy,setBusy]=useState(false),[done,setDone]=useState(false)
  const onMailHost=typeof window!=='undefined'&&window.location.hostname.startsWith('mail.')
  async function load(){try{const r=await fetch(`/api/sign/${encodeURIComponent(token)}`);const j:any=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||'Unable to open document');setData(j as Data)}catch(e:any){setError(e.message)}}
  useEffect(()=>{if(!onMailHost){window.location.replace(`https://mail.pinnaclemanagementventures.com/sign/${encodeURIComponent(token)}`);return}void load()},[token,onMailHost])
  async function requestOtp(){setBusy(true);try{const r=await fetch(`/api/sign/${encodeURIComponent(token)}/otp`,{method:'POST'});const j:any=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error);setChallenge(String(j.challenge_id||''))}catch(e:any){setError(e.message)}finally{setBusy(false)}}
  async function verify(){setBusy(true);try{const r=await fetch(`/api/sign/${encodeURIComponent(token)}/otp/verify`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({challenge_id:challenge,code})});const j:any=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error);setSession(String(j.session_token||''));await load()}catch(e:any){setError(e.message)}finally{setBusy(false)}}
  async function saveField(id:string,payload:any){const r=await fetch(`/api/sign/${encodeURIComponent(token)}/fields/${id}`,{method:'POST',headers:{'Content-Type':'application/json','x-signing-session':session},body:JSON.stringify(payload)});const j:any=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error);await load()}
  async function complete(){setBusy(true);try{const r=await fetch(`/api/sign/${encodeURIComponent(token)}/complete`,{method:'POST',headers:{'x-signing-session':session}});const j:any=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error);setDone(true)}catch(e:any){setError(e.message)}finally{setBusy(false)}}
  async function decline(){const reason=window.prompt('Optional reason for declining:')||'';const r=await fetch(`/api/sign/${encodeURIComponent(token)}/decline`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({reason})});if(r.ok)setDone(true)}
  if(!onMailHost)return <Shell><p className="text-center text-slate-400">Opening Pinnacle Signing…</p></Shell>
  if(error&&!data)return <Shell><p className="text-center text-rose-300">{error}</p></Shell>
  if(done)return <Shell><div className="mx-auto max-w-xl text-center"><span className="mx-auto grid h-14 w-14 place-items-center rounded-full border border-emerald-400/20 bg-emerald-400/10 text-emerald-300"><CheckCircle2 size={26}/></span><p className="mt-6 text-[10px] font-bold uppercase tracking-[.18em] text-gold">Pinnacle Signing</p><h1 className="mt-3 font-display text-4xl font-semibold text-white">Your response has been recorded.</h1><p className="mt-4 text-sm leading-7 text-slate-400">You may close this window. The envelope owner can see the updated status immediately.</p></div></Shell>
  if(!data)return <Shell><p className="text-center text-slate-400">Opening secure envelope…</p></Shell>
  const authed=!!session
  return <Shell><div className="mx-auto max-w-4xl"><div className="mb-9 border-b border-white/10 pb-7"><div className="flex flex-wrap items-center gap-3"><span className="inline-flex items-center gap-2 rounded-full border border-gold/20 bg-gold/[.05] px-3 py-1.5 text-[10px] font-bold uppercase tracking-[.15em] text-gold"><LockKeyhole size={12}/> Secure Envelope</span><span className="text-xs font-semibold text-slate-600">{data.envelope.public_id}</span></div><h1 className="mt-5 max-w-3xl font-display text-4xl font-semibold tracking-[-.025em] text-white sm:text-5xl">{data.envelope.title}</h1>{data.envelope.message&&<p className="mt-4 max-w-2xl text-sm leading-7 text-slate-400">{data.envelope.message}</p>}<div className="mt-5 flex flex-wrap gap-x-6 gap-y-2 text-xs text-slate-500"><span><strong className="font-semibold text-slate-300">Signer:</strong> {data.recipient.name}</span><span>{data.recipient.email}</span></div></div>
  {!authed?<div className="mx-auto max-w-2xl rounded-2xl border border-gold/15 bg-gradient-to-br from-gold/[.055] to-transparent p-6 sm:p-8"><span className="grid h-11 w-11 place-items-center rounded-xl bg-gold/10 text-gold"><ShieldCheck size={21}/></span><h2 className="mt-5 font-display text-3xl font-semibold text-white">Verify your email before signing</h2><p className="mt-3 text-sm leading-7 text-slate-400">Pinnacle records the authentication method, timestamp, network metadata, and device/browser evidence as part of the envelope audit trail.</p>{!challenge?<button className={`${btnPrimary} mt-6 min-h-12`} onClick={requestOtp} disabled={busy}>{busy?'Sending…':'Send Verification Code'}</button>:<div className="mt-6 flex flex-col gap-3 sm:flex-row"><input className="min-h-12 rounded-xl border border-white/15 bg-white/[.035] px-4 text-white outline-none transition focus:border-gold/60 focus:ring-4 focus:ring-gold/10" value={code} onChange={e=>setCode(e.target.value)} placeholder="6-digit code" inputMode="numeric"/><button className={`${btnPrimary} min-h-12`} onClick={verify} disabled={busy||code.length<6}>{busy?'Verifying…':'Verify & Continue'}</button></div>}</div>:<><div className="space-y-4">{data.fields.map(f=><Field key={f.id} field={f} save={saveField}/>)}</div><div className="mt-9 flex flex-wrap gap-3 border-t border-white/10 pt-7"><button className={`${btnPrimary} min-h-12`} onClick={complete} disabled={busy}>{busy?'Completing…':'Complete & Submit'}</button><button className={`${btnOutline} min-h-12`} onClick={decline}>Decline</button></div></>}{error&&<p className="mt-5 text-sm text-rose-300">{error}</p>}</div></Shell>
}

function Field({field,save}:{field:any;save:(id:string,p:any)=>Promise<void>}){const [value,setValue]=useState(field.value_text||'');const label=field.label||({signature:'Signature',initial:'Initials',date:'Date',text:'Text',checkbox:'Confirmation'} as any)[field.field_type];if(field.field_type==='checkbox')return <label className="flex items-start gap-3 rounded-xl border border-white/10 bg-white/[.018] p-5"><input type="checkbox" checked={value==='true'} onChange={async e=>{setValue(e.target.checked?'true':'false');await save(field.id,{checked:e.target.checked})}} className="mt-1 h-4 w-4 accent-gold"/><span><strong className="font-bold text-white">{label}</strong>{field.required===1&&<span className="ml-1 text-gold">*</span>}<span className="mt-1 block text-xs text-slate-500">Page {field.page_number}</span></span></label>;return <label className="block rounded-xl border border-white/10 bg-white/[.018] p-5"><span className="mb-3 block text-sm font-bold text-white">{label}{field.required===1&&<span className="ml-1 text-gold">*</span>} <span className="font-normal text-slate-500">· Page {field.page_number}</span></span><div className="flex flex-col gap-2 sm:flex-row"><input className="min-h-12 min-w-0 flex-1 rounded-xl border border-white/15 bg-white/[.035] px-4 text-white outline-none transition focus:border-gold/60 focus:ring-4 focus:ring-gold/10" type={field.field_type==='date'?'date':'text'} value={value} placeholder={field.field_type==='signature'?'Type your full legal signature':field.field_type==='initial'?'Initials':''} onChange={e=>setValue(e.target.value)}/><button className="min-h-12 rounded-xl border border-gold/30 px-5 text-sm font-bold text-gold transition hover:bg-gold/10" onClick={()=>save(field.id,{value})}>Apply</button></div></label>}
function Shell({children}:{children:any}){return <div className="min-h-screen bg-navy-950 text-slate-100"><header className="border-b border-white/10 bg-navy-950/95"><div className="container-pmv flex min-h-20 items-center justify-between gap-4"><Logo/><span className="text-[10px] font-bold uppercase tracking-[.18em] text-gold">Secure Signing</span></div></header><main className="container-pmv py-10 sm:py-16">{children}</main><footer className="container-pmv border-t border-white/10 py-7 text-xs leading-6 text-slate-500">Electronic signing records include authentication and technical evidence for integrity purposes. This signing workflow is not represented as a remote online notarization unless a separate compliant RON session is expressly identified.</footer></div>}
