import { useCallback, useEffect, useMemo, useState } from 'react'
import { BookOpen, Copy, Lock, Pencil, ShieldCheck, UploadCloud } from 'lucide-react'
import { api, ApiError } from '../../lib/api'
import { DocumentCanvas } from '../../components/admin/DocumentCanvas'
import { EmptyState, PageIntro, Panel, Tag, btnPrimary, btnSecondary, inputCls } from '../../components/admin/ui'
import { toast } from '../../components/kit/toast'
import { DocumentWorkspaceNav } from '../../components/admin/DocumentWorkspaceNav'

type Doc={id:string;title:string;description:string|null;folder:string;document_type:'file'|'text';mime_type:string|null;original_name:string|null;text_content:string|null;library_scope?:string;is_editable?:number;is_branded?:number;community_category?:string|null;version_count?:number;updated_at:string}
type Detail={document:Doc;versions:any[];shares:any[]}

export default function CommunityDocuments(){
  const [docs,setDocs]=useState<Doc[]>([]),[workspace,setWorkspace]=useState<Doc[]>([]),[selected,setSelected]=useState(''),[detail,setDetail]=useState<Detail|null>(null),[q,setQ]=useState(''),[role,setRole]=useState('staff')
  const [publishId,setPublishId]=useState(''),[category,setCategory]=useState('Templates'),[editable,setEditable]=useState(false),[branded,setBranded]=useState(true),[text,setText]=useState('')
  const load=useCallback(async()=>{try{const [c,w,me]=await Promise.all([api.get<{documents:Doc[]}>('/admin/community-documents'),api.get<{documents:Doc[]}>('/admin/documents-workspace'),api.get<{user:{role:string}}>('/me').catch(()=>({user:{role:'staff'}}))]);setDocs(c.documents);setWorkspace(w.documents.filter(d=>d.library_scope!=='community'));setRole(me.user.role);if(!selected&&c.documents[0])setSelected(c.documents[0].id)}catch(e){toast.error(e instanceof ApiError?e.message:'Could not load Community Documents')}},[selected])
  useEffect(()=>{void load()},[load])
  useEffect(()=>{if(!selected){setDetail(null);return}api.get<Detail>(`/admin/documents-workspace/${selected}`).then(d=>{setDetail(d);setText(d.document.text_content||'')}).catch(()=>setDetail(null))},[selected])
  const filtered=useMemo(()=>docs.filter(d=>!q.trim()||`${d.title} ${d.community_category||''} ${d.description||''}`.toLowerCase().includes(q.toLowerCase())),[docs,q])
  async function publish(){if(!publishId)return;try{await api.post(`/admin/community-documents/${publishId}/publish`,{category,editable,branded});toast.success('Published to Community Documents');setPublishId('');await load()}catch(e){toast.error(e instanceof ApiError?e.message:'Could not publish document')}}
  async function unpublish(){if(!selected)return;try{await api.post(`/admin/community-documents/${selected}/unpublish`,{});toast.success('Removed from Community Documents');setSelected('');setDetail(null);await load()}catch(e){toast.error(e instanceof ApiError?e.message:'Could not unpublish document')}}
  async function copyToWorkspace(){if(!selected)return;try{await api.post(`/admin/community-documents/${selected}/copy`,{});toast.success('Working copy added to My Documents')}catch(e){toast.error(e instanceof ApiError?e.message:'Could not create working copy')}}
  async function saveEditable(){if(!detail||detail.document.is_editable!==1)return;try{await api.patch(`/admin/documents-workspace/${detail.document.id}`,{text_content:text,change_note:'Updated Community Document'});toast.success('Community document updated');await load()}catch(e){toast.error(e instanceof ApiError?e.message:'Could not save document')}}
  return <div>
    <DocumentWorkspaceNav />
    <PageIntro kicker="Documents" title="Community Documents" subtitle="Shared templates, reference material, procedures, and knowledge documents maintained for the Pinnacle team." />
    {role==='admin'&&<Panel className="mb-5"><div className="flex items-start gap-3"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-lg border border-gold/20 bg-gold/[.06]"><UploadCloud size={18} className="text-gold"/></div><div className="flex-1"><p className="font-semibold text-white">Publish from Document Hub</p><p className="mt-1 text-xs text-slate-500">Choose an existing document, decide whether staff may edit the shared original, and apply Pinnacle letterhead where supported.</p><div className="mt-4 grid gap-3 lg:grid-cols-[1fr_180px_auto_auto_auto]"><select className={inputCls} value={publishId} onChange={e=>setPublishId(e.target.value)}><option value="">Choose document…</option>{workspace.map(d=><option key={d.id} value={d.id}>{d.title}</option>)}</select><input className={inputCls} value={category} onChange={e=>setCategory(e.target.value)} placeholder="Category"/><label className="flex items-center gap-2 rounded-lg border border-white/10 px-3 text-xs text-slate-300"><input type="checkbox" checked={editable} onChange={e=>setEditable(e.target.checked)}/> Editable</label><label className="flex items-center gap-2 rounded-lg border border-white/10 px-3 text-xs text-slate-300"><input type="checkbox" checked={branded} onChange={e=>setBranded(e.target.checked)}/> Branded</label><button className={btnPrimary} disabled={!publishId} onClick={publish}>Publish</button></div></div></div></Panel>}
    <div className="mb-4"><input className={`${inputCls} max-w-md`} value={q} onChange={e=>setQ(e.target.value)} placeholder="Search templates and knowledge docs…"/></div>
    {selected&&detail?<div className="grid gap-4 2xl:grid-cols-[280px_minmax(0,1fr)_300px]"><Library docs={filtered} selected={selected} onSelect={setSelected}/><DocumentCanvas document={detail.document} text={text} onTextChange={setText} readOnly={detail.document.is_editable!==1}/><aside className="self-start rounded-xl border border-white/10 bg-white/[.015] p-4 2xl:sticky 2xl:top-24"><div className="flex items-start justify-between gap-3"><div><p className="text-[10px] font-semibold uppercase tracking-[.16em] text-gold/80">{detail.document.community_category||'Community'}</p><h2 className="mt-1 text-lg font-semibold text-white">{detail.document.title}</h2></div><Tag tone={detail.document.is_editable===1?'blue':'slate'}>{detail.document.is_editable===1?'editable':'read only'}</Tag></div>{detail.document.description&&<p className="mt-3 text-sm leading-6 text-slate-400">{detail.document.description}</p>}<div className="mt-5 space-y-2"><button className={`${btnPrimary} w-full`} onClick={copyToWorkspace}><Copy size={14}/> Create Working Copy</button>{detail.document.is_editable===1&&detail.document.document_type==='text'&&<button className={`${btnSecondary} w-full`} onClick={saveEditable}><Pencil size={14}/> Save Shared Original</button>}{role==='admin'&&<button className={`${btnSecondary} w-full`} onClick={unpublish}>Remove from Community</button>}</div><div className="mt-5 border-t border-white/10 pt-4 text-xs text-slate-500"><p className="flex items-center gap-2"><ShieldCheck size={13}/>{detail.document.is_branded!==0?'Pinnacle branded':'Original document styling'}</p><p className="mt-2 flex items-center gap-2">{detail.document.is_editable===1?<Pencil size={13}/>:<Lock size={13}/>} {detail.document.is_editable===1?'Shared original may be edited':'Shared original is locked'}</p><p className="mt-2">Updated {new Date(detail.document.updated_at).toLocaleDateString()}</p></div></aside></div>:<Panel className="!p-0">{filtered.length===0?<div className="p-8"><EmptyState label="No Community Documents yet. Administrators can publish documents from the workspace above."/></div>:<Library docs={filtered} selected="" onSelect={setSelected}/>}</Panel>}
  </div>
}

function Library({docs,selected,onSelect}:{docs:Doc[];selected:string;onSelect:(id:string)=>void}){return <div className="overflow-hidden rounded-xl border border-white/10 bg-white/[.015]"><div className="border-b border-white/10 px-4 py-3"><p className="flex items-center gap-2 text-xs font-semibold text-white"><BookOpen size={14} className="text-gold"/> Community Library</p><p className="mt-1 text-[11px] text-slate-500">{docs.length} shared documents</p></div><div className="max-h-[calc(100vh-260px)] overflow-y-auto">{docs.map(d=><button key={d.id} onClick={()=>onSelect(d.id)} className={`w-full border-b border-white/5 px-4 py-3 text-left last:border-0 ${selected===d.id?'bg-gold/[.07]':'hover:bg-white/[.025]'}`}><div className="flex items-start justify-between gap-2"><div className="min-w-0"><p className="truncate text-sm font-medium text-white">{d.title}</p><p className="mt-1 truncate text-[11px] text-slate-500">{d.community_category||'General'} · {d.document_type==='text'?'Knowledge doc':d.original_name||'Template'}</p></div>{d.is_editable===1?<Pencil size={12} className="mt-1 shrink-0 text-slate-500"/>:<Lock size={12} className="mt-1 shrink-0 text-slate-600"/>}</div></button>)}</div></div>}
