import { useCallback, useEffect, useState } from 'react'
import { Clock3, Play, RefreshCw, ShieldCheck } from 'lucide-react'
import { api, ApiError } from '../../lib/api'
import { Panel, Tag, btnPrimary, btnOutline } from '../../components/admin/ui'
import { toast } from '../../components/kit/toast'

type Rule={id:string;name:string;rule_type:string;enabled:number;config_json:string}
type Run={id:string;status:string;trigger_type:string;items_processed:number;items_succeeded:number;items_failed:number;started_at:string;finished_at?:string|null;detail_json?:string|null}
const tone=(s:string):'green'|'gold'|'red'|'blue'|'slate'=>s==='success'?'green':s==='partial'?'gold':s==='failed'?'red':s==='running'?'blue':'slate'

export default function DocumentAutomationPanel(){
 const [rules,setRules]=useState<Rule[]>([]),[runs,setRuns]=useState<Run[]>([]),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true)
 const load=useCallback(async()=>{try{const r=await api.get<{rules:Rule[];runs:Run[]}>('/admin/document-platform/automation');setRules(r.rules||[]);setRuns(r.runs||[])}catch(e){toast.error(e instanceof ApiError?e.message:'Could not load document automation')}finally{setLoading(false)}},[])
 useEffect(()=>{void load()},[load])
 async function run(){setBusy(true);try{const r=await api.post<any>('/admin/document-platform/automation/run',{});toast.success(`Document automation processed ${r.processed||0} item${r.processed===1?'':'s'}`);await load()}catch(e){toast.error(e instanceof ApiError?e.message:'Could not run document automation')}finally{setBusy(false)}}
 async function toggle(rule:Rule){try{await api.patch(`/admin/document-platform/automation/rules/${rule.id}`,{enabled:!Number(rule.enabled)});await load()}catch(e){toast.error(e instanceof ApiError?e.message:'Could not update rule')}}
 if(loading)return <Panel className="mb-6"><p className="text-sm text-slate-400">Loading document lifecycle automation…</p></Panel>
 const last=runs[0]||null
 return <Panel className="mb-6 border-gold/20 bg-gradient-to-br from-gold/[.045] via-transparent to-transparent"><div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div><div className="flex items-center gap-2"><ShieldCheck size={17} className="text-gold"/><p className="text-sm font-extrabold text-white">E-Signature Lifecycle Automation</p></div><p className="mt-1 max-w-3xl text-xs leading-5 text-slate-500">Self-hosted reminder, expiration, and retention enforcement runs every 10 minutes and respects envelope routing, revoked access, and legal holds.</p></div><div className="flex flex-wrap gap-2"><button className={btnPrimary} disabled={busy} onClick={run}><Play size={14}/>{busy?'Running…':'Run Now'}</button><button className={btnOutline} onClick={()=>void load()}><RefreshCw size={14}/>Refresh</button></div></div><div className="mt-5 grid gap-3 md:grid-cols-3">{rules.map(rule=><button key={rule.id} onClick={()=>void toggle(rule)} className={`min-h-24 rounded-xl border p-4 text-left transition ${Number(rule.enabled)?'border-gold/25 bg-gold/[.04]':'border-white/10 bg-white/[.015]'}`}><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-bold text-white">{rule.name}</p><p className="mt-1 text-[10px] font-bold uppercase tracking-[.13em] text-slate-500">{rule.rule_type}</p></div><Tag tone={Number(rule.enabled)?'green':'slate'}>{Number(rule.enabled)?'Enabled':'Disabled'}</Tag></div></button>)}</div>{last&&<div className="mt-5 grid gap-3 border-t border-white/10 pt-5 sm:grid-cols-2 xl:grid-cols-5"><Metric label="Last run" value={new Date(last.started_at).toLocaleString()} icon={<Clock3 size={14}/>}/><Metric label="Status" value={last.status}/><Metric label="Processed" value={String(last.items_processed||0)}/><Metric label="Succeeded" value={String(last.items_succeeded||0)}/><Metric label="Failed" value={String(last.items_failed||0)} danger={Number(last.items_failed)>0}/></div>}</Panel>
}
function Metric({label,value,icon,danger=false}:{label:string;value:string;icon?:any;danger?:boolean}){return <div className="rounded-xl border border-white/10 p-3"><p className="flex items-center gap-1.5 text-[10px] font-bold uppercase tracking-[.12em] text-slate-500">{icon}{label}</p><p className={`mt-1 text-sm font-bold ${danger?'text-rose-300':'text-white'}`}>{value}</p></div>}
