import { useCallback, useEffect, useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { api, ApiError } from '../../lib/api'
import { useAppPath } from '../../lib/basePath'
import { PageIntro, Panel, EmptyState, Tag, inputCls, btnPrimary } from '../../components/admin/ui'
import { toast } from '../../components/kit/toast'

interface ClientDoc { id:string; client_user_id:string; client_name:string; category:string|null; file_name:string|null; review_status:string; visibility:string; content_type:string|null; size_bytes:number|null; source:string|null; created_at:string }
interface ReportExport { id:string; report_key:string; report_label:string; file_name:string; content_type:string; size_bytes:number|null; created_at:string; created_by_name:string|null; created_by_email:string|null }
interface CatalogEntry { key:string; label:string; category:string; description:string }
function size(bytes:number|null){ if(!bytes)return '—'; if(bytes<1024*1024)return `${Math.max(1,Math.round(bytes/1024))} KB`; return `${(bytes/1024/1024).toFixed(1)} MB` }
function today(offset=0){ return new Date(Date.now()+offset*86400000).toISOString().slice(0,10) }

export default function DocumentCenter(){
  const p=useAppPath(); const [docs,setDocs]=useState<ClientDoc[]>([]); const [exports,setExports]=useState<ReportExport[]>([]); const [catalog,setCatalog]=useState<CatalogEntry[]>([]); const [loading,setLoading]=useState(true); const [tab,setTab]=useState<'client'|'reports'>('client'); const [q,setQ]=useState(''); const [reportKey,setReportKey]=useState(''); const [from,setFrom]=useState(today(-30)); const [to,setTo]=useState(today()); const [generating,setGenerating]=useState(false)
  const load=useCallback(async()=>{setLoading(true);try{const [center,reports]=await Promise.all([api.get<{documents:ClientDoc[];report_exports:ReportExport[]}>('/admin/document-center'),api.get<{reports:CatalogEntry[]}>('/admin/reports/catalog').catch(()=>({reports:[]}))]);setDocs(center.documents);setExports(center.report_exports);setCatalog(reports.reports);if(!reportKey&&reports.reports[0])setReportKey(reports.reports[0].key)}catch(e){toast.error(e instanceof ApiError?e.message:'Could not load Document Center.')}finally{setLoading(false)}},[reportKey])
  useEffect(()=>{load()},[load])
  const clientRows=useMemo(()=>docs.filter(d=>!q.trim()||`${d.client_name} ${d.file_name||''} ${d.category||''}`.toLowerCase().includes(q.toLowerCase())),[docs,q])
  const reportRows=useMemo(()=>exports.filter(r=>!q.trim()||`${r.report_label} ${r.file_name}`.toLowerCase().includes(q.toLowerCase())),[exports,q])
  async function generate(){if(!reportKey)return;setGenerating(true);try{const r=await api.post<{export:{id:string;file_name:string}}>(`/admin/reports/${reportKey}/export.pdf?from=${encodeURIComponent(from)}&to=${encodeURIComponent(to)}`,{});toast.success(`${r.export.file_name} created.`);setTab('reports');await load()}catch(e){toast.error(e instanceof ApiError?e.message:'Could not generate report PDF.')}finally{setGenerating(false)}}
  return <div>
    <PageIntro kicker="Documents" title="Document Center" subtitle="One place for generated applications, client documents, and branded report exports. Open the client record from here when a file needs follow-up." />
    <Panel className="mb-6"><div className="flex flex-col gap-4 xl:flex-row xl:items-end"><div className="flex-1"><p className="eyebrow">Create a report PDF</p><h2 className="mt-1 text-base font-semibold text-white">Generate a branded report and keep it in HQ</h2><p className="mt-1 text-xs text-slate-500">The PDF is stored in the Report Exports library instead of relying on a browser print dialog.</p></div><label className="xl:min-w-[260px]"><span className="mb-1 block text-xs text-slate-400">Report</span><select className={inputCls} value={reportKey} onChange={e=>setReportKey(e.target.value)}><option value="">Choose report…</option>{catalog.map(r=><option key={r.key} value={r.key}>{r.label}</option>)}</select></label><label><span className="mb-1 block text-xs text-slate-400">From</span><input className={inputCls} type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label><span className="mb-1 block text-xs text-slate-400">To</span><input className={inputCls} type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><button className={btnPrimary} disabled={!reportKey||generating} onClick={generate}>{generating?'Generating…':'Generate branded PDF'}</button></div></Panel>
    <div className="mb-5 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div className="flex gap-2"><button onClick={()=>setTab('client')} className={`rounded-full border px-3 py-1.5 text-xs ${tab==='client'?'border-gold/40 bg-gold/10 text-gold':'border-white/10 text-slate-400'}`}>Client documents ({docs.length})</button><button onClick={()=>setTab('reports')} className={`rounded-full border px-3 py-1.5 text-xs ${tab==='reports'?'border-gold/40 bg-gold/10 text-gold':'border-white/10 text-slate-400'}`}>Report exports ({exports.length})</button></div><input className={`${inputCls} sm:max-w-xs`} placeholder="Search files or clients…" value={q} onChange={e=>setQ(e.target.value)}/></div>
    <Panel className="!p-0 overflow-x-auto">{loading?<p className="p-6 text-sm text-slate-400">Loading…</p>:tab==='client'?(clientRows.length===0?<div className="p-6"><EmptyState label="No client documents match this view."/></div>:<table className="w-full min-w-[900px] text-left text-sm"><thead><tr className="border-b border-white/10 text-xs uppercase tracking-wide text-slate-500"><th className="px-5 py-3 font-medium">File</th><th className="px-5 py-3 font-medium">Client</th><th className="px-5 py-3 font-medium">Category</th><th className="px-5 py-3 font-medium">Visibility</th><th className="px-5 py-3 font-medium">Size</th><th className="px-5 py-3 font-medium">Created</th></tr></thead><tbody>{clientRows.map(d=><tr key={d.id} className="border-b border-white/5 last:border-0"><td className="px-5 py-3"><a className="font-medium text-gold hover:underline" href={`/api/portal/documents/${d.id}/file`} target="_blank" rel="noreferrer">{d.file_name||'Open document'}</a><p className="mt-1 text-xs text-slate-500">{d.source||d.content_type||''}</p></td><td className="px-5 py-3"><Link className="text-slate-200 hover:text-gold" to={p(`clients/${d.client_user_id}`)}>{d.client_name}</Link></td><td className="px-5 py-3 text-slate-400">{(d.category||'other').replace(/_/g,' ')}</td><td className="px-5 py-3"><Tag tone={d.visibility==='internal'?'red':'green'}>{d.visibility==='internal'?'Pinnacle only':'Client visible'}</Tag></td><td className="px-5 py-3 text-slate-400">{size(d.size_bytes)}</td><td className="px-5 py-3 text-slate-400">{new Date(d.created_at).toLocaleString()}</td></tr>)}</tbody></table>):(reportRows.length===0?<div className="p-6"><EmptyState label="No report PDFs have been generated yet."/></div>:<table className="w-full min-w-[760px] text-left text-sm"><thead><tr className="border-b border-white/10 text-xs uppercase tracking-wide text-slate-500"><th className="px-5 py-3 font-medium">Report</th><th className="px-5 py-3 font-medium">Generated by</th><th className="px-5 py-3 font-medium">Size</th><th className="px-5 py-3 font-medium">Generated</th></tr></thead><tbody>{reportRows.map(r=><tr key={r.id} className="border-b border-white/5 last:border-0"><td className="px-5 py-3"><a className="font-medium text-gold hover:underline" href={`/api/admin/report-exports/${r.id}/file`} target="_blank" rel="noreferrer">{r.file_name}</a><p className="mt-1 text-xs text-slate-500">{r.report_label}</p></td><td className="px-5 py-3 text-slate-400">{r.created_by_name||r.created_by_email||'Pinnacle'}</td><td className="px-5 py-3 text-slate-400">{size(r.size_bytes)}</td><td className="px-5 py-3 text-slate-400">{new Date(r.created_at).toLocaleString()}</td></tr>)}</tbody></table>)}</Panel>
  </div>
}
