import { useCallback, useEffect, useMemo, useState } from 'react'
import { Archive, Check, CopyPlus, FileDiff, Files, Gavel, Layers3, RefreshCw, Repeat2, ShieldOff, Sparkles, UsersRound, Workflow } from 'lucide-react'
import { api, ApiError } from '../../lib/api'
import { PageIntro, Panel, Tag, inputCls, btnPrimary, btnSecondary } from '../../components/admin/ui'
import { toast } from '../../components/kit/toast'
import EnvelopeWorkspace from './EnvelopeWorkspace'

type Envelope={id:string;public_id:string;title:string;status:string;created_at:string;priority?:string}
type Detail={envelope:any;recipients:any[];fields:any[];events:any[];seal?:any}
type Template={id:string;name:string;description?:string|null;status:string;version_number:number;version_count:number;updated_at:string}
type PacketDoc={id:string;title:string;sort_order:number;required:number;original_name?:string;mime_type?:string}
type Retention={policies:any[];holds:any[];assignments:any[]}
type Mode='templates'|'packet'|'bulk'|'retention'

const fmt=(s:string)=>s.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase())

export default function EnvelopeWorkspaceEnterprise(){
  const [rows,setRows]=useState<Envelope[]>([]),[selected,setSelected]=useState(''),[detail,setDetail]=useState<Detail|null>(null),[templates,setTemplates]=useState<Template[]>([]),[packet,setPacket]=useState<PacketDoc[]>([]),[retention,setRetention]=useState<Retention>({policies:[],holds:[],assignments:[]})
  const [mode,setMode]=useState<Mode>('templates'),[busy,setBusy]=useState(''),[templateName,setTemplateName]=useState(''),[templateDescription,setTemplateDescription]=useState(''),[packetFile,setPacketFile]=useState<File|null>(null),[packetTitle,setPacketTitle]=useState('')
  const [replacement,setReplacement]=useState<Record<string,{name:string;email:string;reason:string}>>({}),[ruleDraft,setRuleDraft]=useState<Record<string,{format:string;pattern:string;minLength:string;error:string}>>({})
  const [bulkIds,setBulkIds]=useState<string[]>([]),[bulkOperation,setBulkOperation]=useState('remind'),[bulkReason,setBulkReason]=useState('')
  const [policyName,setPolicyName]=useState(''),[policyDays,setPolicyDays]=useState('2555'),[holdName,setHoldName]=useState(''),[holdReason,setHoldReason]=useState(''),[holdScope,setHoldScope]=useState<'envelope'|'document'|'client'|'global'>('envelope')
  const [compareTemplate,setCompareTemplate]=useState(''),[leftVersion,setLeftVersion]=useState('1'),[rightVersion,setRightVersion]=useState('2'),[comparison,setComparison]=useState<any>(null)
  const [serviceWarnings,setServiceWarnings]=useState<string[]>([])

  const loadBase=useCallback(async()=>{const results=await Promise.allSettled([api.get<{envelopes:Envelope[]}>('/admin/envelopes'),api.get<{templates:Template[]}>('/admin/document-platform/templates'),api.get<Retention>('/admin/document-platform/retention')]);const warnings:string[]=[];const[e,t,r]=results;if(e.status==='fulfilled'){setRows(e.value.envelopes);setSelected(v=>v||e.value.envelopes[0]?.id||'')}else warnings.push('Envelope records');if(t.status==='fulfilled')setTemplates(t.value.templates);else warnings.push('Template library');if(r.status==='fulfilled')setRetention(r.value);else warnings.push('Retention controls');setServiceWarnings(warnings)},[])
  const loadSelected=useCallback(async()=>{if(!selected){setDetail(null);setPacket([]);return}const results=await Promise.allSettled([api.get<Detail>(`/admin/envelopes/${selected}`),api.get<{documents:PacketDoc[]}>(`/admin/document-platform/envelopes/${selected}/documents`)]);const[d,p]=results;if(d.status==='fulfilled'){setDetail(d.value);const rules:Record<string,{format:string;pattern:string;minLength:string;error:string}>={};for(const f of d.value.fields){let v:any={};try{v=JSON.parse(f.validation_json||'{}')}catch{}rules[f.id]={format:v.format||'',pattern:v.pattern||'',minLength:v.minLength?String(v.minLength):'',error:f.validation_error_message||''}}setRuleDraft(rules)}else toast.error(d.reason instanceof ApiError?d.reason.message:'Could not load this envelope.');if(p.status==='fulfilled')setPacket(p.value.documents);else setServiceWarnings(v=>[...new Set([...v,'Packet documents'])])},[selected])
  useEffect(()=>{void loadBase()},[loadBase]);useEffect(()=>{void loadSelected()},[loadSelected])
  const selectedEnvelope=useMemo(()=>rows.find(r=>r.id===selected)||null,[rows,selected])
  const activeHolds=retention.holds.filter(h=>h.status==='active')

  async function saveAsTemplate(){if(!selected||!templateName.trim())return;setBusy('template');try{await api.post(`/admin/document-platform/templates/from-envelope/${selected}`,{name:templateName.trim(),description:templateDescription.trim(),expiration_days:14});setTemplateName('');setTemplateDescription('');toast.success('Reusable envelope template created');await loadBase()}catch(err){toast.error(err instanceof ApiError?err.message:'Could not create template')}finally{setBusy('')}}
  async function useTemplate(id:string){setBusy(`use-${id}`);try{const r=await api.post<{id:string}>(`/admin/document-platform/templates/${id}/use`,{});setSelected(r.id);toast.success('New customizable draft created from template');await loadBase()}catch(err){toast.error(err instanceof ApiError?err.message:'Could not use template')}finally{setBusy('')}}
  async function compareVersions(){if(!compareTemplate)return;setBusy('compare');try{const r=await api.get<any>(`/admin/document-platform/templates/${compareTemplate}/compare?left=${encodeURIComponent(leftVersion)}&right=${encodeURIComponent(rightVersion)}`);setComparison(r.summary)}catch(err){toast.error(err instanceof ApiError?err.message:'Could not compare versions')}finally{setBusy('')}}
  async function addPacketDocument(){if(!selected||!packetFile)return;setBusy('packet');try{const up=await api.upload<{file:{id:string}} >('/admin/documents/upload',packetFile);await api.post(`/admin/document-platform/envelopes/${selected}/documents`,{document_file_id:up.file.id,title:packetTitle.trim()||packetFile.name,required:true});setPacketFile(null);setPacketTitle('');toast.success('Document added to packet');await loadSelected()}catch(err){toast.error(err instanceof ApiError?err.message:'Could not add packet document')}finally{setBusy('')}}
  async function reorder(doc:PacketDoc,direction:-1|1){const index=packet.findIndex(d=>d.id===doc.id),next=index+direction;if(next<0||next>=packet.length)return;const ids=packet.map(d=>d.id);[ids[index],ids[next]]=[ids[next],ids[index]];try{await api.patch(`/admin/document-platform/envelopes/${selected}/documents/order`,{ids});await loadSelected()}catch(err){toast.error(err instanceof ApiError?err.message:'Could not reorder packet')}}
  async function removePacket(id:string){if(!confirm('Remove this document from the draft packet?'))return;const r=await fetch(`/api/admin/document-platform/envelopes/${selected}/documents/${id}`,{method:'DELETE',credentials:'include'});const j:any=await r.json().catch(()=>({}));if(!r.ok){toast.error(j.error||'Could not remove document');return}await loadSelected()}
  async function replaceRecipient(r:any){const draft=replacement[r.id];if(!draft?.name.trim()||!draft?.email.trim()||draft.reason.trim().length<5)return;setBusy(`replace-${r.id}`);try{await api.post(`/admin/document-platform/envelopes/${selected}/recipients/${r.id}/replace`,draft);toast.success('Recipient securely replaced and access rotated');setReplacement(v=>({...v,[r.id]:{name:'',email:'',reason:''}}));await loadSelected()}catch(err){toast.error(err instanceof ApiError?err.message:'Could not replace recipient')}finally{setBusy('')}}
  async function revokeRecipient(r:any){const reason=prompt(`Reason for revoking ${r.name}'s access:`)||'';if(reason.trim().length<5)return;setBusy(`revoke-${r.id}`);try{await api.post(`/admin/document-platform/envelopes/${selected}/recipients/${r.id}/revoke`,{reason});toast.success('Recipient access revoked');await loadSelected()}catch(err){toast.error(err instanceof ApiError?err.message:'Could not revoke access')}finally{setBusy('')}}
  async function saveFieldRule(f:any){const d=ruleDraft[f.id]||{format:'',pattern:'',minLength:'',error:''},validation:any={};if(d.format)validation.format=d.format;if(d.pattern)validation.pattern=d.pattern;if(d.minLength)validation.minLength=Number(d.minLength);setBusy(`rule-${f.id}`);try{await api.patch(`/admin/document-platform/envelopes/${selected}/fields/${f.id}/rules`,{required:!!f.required,label:f.label,validation,error_message:d.error});toast.success('Signing validation rule saved');await loadSelected()}catch(err){toast.error(err instanceof ApiError?err.message:'Could not save field rule')}finally{setBusy('')}}
  async function runBulk(){if(!bulkIds.length)return;setBusy('bulk');try{const r=await api.post<any>('/admin/document-platform/envelopes/bulk',{envelope_ids:bulkIds,operation:bulkOperation,reason:bulkReason,status:bulkOperation==='status'?'voided':undefined});if(bulkOperation==='download'){for(const item of r.results||[]){if(item.links?.signed)window.open(item.links.signed,'_blank','noopener,noreferrer')}}toast.success(`${r.succeeded} envelope${r.succeeded===1?'':'s'} processed`);if(r.failed)toast.error(`${r.failed} envelope${r.failed===1?'':'s'} could not be processed`);await loadBase()}catch(err){toast.error(err instanceof ApiError?err.message:'Bulk operation failed')}finally{setBusy('')}}
  async function createPolicy(){if(!policyName.trim())return;setBusy('policy');try{await api.post('/admin/document-platform/retention/policies',{name:policyName,retention_days:Number(policyDays)||null,description:'PMV document retention policy',active:true});setPolicyName('');toast.success('Retention policy created');await loadBase()}catch(err){toast.error(err instanceof ApiError?err.message:'Could not create policy')}finally{setBusy('')}}
  async function assignPolicy(policyId:string){if(!selected)return;try{await api.post('/admin/document-platform/retention/assign',{policy_id:policyId,scope_type:'envelope',scope_id:selected});toast.success('Retention policy assigned to envelope');await loadBase()}catch(err){toast.error(err instanceof ApiError?err.message:'Could not assign policy')}}
  async function createHold(){if(!holdName.trim()||holdReason.trim().length<5)return;setBusy('hold');try{await api.post('/admin/document-platform/retention/holds',{scope_type:holdScope,scope_id:holdScope==='global'?null:selected,name:holdName,reason:holdReason});setHoldName('');setHoldReason('');toast.success('Legal hold activated');await loadBase()}catch(err){toast.error(err instanceof ApiError?err.message:'Could not create legal hold')}finally{setBusy('')}}
  async function releaseHold(id:string){try{await api.post(`/admin/document-platform/retention/holds/${id}/release`,{});toast.success('Legal hold released');await loadBase()}catch(err){toast.error(err instanceof ApiError?err.message:'Could not release hold')}}

  return <div className="space-y-6">
    <PageIntro kicker="PMV Document Platform" title="Enterprise Envelope Workspace" subtitle="Reusable templates, multi-document packets, controlled recipient access, field rules, bulk processing, retention, legal holds, and evidentiary controls in one self-hosted workspace." />
    {serviceWarnings.length>0&&<div role="alert" className="flex flex-col gap-3 rounded-xl border border-amber-300/20 bg-amber-300/[.04] p-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm font-semibold text-amber-100">Part of the document workspace is temporarily unavailable</p><p className="mt-1 text-xs text-slate-400">Unavailable: {serviceWarnings.join(', ')}. The sections that loaded remain usable.</p></div><button className={btnSecondary} onClick={()=>void loadBase()}><RefreshCw size={14}/>Retry unavailable services</button></div>}

    <Panel className="!p-0 overflow-hidden border-gold/20 bg-gradient-to-br from-gold/[.055] via-white/[.015] to-transparent">
      <div className="grid gap-px bg-white/[.06] sm:grid-cols-2 xl:grid-cols-4">{[
        {id:'templates',label:'Templates',icon:CopyPlus,sub:`${templates.length} reusable`},{id:'packet',label:'Packet & Access',icon:Layers3,sub:selectedEnvelope?selectedEnvelope.public_id:'Select envelope'},{id:'bulk',label:'Bulk Operations',icon:Workflow,sub:`${bulkIds.length} selected`},{id:'retention',label:'Retention & Holds',icon:Gavel,sub:`${activeHolds.length} active holds`},
      ].map((item:any)=><button key={item.id} onClick={()=>setMode(item.id)} className={`bg-navy-950/80 p-4 text-left transition ${mode===item.id?'ring-1 ring-inset ring-gold/35':'hover:bg-white/[.03]'}`}><div className="flex items-center gap-2"><item.icon size={16} className={mode===item.id?'text-gold':'text-slate-500'}/><span className="text-xs font-extrabold text-white">{item.label}</span></div><p className="mt-1 text-[11px] text-slate-500">{item.sub}</p></button>)}</div>
      <div className="border-t border-white/10 p-4 sm:p-5"><div className="flex flex-col gap-3 lg:flex-row lg:items-end"><label className="min-w-0 flex-1"><span className="mb-1.5 block text-[10px] font-bold uppercase tracking-[.14em] text-slate-500">Working envelope</span><select className={inputCls} value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Select envelope</option>{rows.map(e=><option key={e.id} value={e.id}>{e.title} · {e.public_id} · {fmt(e.status)}</option>)}</select></label><button className={btnSecondary} onClick={()=>void Promise.all([loadBase(),loadSelected()])}><RefreshCw size={14}/>Refresh</button></div></div>
    </Panel>

    {mode==='templates'&&<div className="grid gap-5 xl:grid-cols-[.8fr_1.2fr]">
      <Panel><div className="flex items-center gap-2"><Sparkles size={16} className="text-gold"/><h2 className="text-sm font-extrabold text-white">Save complete envelope as template</h2></div><p className="mt-2 text-xs leading-5 text-slate-500">Captures recipients, routing, packet documents, fields, validation, settings, branding references, reminders, priority, and approval defaults.</p><div className="mt-4 space-y-3"><input className={inputCls} value={templateName} onChange={e=>setTemplateName(e.target.value)} placeholder="Template name"/><textarea className={`${inputCls} min-h-24`} value={templateDescription} onChange={e=>setTemplateDescription(e.target.value)} placeholder="Internal description"/><button className={btnPrimary} disabled={!selected||!templateName.trim()||busy==='template'} onClick={saveAsTemplate}>{busy==='template'?'Saving…':'Save Reusable Template'}</button></div></Panel>
      <Panel><div className="flex items-center justify-between"><div><p className="text-sm font-extrabold text-white">Template library</p><p className="mt-1 text-xs text-slate-500">Create a new customizable draft without rebuilding routing or fields.</p></div><Tag>{templates.length}</Tag></div><div className="mt-4 grid gap-3 md:grid-cols-2">{templates.map(t=><div key={t.id} className="rounded-xl border border-white/10 bg-white/[.018] p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-bold text-white">{t.name}</p><p className="mt-1 text-xs text-slate-500">v{t.version_number} · {t.version_count} snapshots</p></div><Tag tone={t.status==='active'?'green':'slate'}>{t.status}</Tag></div>{t.description&&<p className="mt-3 text-xs leading-5 text-slate-400">{t.description}</p>}<button className={`${btnSecondary} mt-4`} disabled={busy===`use-${t.id}`} onClick={()=>useTemplate(t.id)}>Use Template</button></div>)}</div>{templates.length>0&&<div className="mt-5 border-t border-white/10 pt-5"><div className="mb-3 flex items-center gap-2"><FileDiff size={15} className="text-gold"/><p className="text-xs font-extrabold text-white">Template version comparison</p></div><div className="grid gap-2 sm:grid-cols-[1fr_90px_90px_auto]"><select className={inputCls} value={compareTemplate} onChange={e=>setCompareTemplate(e.target.value)}><option value="">Choose template</option>{templates.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select><input className={inputCls} value={leftVersion} onChange={e=>setLeftVersion(e.target.value)} inputMode="numeric" placeholder="Left"/><input className={inputCls} value={rightVersion} onChange={e=>setRightVersion(e.target.value)} inputMode="numeric" placeholder="Right"/><button className={btnSecondary} onClick={compareVersions}>Compare</button></div>{comparison&&<div className="mt-3 rounded-lg border border-white/10 bg-black/10 p-3 text-xs text-slate-400"><p>{comparison.changed_lines} changed · {comparison.added_lines} added · {comparison.removed_lines} removed</p>{comparison.samples?.slice(0,5).map((s:string,i:number)=><p key={i} className="mt-1 break-words text-[11px] text-slate-500">{s}</p>)}</div>}</div>}</Panel>
    </div>}

    {mode==='packet'&&<div className="grid gap-5 xl:grid-cols-2">
      <Panel><div className="flex items-center justify-between"><div><p className="text-sm font-extrabold text-white">Multi-document packet</p><p className="mt-1 text-xs text-slate-500">Ordered documents share the same envelope, recipients, audit chain, and final evidence package.</p></div><Files size={18} className="text-gold"/></div><div className="mt-4 grid gap-2 sm:grid-cols-[1fr_1fr_auto]"><input className={inputCls} value={packetTitle} onChange={e=>setPacketTitle(e.target.value)} placeholder="Document title"/><input className={inputCls} type="file" accept="application/pdf,.pdf" onChange={e=>setPacketFile(e.target.files?.[0]||null)}/><button className={btnPrimary} disabled={!selected||!packetFile||busy==='packet'} onClick={addPacketDocument}>Add</button></div><div className="mt-4 space-y-2">{packet.map((d,i)=><div key={d.id} className="flex flex-col gap-3 rounded-xl border border-white/10 p-3 sm:flex-row sm:items-center sm:justify-between"><div className="min-w-0"><p className="truncate text-sm font-bold text-white">{i+1}. {d.title}</p><p className="mt-1 truncate text-[11px] text-slate-500">{d.original_name||'PDF'} · {d.required?'Required':'Optional'}</p></div><div className="flex gap-2"><button className={btnSecondary} disabled={i===0} onClick={()=>reorder(d,-1)}>↑</button><button className={btnSecondary} disabled={i===packet.length-1} onClick={()=>reorder(d,1)}>↓</button><button className={btnSecondary} onClick={()=>removePacket(d.id)}>Remove</button></div></div>)}</div></Panel>
      <Panel><div className="flex items-center gap-2"><UsersRound size={16} className="text-gold"/><h2 className="text-sm font-extrabold text-white">Post-send recipient control</h2></div><p className="mt-2 text-xs leading-5 text-slate-500">Replacement immediately revokes the prior link, transfers assigned fields, records the reason, notifies the original party, and securely invites the replacement when appropriate.</p><div className="mt-4 space-y-3">{detail?.recipients.map(r=>{const d=replacement[r.id]||{name:'',email:'',reason:''};return <div key={r.id} className="rounded-xl border border-white/10 p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-bold text-white">{r.name}</p><p className="text-[11px] text-slate-500">{r.email} · {r.role} · {fmt(r.status)}</p></div>{r.access_revoked_at?<Tag tone="red">Revoked</Tag>:<Tag>Active access</Tag>}</div>{selectedEnvelope&&['sent','viewed','in_progress'].includes(selectedEnvelope.status)&&r.status!=='completed'&&<div className="mt-3 grid gap-2 sm:grid-cols-2"><input className={inputCls} value={d.name} onChange={e=>setReplacement(v=>({...v,[r.id]:{...d,name:e.target.value}}))} placeholder="Replacement name"/><input className={inputCls} value={d.email} onChange={e=>setReplacement(v=>({...v,[r.id]:{...d,email:e.target.value}}))} placeholder="Replacement email"/><input className={`${inputCls} sm:col-span-2`} value={d.reason} onChange={e=>setReplacement(v=>({...v,[r.id]:{...d,reason:e.target.value}}))} placeholder="Required replacement reason"/><div className="flex flex-wrap gap-2 sm:col-span-2"><button className={btnPrimary} disabled={busy===`replace-${r.id}`} onClick={()=>replaceRecipient(r)}><Repeat2 size={14}/>Replace Securely</button><button className={btnSecondary} disabled={busy===`revoke-${r.id}`} onClick={()=>revokeRecipient(r)}><ShieldOff size={14}/>Revoke Access</button></div></div>}</div>})}</div></Panel>
      <Panel className="xl:col-span-2"><div className="flex items-center gap-2"><Check size={16} className="text-gold"/><h2 className="text-sm font-extrabold text-white">Field validation rules</h2></div><div className="mt-4 grid gap-3 lg:grid-cols-2">{detail?.fields.map(f=>{const d=ruleDraft[f.id]||{format:'',pattern:'',minLength:'',error:''};const recipient=detail.recipients.find(r=>r.id===f.recipient_id);return <div key={f.id} className="rounded-xl border border-white/10 p-4"><p className="text-sm font-bold text-white">{f.label||fmt(f.field_type)}</p><p className="mt-1 text-[11px] text-slate-500">{recipient?.name||'Recipient'} · Page {f.page_number}</p><div className="mt-3 grid gap-2 sm:grid-cols-2"><select className={inputCls} value={f.envelope_document_id||''} onChange={async e=>{try{await api.patch(`/admin/document-platform/envelopes/${selected}/fields/${f.id}/rules`,{envelope_document_id:e.target.value||null});await loadSelected()}catch(err){toast.error(err instanceof ApiError?err.message:'Could not assign field document')}}}><option value="">Primary document</option>{packet.map(doc=><option key={doc.id} value={doc.id}>{doc.title}</option>)}</select><select className={inputCls} value={d.format} onChange={e=>setRuleDraft(v=>({...v,[f.id]:{...d,format:e.target.value}}))}><option value="">No preset format</option><option value="email">Email</option><option value="phone">Phone</option><option value="number">Number</option></select><input className={inputCls} value={d.minLength} onChange={e=>setRuleDraft(v=>({...v,[f.id]:{...d,minLength:e.target.value}}))} placeholder="Min length" inputMode="numeric"/><input className={`${inputCls} sm:col-span-2`} value={d.pattern} onChange={e=>setRuleDraft(v=>({...v,[f.id]:{...d,pattern:e.target.value}}))} placeholder="Custom regex pattern (optional)"/><input className={`${inputCls} sm:col-span-2`} value={d.error} onChange={e=>setRuleDraft(v=>({...v,[f.id]:{...d,error:e.target.value}}))} placeholder="Custom validation message"/><button className={btnSecondary} disabled={busy===`rule-${f.id}`} onClick={()=>saveFieldRule(f)}>Save Rule</button></div></div>})}</div></Panel>
    </div>}

    {mode==='bulk'&&<Panel><div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div><p className="text-sm font-extrabold text-white">Bulk envelope operations</p><p className="mt-1 text-xs text-slate-500">Run controlled send, remind, void, archive, evidence-download, and supported status actions across selected envelopes.</p></div><Tag tone="blue">{bulkIds.length} selected</Tag></div><div className="mt-4 grid gap-2 sm:grid-cols-[180px_1fr_auto]"><select className={inputCls} value={bulkOperation} onChange={e=>setBulkOperation(e.target.value)}><option value="send">Send drafts</option><option value="remind">Send reminders</option><option value="void">Void</option><option value="archive">Archive marker</option><option value="download">Open evidence downloads</option><option value="status">Status: voided</option></select><input className={inputCls} value={bulkReason} onChange={e=>setBulkReason(e.target.value)} placeholder="Reason / note for controlled operation"/><button className={btnPrimary} disabled={!bulkIds.length||busy==='bulk'} onClick={runBulk}>{busy==='bulk'?'Processing…':'Run Operation'}</button></div><div className="mt-5 grid gap-2 md:grid-cols-2 xl:grid-cols-3">{rows.map(e=><label key={e.id} className={`flex cursor-pointer items-start gap-3 rounded-xl border p-3 ${bulkIds.includes(e.id)?'border-gold/35 bg-gold/[.04]':'border-white/10'}`}><input type="checkbox" className="mt-1" checked={bulkIds.includes(e.id)} onChange={ev=>setBulkIds(v=>ev.target.checked?[...v,e.id]:v.filter(id=>id!==e.id))}/><span className="min-w-0"><span className="block truncate text-sm font-bold text-white">{e.title}</span><span className="mt-1 block text-[11px] text-slate-500">{e.public_id} · {fmt(e.status)}</span></span></label>)}</div></Panel>}

    {mode==='retention'&&<div className="grid gap-5 xl:grid-cols-2"><Panel><div className="flex items-center gap-2"><Archive size={16} className="text-gold"/><h2 className="text-sm font-extrabold text-white">Retention policies</h2></div><div className="mt-4 grid gap-2 sm:grid-cols-[1fr_120px_auto]"><input className={inputCls} value={policyName} onChange={e=>setPolicyName(e.target.value)} placeholder="Policy name"/><input className={inputCls} value={policyDays} onChange={e=>setPolicyDays(e.target.value)} inputMode="numeric" placeholder="Days"/><button className={btnPrimary} disabled={busy==='policy'} onClick={createPolicy}>Create</button></div><div className="mt-4 space-y-2">{retention.policies.map(p=><div key={p.id} className="flex flex-col gap-3 rounded-xl border border-white/10 p-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm font-bold text-white">{p.name}</p><p className="text-[11px] text-slate-500">{p.retention_days?`${p.retention_days} days`:'No automatic disposition'} · {p.active?'Active':'Inactive'}</p></div><button className={btnSecondary} disabled={!selected} onClick={()=>assignPolicy(p.id)}>Assign to Envelope</button></div>)}</div></Panel><Panel><div className="flex items-center gap-2"><Gavel size={16} className="text-gold"/><h2 className="text-sm font-extrabold text-white">Legal holds</h2></div><div className="mt-4 grid gap-2 sm:grid-cols-2"><select className={inputCls} value={holdScope} onChange={e=>setHoldScope(e.target.value as any)}><option value="envelope">Selected envelope</option><option value="global">Global hold</option></select><input className={inputCls} value={holdName} onChange={e=>setHoldName(e.target.value)} placeholder="Hold name"/><textarea className={`${inputCls} min-h-20 sm:col-span-2`} value={holdReason} onChange={e=>setHoldReason(e.target.value)} placeholder="Required legal/business reason"/><button className={btnPrimary} disabled={busy==='hold'||(!selected&&holdScope!=='global')} onClick={createHold}>Activate Hold</button></div><div className="mt-4 space-y-2">{retention.holds.map(h=><div key={h.id} className="flex items-center justify-between gap-3 rounded-xl border border-white/10 p-3"><div><p className="text-sm font-bold text-white">{h.name}</p><p className="mt-1 text-[11px] text-slate-500">{fmt(h.scope_type)} · {fmt(h.status)}</p></div>{h.status==='active'?<button className={btnSecondary} onClick={()=>releaseHold(h.id)}>Release</button>:<Tag>Released</Tag>}</div>)}</div></Panel></div>}

    <div className="border-t border-white/10 pt-6"><EnvelopeWorkspace/></div>
  </div>
}
