import { useCallback, useEffect, useState } from 'react'
import { api, ApiError } from '../../lib/api'
import { FieldPlacementCanvas } from '../../components/admin/FieldPlacementCanvas'
import { PageIntro, Panel, EmptyState, Tag, inputCls, btnPrimary, btnSecondary } from '../../components/admin/ui'
import { toast } from '../../components/kit/toast'

type Envelope={id:string;public_id:string;title:string;status:string;signer_count:number;completed_signer_count:number;created_at:string}
type Detail={envelope:any;recipients:any[];fields:any[];events:any[];seal?:any}

export default function EnvelopeWorkspace(){
  const [rows,setRows]=useState<Envelope[]>([]),[selected,setSelected]=useState<string>(''),[detail,setDetail]=useState<Detail|null>(null),[loading,setLoading]=useState(true)
  const [title,setTitle]=useState(''),[file,setFile]=useState<File|null>(null),[creating,setCreating]=useState(false),[sealing,setSealing]=useState(false)
  const [name,setName]=useState(''),[email,setEmail]=useState(''),[role,setRole]=useState('signer')
  const [recipientId,setRecipientId]=useState(''),[fieldType,setFieldType]=useState('signature'),[page,setPage]=useState(1)
  const load=useCallback(async()=>{setLoading(true);try{const r=await api.get<{envelopes:Envelope[]}>('/admin/envelopes');setRows(r.envelopes);if(!selected&&r.envelopes[0])setSelected(r.envelopes[0].id)}catch(e){toast.error(e instanceof ApiError?e.message:'Could not load envelopes')}finally{setLoading(false)}},[selected])
  const loadDetail=useCallback(async()=>{if(!selected){setDetail(null);return}try{const d=await api.get<Detail>(`/admin/envelopes/${selected}`);setDetail(d);if(!recipientId&&d.recipients[0])setRecipientId(d.recipients[0].id)}catch(e){toast.error(e instanceof ApiError?e.message:'Could not load envelope')}},[selected,recipientId])
  useEffect(()=>{void load()},[]); useEffect(()=>{void loadDetail()},[selected])
  async function create(){if(!file||!title.trim())return;setCreating(true);try{const up=await api.upload<{file:{id:string}}>('/admin/documents/upload',file);const e=await api.post<{id:string}>('/admin/envelopes',{title:title.trim(),source_file_id:up.file.id});setTitle('');setFile(null);setSelected(e.id);toast.success('Envelope created');await load()}catch(err){toast.error(err instanceof ApiError?err.message:'Could not create envelope')}finally{setCreating(false)}}
  async function addRecipient(){if(!selected||!name.trim()||!email.trim())return;try{await api.post(`/admin/envelopes/${selected}/recipients`,{name,email,role});setName('');setEmail('');toast.success('Signer added');await loadDetail()}catch(err){toast.error(err instanceof ApiError?err.message:'Could not add signer')}}
  async function placeField(pos:{x:number;y:number;width:number;height:number}){if(!selected||!recipientId)return;try{await api.post(`/admin/envelopes/${selected}/fields`,{recipient_id:recipientId,field_type:fieldType,page_number:page,...pos,required:true});toast.success(`${fieldType[0].toUpperCase()+fieldType.slice(1)} field placed`);await loadDetail()}catch(err){toast.error(err instanceof ApiError?err.message:'Could not place field')}}
  async function send(){if(!selected)return;try{await api.post(`/admin/envelopes/${selected}/send`,{});toast.success('Envelope sent');await Promise.all([load(),loadDetail()])}catch(err){toast.error(err instanceof ApiError?err.message:'Could not send envelope')}}
  async function seal(){if(!selected)return;setSealing(true);try{await api.post(`/admin/envelopes/${selected}/seal`,{});toast.success('Final signed PDF, audit certificate, and evidence manifest sealed and archived.');await loadDetail()}catch(err){toast.error(err instanceof ApiError?err.message:'Could not seal envelope')}finally{setSealing(false)}}
  return <div>
    <PageIntro kicker="Documents" title="Envelope Workspace" subtitle="Prepare, route, authenticate, sign, seal, and archive documents from one controlled internal workflow." />
    <Panel className="mb-6 border-gold/20 bg-gradient-to-br from-gold/[.06] via-transparent to-transparent"><div className="grid gap-5 lg:grid-cols-[1fr_1fr_auto] lg:items-end"><label><span className="mb-1 block text-xs text-slate-400">Envelope title</span><input className={inputCls} value={title} onChange={e=>setTitle(e.target.value)} placeholder="Engagement agreement"/></label><label><span className="mb-1 block text-xs text-slate-400">PDF source</span><input className={inputCls} type="file" accept="application/pdf,.pdf" onChange={e=>setFile(e.target.files?.[0]||null)}/><span className="mt-1 block text-[11px] text-slate-500">PDF is required for precise field rendering and final archival.</span></label><button className={btnPrimary} disabled={!file||!title.trim()||creating} onClick={create}>{creating?'Creating…':'Create Envelope'}</button></div></Panel>
    <div className="grid gap-6 xl:grid-cols-[330px_1fr]">
      <Panel className="!p-0 overflow-hidden"><div className="border-b border-white/10 px-5 py-4"><p className="eyebrow">Envelopes</p></div>{loading?<p className="p-5 text-sm text-slate-400">Loading…</p>:rows.length===0?<div className="p-5"><EmptyState label="No envelopes yet."/></div>:<div>{rows.map(r=><button key={r.id} onClick={()=>setSelected(r.id)} className={`w-full border-b border-white/5 px-5 py-4 text-left last:border-0 ${selected===r.id?'bg-gold/[.06]':'hover:bg-white/[.025]'}`}><div className="flex items-start justify-between gap-3"><div><p className="font-medium text-white">{r.title}</p><p className="mt-1 text-xs text-slate-500">{r.public_id}</p></div><Tag tone={r.status==='completed'?'green':r.status==='declined'?'red':r.status==='sent'||r.status==='viewed'||r.status==='in_progress'?'blue':'slate'}>{r.status.replace('_',' ')}</Tag></div><p className="mt-3 text-xs text-slate-500">{r.completed_signer_count}/{r.signer_count} completed · {new Date(r.created_at).toLocaleDateString()}</p></button>)}</div>}</Panel>
      <div className="space-y-6">{!detail?<Panel><EmptyState label="Select an envelope to manage it."/></Panel>:<>
        <Panel><div className="flex flex-col gap-5 lg:flex-row lg:items-start lg:justify-between"><div><p className="eyebrow">{detail.envelope.public_id}</p><h2 className="mt-1 font-display text-2xl text-white">{detail.envelope.title}</h2><p className="mt-2 text-sm text-slate-400">Status: <span className="text-white">{detail.envelope.status.replace('_',' ')}</span></p></div><div className="flex flex-wrap gap-2">{detail.envelope.status==='draft'&&<button className={btnPrimary} onClick={send}>Send Envelope</button>}{detail.envelope.status==='completed'&&!detail.seal&&<button className={btnPrimary} disabled={sealing} onClick={seal}>{sealing?'Sealing…':'Seal & Archive'}</button>}</div></div>
          {detail.seal&&<div className="mt-5 border-t border-white/10 pt-5"><div className="flex flex-wrap items-center gap-2"><Tag tone="green">Sealed</Tag><span className="text-xs text-slate-500">{detail.seal.signature_algorithm} · {detail.seal.public_key_id}</span></div><div className="mt-4 flex flex-wrap gap-2"><a className={btnSecondary} href={`/api/admin/envelopes/${selected}/artifacts/signed`} target="_blank" rel="noreferrer">Signed PDF</a><a className={btnSecondary} href={`/api/admin/envelopes/${selected}/artifacts/audit`} target="_blank" rel="noreferrer">Audit Certificate</a><a className={btnSecondary} href={`/api/admin/envelopes/${selected}/artifacts/manifest`} target="_blank" rel="noreferrer">Evidence Manifest</a></div></div>}
        </Panel>
        <Panel><div className="grid gap-3 md:grid-cols-[1fr_180px_120px] md:items-end"><label><span className="mb-1 block text-xs text-slate-400">Place for</span><select className={inputCls} value={recipientId} onChange={e=>setRecipientId(e.target.value)}><option value="">Choose recipient…</option>{detail.recipients.map(r=><option key={r.id} value={r.id}>{r.name} · {r.role}</option>)}</select></label><label><span className="mb-1 block text-xs text-slate-400">Field</span><select className={inputCls} value={fieldType} onChange={e=>setFieldType(e.target.value)}>{['signature','initial','date','text','checkbox'].map(t=><option key={t} value={t}>{t[0].toUpperCase()+t.slice(1)}</option>)}</select></label><label><span className="mb-1 block text-xs text-slate-400">Page</span><input className={inputCls} type="number" min="1" value={page} onChange={e=>setPage(Math.max(1,Number(e.target.value)||1))}/></label></div><div className="mt-5"><FieldPlacementCanvas envelopeId={selected} page={page} recipientId={recipientId} fieldType={fieldType} fields={detail.fields} recipients={detail.recipients} onPlace={placeField}/></div></Panel>
        <div className="grid gap-6 lg:grid-cols-2"><Panel><p className="eyebrow">Recipients</p><div className="mt-4 grid gap-3 sm:grid-cols-2"><input className={inputCls} value={name} onChange={e=>setName(e.target.value)} placeholder="Full name"/><input className={inputCls} value={email} onChange={e=>setEmail(e.target.value)} placeholder="Email"/><select className={inputCls} value={role} onChange={e=>setRole(e.target.value)}><option value="signer">Signer</option><option value="approver">Approver</option><option value="witness">Witness</option><option value="notary">Notary</option><option value="cc">CC</option></select><button className={btnSecondary} onClick={addRecipient}>Add Recipient</button></div><div className="mt-5 space-y-2">{detail.recipients.map(r=><div key={r.id} className="flex items-center justify-between rounded-lg border border-white/10 px-3 py-2"><div><p className="text-sm text-white">{r.name}</p><p className="text-xs text-slate-500">{r.email} · {r.role}</p></div><Tag>{r.status}</Tag></div>)}</div></Panel><Panel><p className="eyebrow">Placed fields</p><div className="mt-4 space-y-2">{detail.fields.length===0?<EmptyState label="No fields placed yet. Choose a field above and click the document."/>:detail.fields.map(f=><div key={f.id} className="flex items-center justify-between rounded-lg border border-white/10 px-3 py-2"><div><p className="text-sm text-white">{f.field_type[0].toUpperCase()+f.field_type.slice(1)}</p><p className="text-xs text-slate-500">Page {f.page_number} · {detail.recipients.find(r=>r.id===f.recipient_id)?.name||'Recipient'}</p></div><Tag>placed</Tag></div>)}</div></Panel></div>
        <Panel><p className="eyebrow">Evidence timeline</p><div className="mt-4 space-y-3">{detail.events.map(e=><div key={e.id} className="grid gap-1 border-l border-gold/25 pl-4 sm:grid-cols-[170px_1fr]"><p className="text-xs text-slate-500">{new Date(e.occurred_at_utc).toLocaleString()}</p><div><p className="text-sm text-white">{e.event_type.replaceAll('.',' · ')}</p><p className="mt-1 break-all text-[11px] text-slate-600">{String(e.event_hash).slice(0,32)}…</p></div></div>)}</div></Panel>
      </>}</div>
    </div>
  </div>
}