import { useCallback, useEffect, useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { api, ApiError } from '../../lib/api'
import { useAppPath } from '../../lib/basePath'
import { useLiveRefresh } from '../../lib/liveRefresh'
import { PageIntro, Panel, Tag, btnOutline, btnPrimary, inputCls, SkeletonTable, EmptyState } from '../../components/admin/ui'
import { toast } from '../../components/kit/toast'

interface Scorecard {
  generated_at:string
  portfolio:{open_matters:number;overdue_tasks:number;open_tickets:number;open_receivables_cents:number}
  workload_capacity:Array<{id:string;employee:string;email:string;assigned_clients:number;open_tasks:number;overdue_tasks:number;completed_tasks_30d:number;open_tickets:number;interactions_30d:number;emails_30d:number;avg_response_hours:number|null;load_index:number;workload_status:string}>
  project_health:Array<{id:string;title:string;client:string;email:string;status:string;due_date:string|null;open_tasks:number;overdue_tasks:number;open_invoice_cents:number;last_activity_at:string|null;health:string;days_to_due:number|null;inactive_days:number}>
  pipeline_aging:Array<{stage:string;count:number;avg_age_days:number;aged_14d:number}>
  receivables:{open_cents:number;overdue_cents:number;due_7d_cents:number;due_30d_cents:number;open_count:number}
}
interface Template {id:string;name:string;report_key:string;filters_json:string;created_at:string;schedule_kind:string|null;schedule_time:string|null;schedule_day:number|null;recipients_json:string|null;enabled:number;next_run_at:string|null;last_run_at:string|null;last_status:string|null;last_error:string|null}
function money(cents:number){return(cents/100).toLocaleString(undefined,{style:'currency',currency:'USD'})}
function when(v:string|null){return v?new Date(v).toLocaleString():'Not provided'}
const healthTone:Record<string,'green'|'gold'|'red'|'slate'>={on_track:'green',watch:'gold',at_risk:'red',balanced:'green',high:'red'}

export default function ManagementCenter(){
  const p=useAppPath();const[data,setData]=useState<Scorecard|null>(null);const[templates,setTemplates]=useState<Template[]>([]);const[loading,setLoading]=useState(true);const[busy,setBusy]=useState<string|null>(null);const[editing,setEditing]=useState<Template|null>(null);const[recipients,setRecipients]=useState('')
  const load=useCallback(async(silent=false)=>{if(!silent)setLoading(true);try{const[s,t]=await Promise.all([api.get<Scorecard>('/admin/management/scorecard'),api.get<{templates:Template[]}>('/admin/report-templates')]);setData(s);setTemplates(t.templates)}catch(err){if(!silent)toast.error(err instanceof ApiError?err.message:'Could not load management data.')}finally{if(!silent)setLoading(false)}},[])
  useEffect(()=>{void load()},[load]);useLiveRefresh(useCallback(()=>load(true),[load]))
  const healthCounts=useMemo(()=>({atRisk:data?.project_health.filter(x=>x.health==='at_risk').length||0,watch:data?.project_health.filter(x=>x.health==='watch').length||0,onTrack:data?.project_health.filter(x=>x.health==='on_track').length||0}),[data])
  function edit(t:Template){setEditing({...t});let r:string[]=[];try{r=JSON.parse(t.recipients_json||'[]')}catch{}setRecipients(r.join(', '))}
  async function saveSchedule(){if(!editing)return;setBusy(editing.id);try{await api.patch(`/admin/report-templates/${editing.id}/schedule`,{schedule_kind:editing.schedule_kind,schedule_time:editing.schedule_time||'08:00',schedule_day:editing.schedule_day,recipients:recipients.split(/[;,\n]/).map(x=>x.trim()).filter(Boolean),enabled:!!editing.enabled});toast.success('Report schedule saved.');setEditing(null);await load()}catch(err){toast.error(err instanceof ApiError?err.message:'Could not save report schedule.')}finally{setBusy(null)}}
  async function deliver(t:Template){if(!window.confirm(`Generate and deliver ${t.name} now?`))return;setBusy(`deliver:${t.id}`);try{const r=await api.post<{rows:number;recipients:number}>(`/admin/report-templates/${t.id}/deliver-now`);toast.success(`Report generated: ${r.rows} row${r.rows===1?'':'s'}, ${r.recipients} recipient${r.recipients===1?'':'s'}.`);await load()}catch(err){toast.error(err instanceof ApiError?err.message:'Could not deliver this report.')}finally{setBusy(null)}}
  if(loading&&!data)return <div><PageIntro kicker="Intelligence" title="Management Center" subtitle="Operational health, workload, pipeline aging and scheduled management reporting."/><SkeletonTable rows={6} cols={6}/></div>
  return <div className="mx-auto max-w-[1550px]">
    <PageIntro kicker="Management Intelligence" title="Management Center" subtitle="A decision-focused view of delivery risk, team workload, pipeline aging, receivables and recurring management reporting." action={<Link to={p('reports')} className={btnOutline}>Open report library</Link>}/>
    {data&&<div className="mb-6 grid grid-cols-2 gap-3 lg:grid-cols-4"><Metric label="Open matters" value={data.portfolio.open_matters}/><Metric label="Overdue tasks" value={data.portfolio.overdue_tasks} warn={data.portfolio.overdue_tasks>0}/><Metric label="Open tickets" value={data.portfolio.open_tickets}/><Metric label="Open receivables" value={money(data.portfolio.open_receivables_cents)} /></div>}

    <div className="grid gap-6 xl:grid-cols-[1.08fr_.92fr]">
      <Panel className="!p-0 overflow-hidden"><div className="border-b border-white/10 px-5 py-4"><div className="flex items-center justify-between"><div><p className="text-xs uppercase tracking-[.15em] text-slate-500">Team operations</p><h2 className="mt-1 text-base font-semibold text-white">Workload & capacity</h2></div><p className="text-xs text-slate-500">Load index is workload, not billable utilization</p></div></div>{!data?.workload_capacity.length?<div className="p-5"><EmptyState label="No staff workload data yet."/></div>:<div className="overflow-x-auto"><table className="w-full min-w-[900px] text-sm"><thead><tr className="border-b border-white/10 text-left text-xs uppercase tracking-wide text-slate-500"><th className="px-4 py-3">Team member</th><th className="px-4 py-3">Clients</th><th className="px-4 py-3">Open</th><th className="px-4 py-3">Overdue</th><th className="px-4 py-3">Completed · 30d</th><th className="px-4 py-3">Avg response</th><th className="px-4 py-3">Load</th></tr></thead><tbody>{data.workload_capacity.map(r=><tr key={r.id} className="border-b border-white/5 last:border-0"><td className="px-4 py-3"><p className="font-medium text-white">{r.employee}</p><p className="text-xs text-slate-500">{r.email}</p></td><td className="px-4 py-3 text-slate-300">{r.assigned_clients}</td><td className="px-4 py-3 text-slate-300">{r.open_tasks+r.open_tickets}</td><td className={`px-4 py-3 ${r.overdue_tasks?'text-rose-300':'text-slate-300'}`}>{r.overdue_tasks}</td><td className="px-4 py-3 text-slate-300">{r.completed_tasks_30d}</td><td className="px-4 py-3 text-slate-400">{r.avg_response_hours==null?'Not provided':`${r.avg_response_hours}h`}</td><td className="px-4 py-3"><Tag tone={healthTone[r.workload_status]||'gold'}>{r.workload_status} · {r.load_index}</Tag></td></tr>)}</tbody></table></div>}</Panel>
      <Panel><div className="flex items-start justify-between gap-4"><div><p className="text-xs uppercase tracking-[.15em] text-slate-500">Delivery health</p><h2 className="mt-1 text-base font-semibold text-white">Active project portfolio</h2></div><div className="flex gap-2"><Tag tone="red">{healthCounts.atRisk} at risk</Tag><Tag tone="gold">{healthCounts.watch} watch</Tag></div></div><div className="mt-5 space-y-3">{data?.project_health.slice(0,10).map(r=><div key={r.id} className="rounded-lg border border-white/8 bg-white/[.018] p-3"><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-medium text-white">{r.title}</p><p className="mt-1 text-xs text-slate-500">{r.client} · {r.open_tasks} open task{r.open_tasks===1?'':'s'} · {money(r.open_invoice_cents)} open</p></div><Tag tone={healthTone[r.health]||'slate'}>{r.health.replace('_',' ')}</Tag></div>{r.health!=='on_track'&&<p className="mt-2 text-xs text-slate-400">{r.overdue_tasks?`${r.overdue_tasks} overdue task${r.overdue_tasks===1?'':'s'}. `:''}{r.days_to_due!=null?`Due ${r.days_to_due<0?`${Math.abs(r.days_to_due)} day(s) ago`:`in ${r.days_to_due} day(s)`}. `:''}{r.inactive_days>=14?`No recorded client activity for ${r.inactive_days} days.`:''}</p>}</div>)}{!data?.project_health.length&&<EmptyState label="No active projects."/>}</div></Panel>
    </div>

    <div className="mt-6 grid gap-6 lg:grid-cols-2"><Panel><p className="text-xs uppercase tracking-[.15em] text-slate-500">Revenue pipeline</p><h2 className="mt-1 text-base font-semibold text-white">Pipeline aging</h2><div className="mt-4 divide-y divide-white/8">{data?.pipeline_aging.map(r=><div key={r.stage} className="grid grid-cols-[1fr_auto_auto] gap-4 py-3 text-sm"><div className="capitalize text-slate-200">{r.stage.replace(/_/g,' ')}</div><div className="text-right"><strong className="text-white">{r.count}</strong><span className="ml-1 text-xs text-slate-500">records</span></div><div className="min-w-[110px] text-right text-xs text-slate-500">avg {r.avg_age_days||0}d · {r.aged_14d||0} aged 14d+</div></div>)}</div></Panel><Panel><p className="text-xs uppercase tracking-[.15em] text-slate-500">Cash visibility</p><h2 className="mt-1 text-base font-semibold text-white">Receivables outlook</h2>{data&&<div className="mt-5 grid grid-cols-2 gap-3"><Mini label="Open" value={money(data.receivables.open_cents)}/><Mini label="Overdue" value={money(data.receivables.overdue_cents)} warn={data.receivables.overdue_cents>0}/><Mini label="Due next 7 days" value={money(data.receivables.due_7d_cents)}/><Mini label="Due days 8–30" value={money(data.receivables.due_30d_cents)}/></div>}<p className="mt-4 text-xs leading-5 text-slate-500">This is a receivables outlook based on invoices already issued. It is intentionally not labeled a revenue forecast because PMV does not yet require probability-weighted project forecasts.</p></Panel></div>

    <Panel className="mt-6 !p-0 overflow-hidden"><div className="flex flex-wrap items-start justify-between gap-3 border-b border-white/10 px-5 py-4"><div><p className="text-xs uppercase tracking-[.15em] text-slate-500">Recurring management cadence</p><h2 className="mt-1 text-base font-semibold text-white">Scheduled reports</h2><p className="mt-1 text-xs text-slate-500">Save a report in the Report Library, then configure delivery here. CSV attachments are generated at send time.</p></div><Link to={p('reports')} className={btnPrimary}>Create saved report</Link></div>{templates.length===0?<div className="p-5"><EmptyState label="No saved reports yet."/></div>:<div className="overflow-x-auto"><table className="w-full min-w-[980px] text-sm"><thead><tr className="border-b border-white/10 text-left text-xs uppercase tracking-wide text-slate-500"><th className="px-4 py-3">Saved report</th><th className="px-4 py-3">Schedule</th><th className="px-4 py-3">Next</th><th className="px-4 py-3">Last</th><th className="px-4 py-3">Status</th><th className="px-4 py-3"></th></tr></thead><tbody>{templates.map(t=><tr key={t.id} className="border-b border-white/5 last:border-0"><td className="px-4 py-3"><p className="font-medium text-white">{t.name}</p><p className="text-xs text-slate-500">{t.report_key.replace(/_/g,' ')}</p></td><td className="px-4 py-3 capitalize text-slate-300">{t.enabled&&t.schedule_kind?`${t.schedule_kind} · ${t.schedule_time||'08:00'} ET`:'Off'}</td><td className="px-4 py-3 text-slate-500">{when(t.next_run_at)}</td><td className="px-4 py-3 text-slate-500">{when(t.last_run_at)}</td><td className="px-4 py-3">{t.last_status?<Tag tone={t.last_status==='succeeded'?'green':'red'}>{t.last_status}</Tag>:<span className="text-slate-500">:</span>}{t.last_error&&<p className="mt-1 max-w-[260px] truncate text-xs text-rose-300" title={t.last_error}>{t.last_error}</p>}</td><td className="px-4 py-3 text-right"><div className="flex justify-end gap-3"><button className="text-xs font-medium text-gold hover:underline" onClick={()=>edit(t)}>Schedule</button><button className="text-xs font-medium text-slate-300 hover:text-white" disabled={busy===`deliver:${t.id}`} onClick={()=>deliver(t)}>{busy===`deliver:${t.id}`?'Sending…':'Deliver now'}</button></div></td></tr>)}</tbody></table></div>}</Panel>

    {editing&&<div className="fixed inset-0 z-50 grid place-items-center bg-black/70 p-4" onMouseDown={()=>setEditing(null)}><div className="w-full max-w-xl rounded-xl border border-white/10 bg-navy-950 p-5 shadow-2xl" onMouseDown={e=>e.stopPropagation()}><div className="flex items-start justify-between gap-3"><div><p className="eyebrow">Scheduled report</p><h3 className="mt-1 text-lg font-semibold text-white">{editing.name}</h3></div><button className={btnOutline} onClick={()=>setEditing(null)}>Close</button></div><div className="mt-5 grid gap-4 sm:grid-cols-2"><label><span className="mb-1 block text-xs text-slate-400">Frequency</span><select className={inputCls} value={editing.schedule_kind||''} onChange={e=>setEditing({...editing,schedule_kind:e.target.value||null,enabled:e.target.value?1:0})}><option value="">Off</option><option value="daily">Daily</option><option value="weekly">Weekly</option><option value="monthly">Monthly</option></select></label><label><span className="mb-1 block text-xs text-slate-400">Time · Eastern</span><input type="time" className={inputCls} value={editing.schedule_time||'08:00'} onChange={e=>setEditing({...editing,schedule_time:e.target.value})}/></label>{editing.schedule_kind==='weekly'&&<label><span className="mb-1 block text-xs text-slate-400">Day</span><select className={inputCls} value={editing.schedule_day??1} onChange={e=>setEditing({...editing,schedule_day:Number(e.target.value)})}>{['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'].map((d,i)=><option key={d} value={i}>{d}</option>)}</select></label>}{editing.schedule_kind==='monthly'&&<label><span className="mb-1 block text-xs text-slate-400">Day of month</span><input className={inputCls} type="number" min={1} max={28} value={editing.schedule_day??1} onChange={e=>setEditing({...editing,schedule_day:Number(e.target.value)})}/></label>}<label className="sm:col-span-2"><span className="mb-1 block text-xs text-slate-400">Recipients</span><textarea className={`${inputCls} min-h-[90px]`} value={recipients} onChange={e=>setRecipients(e.target.value)} placeholder="owner@example.com, manager@example.com"/><span className="mt-1 block text-xs text-slate-500">Up to 25 authorized recipients. Separate addresses with commas or new lines.</span></label></div><div className="mt-5 flex justify-end"><button className={btnPrimary} disabled={busy===editing.id} onClick={saveSchedule}>{busy===editing.id?'Saving…':'Save schedule'}</button></div></div></div>}
  </div>
}
function Metric({label,value,warn=false}:{label:string;value:string|number;warn?:boolean}){return <Panel className="!p-4"><p className="text-xs uppercase tracking-wide text-slate-500">{label}</p><p className={`mt-2 text-3xl font-semibold ${warn?'text-rose-300':'text-white'}`}>{value}</p></Panel>}
function Mini({label,value,warn=false}:{label:string;value:string;warn?:boolean}){return <div className="rounded-lg border border-white/8 bg-white/[.02] p-3"><p className="text-xs text-slate-500">{label}</p><p className={`mt-1 text-lg font-semibold ${warn?'text-rose-300':'text-white'}`}>{value}</p></div>}
